-- =====================================================
-- MatchMatrix
-- Seed: Countries
-- File: 004_seed_countries.sql
-- Purpose: základní státy + sportovní regiony
-- =====================================================

INSERT INTO public.countries (iso2, iso3, name, continent_code)
SELECT v.iso2, v.iso3, v.name, v.continent_code
FROM (
    VALUES
    -- SPECIAL / SPORT REGIONS
    ('EU','EUR','Europe','EU'),
    ('WO','WRL','World','WORLD'),
    ('SA','SAM','South America','SA'),
    ('SC','SCO','Scotland','EU'),
    ('GB','ENG','England','EU'),
    ('GB','WLS','Wales','EU'),
    ('GB','NIR','Northern Ireland','EU'),

    -- EUROPE
    ('GB','GBR','United Kingdom','EU'),
    ('IE','IRL','Ireland','EU'),
    ('ES','ESP','Spain','EU'),
    ('DE','DEU','Germany','EU'),
    ('IT','ITA','Italy','EU'),
    ('FR','FRA','France','EU'),
    ('NL','NLD','Netherlands','EU'),
    ('PT','PRT','Portugal','EU'),
    ('BE','BEL','Belgium','EU'),
    ('TR','TUR','Turkey','EU'),
    ('CH','CHE','Switzerland','EU'),
    ('AT','AUT','Austria','EU'),
    ('PL','POL','Poland','EU'),
    ('CZ','CZE','Czech Republic','EU'),
    ('SK','SVK','Slovakia','EU'),
    ('HU','HUN','Hungary','EU'),
    ('RO','ROU','Romania','EU'),
    ('BG','BGR','Bulgaria','EU'),
    ('HR','HRV','Croatia','EU'),
    ('RS','SRB','Serbia','EU'),
    ('BA','BIH','Bosnia and Herzegovina','EU'),
    ('SI','SVN','Slovenia','EU'),
    ('ME','MNE','Montenegro','EU'),
    ('MK','MKD','North Macedonia','EU'),
    ('AL','ALB','Albania','EU'),
    ('GR','GRC','Greece','EU'),
    ('CY','CYP','Cyprus','EU'),
    ('DK','DNK','Denmark','EU'),
    ('SE','SWE','Sweden','EU'),
    ('NO','NOR','Norway','EU'),
    ('FI','FIN','Finland','EU'),
    ('IS','ISL','Iceland','EU'),
    ('UA','UKR','Ukraine','EU'),
    ('BY','BLR','Belarus','EU'),
    ('LT','LTU','Lithuania','EU'),
    ('LV','LVA','Latvia','EU'),
    ('EE','EST','Estonia','EU'),
    ('LU','LUX','Luxembourg','EU'),
    ('MT','MLT','Malta','EU'),
    ('AD','AND','Andorra','EU'),
    ('SM','SMR','San Marino','EU'),
    ('LI','LIE','Liechtenstein','EU'),
    ('MC','MCO','Monaco','EU'),
    ('MD','MDA','Moldova','EU'),
    ('XK','XKX','Kosovo','EU'),
    ('AM','ARM','Armenia','EU'),
    ('GE','GEO','Georgia','EU'),
    ('AZ','AZE','Azerbaijan','EU'),

    -- SOUTH AMERICA
    ('BR','BRA','Brazil','SA'),
    ('AR','ARG','Argentina','SA'),
    ('UY','URY','Uruguay','SA'),
    ('PY','PRY','Paraguay','SA'),
    ('CL','CHL','Chile','SA'),
    ('BO','BOL','Bolivia','SA'),
    ('PE','PER','Peru','SA'),
    ('EC','ECU','Ecuador','SA'),
    ('CO','COL','Colombia','SA'),
    ('VE','VEN','Venezuela','SA'),
    ('GY','GUY','Guyana','SA'),
    ('SR','SUR','Suriname','SA'),

    -- NORTH & CENTRAL AMERICA
    ('US','USA','United States','NA'),
    ('CA','CAN','Canada','NA'),
    ('MX','MEX','Mexico','NA'),
    ('CR','CRI','Costa Rica','NA'),
    ('PA','PAN','Panama','NA'),
    ('HN','HND','Honduras','NA'),
    ('SV','SLV','El Salvador','NA'),
    ('GT','GTM','Guatemala','NA'),
    ('NI','NIC','Nicaragua','NA'),
    ('JM','JAM','Jamaica','NA'),
    ('HT','HTI','Haiti','NA'),
    ('DO','DOM','Dominican Republic','NA'),
    ('TT','TTO','Trinidad and Tobago','NA'),
    ('CU','CUB','Cuba','NA'),

    -- AFRICA
    ('MA','MAR','Morocco','AF'),
    ('DZ','DZA','Algeria','AF'),
    ('TN','TUN','Tunisia','AF'),
    ('EG','EGY','Egypt','AF'),
    ('LY','LBY','Libya','AF'),
    ('SN','SEN','Senegal','AF'),
    ('CI','CIV','Ivory Coast','AF'),
    ('GH','GHA','Ghana','AF'),
    ('NG','NGA','Nigeria','AF'),
    ('CM','CMR','Cameroon','AF'),
    ('ZA','ZAF','South Africa','AF'),
    ('KE','KEN','Kenya','AF'),
    ('UG','UGA','Uganda','AF'),
    ('TZ','TZA','Tanzania','AF'),
    ('ML','MLI','Mali','AF'),
    ('BF','BFA','Burkina Faso','AF'),
    ('GN','GIN','Guinea','AF'),
    ('CD','COD','DR Congo','AF'),
    ('CG','COG','Congo','AF'),
    ('GA','GAB','Gabon','AF'),
    ('ZM','ZMB','Zambia','AF'),
    ('ZW','ZWE','Zimbabwe','AF'),
    ('AO','AGO','Angola','AF'),
    ('MZ','MOZ','Mozambique','AF'),

    -- ASIA
    ('CN','CHN','China','AS'),
    ('JP','JPN','Japan','AS'),
    ('KR','KOR','South Korea','AS'),
    ('KP','PRK','North Korea','AS'),
    ('IN','IND','India','AS'),
    ('ID','IDN','Indonesia','AS'),
    ('TH','THA','Thailand','AS'),
    ('VN','VNM','Vietnam','AS'),
    ('MY','MYS','Malaysia','AS'),
    ('SG','SGP','Singapore','AS'),
    ('PH','PHL','Philippines','AS'),
    ('HK','HKG','Hong Kong','AS'),
    ('TW','TWN','Taiwan','AS'),
    ('MO','MAC','Macau','AS'),
    ('SA','SAU','Saudi Arabia','AS'),
    ('AE','ARE','United Arab Emirates','AS'),
    ('QA','QAT','Qatar','AS'),
    ('KW','KWT','Kuwait','AS'),
    ('BH','BHR','Bahrain','AS'),
    ('OM','OMN','Oman','AS'),
    ('JO','JOR','Jordan','AS'),
    ('LB','LBN','Lebanon','AS'),
    ('SY','SYR','Syria','AS'),
    ('IQ','IRQ','Iraq','AS'),
    ('IR','IRN','Iran','AS'),
    ('IL','ISR','Israel','AS'),
    ('PS','PSE','Palestine','AS'),
    ('UZ','UZB','Uzbekistan','AS'),
    ('KZ','KAZ','Kazakhstan','AS'),
    ('KG','KGZ','Kyrgyzstan','AS'),
    ('TJ','TJK','Tajikistan','AS'),
    ('TM','TKM','Turkmenistan','AS'),
    ('AF','AFG','Afghanistan','AS'),
    ('PK','PAK','Pakistan','AS'),
    ('BD','BGD','Bangladesh','AS'),
    ('LK','LKA','Sri Lanka','AS'),
    ('NP','NPL','Nepal','AS'),

    -- OCEANIA
    ('AU','AUS','Australia','OC'),
    ('NZ','NZL','New Zealand','OC'),
    ('FJ','FJI','Fiji','OC'),
    ('PG','PNG','Papua New Guinea','OC'),
    ('NC','NCL','New Caledonia','OC')
) AS v(iso2, iso3, name, continent_code)
WHERE NOT EXISTS (
    SELECT 1
    FROM public.countries c
    WHERE c.iso3 = v.iso3
);