-- =========================================================
-- MatchMatrix
-- Soubor: 2026-03-29_01_create_table_standings_rules.sql
-- Účel: pravidla bodování pro standings (multi-sport)
-- =========================================================

CREATE TABLE IF NOT EXISTS public.standings_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sport_id integer NOT NULL,
    league_id integer NULL, -- pokud NULL = default pro sport

    win_points numeric NOT NULL DEFAULT 3,
    draw_points numeric NOT NULL DEFAULT 1,
    loss_points numeric NOT NULL DEFAULT 0,

    allow_draws boolean NOT NULL DEFAULT true,

    -- speciální sporty (hokej OT/SO apod.)
    overtime_win_points numeric,
    overtime_loss_points numeric,

    rules_name text,
    rules_description text,

    is_default boolean NOT NULL DEFAULT false,

    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),

    CONSTRAINT fk_standings_rules_sport
        FOREIGN KEY (sport_id) REFERENCES public.sports(id),

    CONSTRAINT fk_standings_rules_league
        FOREIGN KEY (league_id) REFERENCES public.leagues(id),

    CONSTRAINT ux_standings_rules_unique
        UNIQUE (sport_id, league_id)
);

-- indexy
CREATE INDEX IF NOT EXISTS ix_standings_rules_sport
    ON public.standings_rules (sport_id);

CREATE INDEX IF NOT EXISTS ix_standings_rules_league
    ON public.standings_rules (league_id);

-- trigger na updated_at
CREATE OR REPLACE FUNCTION public.trg_set_updated_at_standings_rules()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_standings_rules_updated_at ON public.standings_rules;

CREATE TRIGGER trg_standings_rules_updated_at
BEFORE UPDATE ON public.standings_rules
FOR EACH ROW
EXECUTE FUNCTION public.trg_set_updated_at_standings_rules();