-- =========================================================
-- MatchMatrix
-- Soubor: C:\MatchMatrix-platform\db\migrations\2026-03-29_02_create_table_league_standings.sql
-- Účel: fyzická tabulka ligových tabulek pro všechny sporty a sezony
-- Spouštět v DBeaveru
-- =========================================================

CREATE TABLE IF NOT EXISTS public.league_standings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    league_id integer NOT NULL,
    season text NOT NULL,
    team_id integer NOT NULL,

    position integer,
    played integer NOT NULL DEFAULT 0,
    wins integer NOT NULL DEFAULT 0,
    draws integer NOT NULL DEFAULT 0,
    losses integer NOT NULL DEFAULT 0,

    goals_for integer NOT NULL DEFAULT 0,
    goals_against integer NOT NULL DEFAULT 0,
    goal_diff integer NOT NULL DEFAULT 0,
    points numeric NOT NULL DEFAULT 0,

    home_played integer NOT NULL DEFAULT 0,
    home_wins integer NOT NULL DEFAULT 0,
    home_draws integer NOT NULL DEFAULT 0,
    home_losses integer NOT NULL DEFAULT 0,
    home_goals_for integer NOT NULL DEFAULT 0,
    home_goals_against integer NOT NULL DEFAULT 0,
    home_goal_diff integer NOT NULL DEFAULT 0,
    home_points numeric NOT NULL DEFAULT 0,

    away_played integer NOT NULL DEFAULT 0,
    away_wins integer NOT NULL DEFAULT 0,
    away_draws integer NOT NULL DEFAULT 0,
    away_losses integer NOT NULL DEFAULT 0,
    away_goals_for integer NOT NULL DEFAULT 0,
    away_goals_against integer NOT NULL DEFAULT 0,
    away_goal_diff integer NOT NULL DEFAULT 0,
    away_points numeric NOT NULL DEFAULT 0,

    form_last_5 text,
    form_last_10 text,
    form_last_15 text,

    wins_last_5 integer NOT NULL DEFAULT 0,
    draws_last_5 integer NOT NULL DEFAULT 0,
    losses_last_5 integer NOT NULL DEFAULT 0,
    points_last_5 numeric NOT NULL DEFAULT 0,

    wins_last_10 integer NOT NULL DEFAULT 0,
    draws_last_10 integer NOT NULL DEFAULT 0,
    losses_last_10 integer NOT NULL DEFAULT 0,
    points_last_10 numeric NOT NULL DEFAULT 0,

    wins_last_15 integer NOT NULL DEFAULT 0,
    draws_last_15 integer NOT NULL DEFAULT 0,
    losses_last_15 integer NOT NULL DEFAULT 0,
    points_last_15 numeric NOT NULL DEFAULT 0,

    table_type text NOT NULL DEFAULT 'overall',
    standings_source text NOT NULL DEFAULT 'computed_from_matches',

    computed_at timestamp with time zone NOT NULL DEFAULT now(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),

    CONSTRAINT fk_league_standings_league
        FOREIGN KEY (league_id) REFERENCES public.leagues(id),

    CONSTRAINT fk_league_standings_team
        FOREIGN KEY (team_id) REFERENCES public.teams(id),

    CONSTRAINT chk_league_standings_table_type
        CHECK (table_type IN ('overall', 'home', 'away')),

    CONSTRAINT uq_league_standings
        UNIQUE (league_id, season, team_id, table_type)
);

CREATE INDEX IF NOT EXISTS ix_league_standings_league_season_pos
    ON public.league_standings (league_id, season, table_type, position);

CREATE INDEX IF NOT EXISTS ix_league_standings_team_season
    ON public.league_standings (team_id, season);

CREATE INDEX IF NOT EXISTS ix_league_standings_points
    ON public.league_standings (league_id, season, table_type, points DESC, goal_diff DESC, goals_for DESC);

CREATE OR REPLACE FUNCTION public.trg_set_updated_at_league_standings()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_league_standings_updated_at ON public.league_standings;

CREATE TRIGGER trg_league_standings_updated_at
BEFORE UPDATE ON public.league_standings
FOR EACH ROW
EXECUTE FUNCTION public.trg_set_updated_at_league_standings();