-- =========================================================
-- MatchMatrix
-- Soubor: 2026-03-29_06_create_table_product_active_leagues.sql
-- Účel: whitelist lig pro Ticket Studio / produktovou vrstvu
-- =========================================================

CREATE TABLE IF NOT EXISTS public.product_active_leagues (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    league_id integer NOT NULL,
    season text NOT NULL,

    is_active boolean NOT NULL DEFAULT true,

    -- zdroj (Football_Data, theOdds, api_football...)
    source text,

    -- např. "ticket_studio", "ml_model", "frontend"
    usage text DEFAULT 'ticket_studio',

    priority integer DEFAULT 100,

    note text,

    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),

    CONSTRAINT fk_product_active_leagues_league
        FOREIGN KEY (league_id) REFERENCES public.leagues(id),

    CONSTRAINT uq_product_active_leagues
        UNIQUE (league_id, season, usage)
);

-- indexy
CREATE INDEX IF NOT EXISTS ix_product_active_leagues_active
    ON public.product_active_leagues (is_active);

CREATE INDEX IF NOT EXISTS ix_product_active_leagues_usage
    ON public.product_active_leagues (usage);

CREATE INDEX IF NOT EXISTS ix_product_active_leagues_league_season
    ON public.product_active_leagues (league_id, season);