-- 741_insert_sport_completion_audit_ck_core.sql

INSERT INTO ops.sport_completion_audit (
    sport_code,
    entity,
    layer_type,
    current_status,
    production_readiness,
    provider_primary,
    provider_fallback,
    db_layer_ready,
    planner_ready,
    queue_ready,
    public_ready,
    key_gap,
    next_step,
    evidence_note,
    priority_rank,
    created_at,
    updated_at
)
VALUES
(
    'CK',
    'fixtures',
    'core',
    'PARTIAL',
    'NEAR_READY',
    'api_cricket',
    NULL,
    true,
    false,
    false,
    false,
    'Chybi public merge a provider/public map navazani',
    'Navrhnout a otestovat CK public merge pro fixtures',
    'CK fixtures raw+staging confirmed | stg_provider_fixtures=44',
    100,
    now(),
    now()
),
(
    'CK',
    'leagues',
    'core',
    'PARTIAL',
    'NEAR_READY',
    'api_cricket',
    NULL,
    true,
    false,
    false,
    false,
    'Chybi public merge a canonical/public league sync',
    'Navrhnout a otestovat CK public merge pro leagues',
    'CK leagues raw+staging confirmed | stg_provider_leagues=32',
    101,
    now(),
    now()
),
(
    'CK',
    'teams',
    'core',
    'PARTIAL',
    'NEAR_READY',
    'api_cricket',
    NULL,
    true,
    false,
    false,
    false,
    'Chybi provider_map/public merge pro teams',
    'Navrhnout a otestovat CK public merge pro teams',
    'CK teams raw+staging confirmed | stg_provider_teams=37',
    102,
    now(),
    now()
);