INSERT INTO ops.runtime_entity_audit (
    provider,
    sport_code,
    entity,
    current_state,
    state_reason,
    panel_runner_exists,
    planner_target_exists,
    batch_target_exists,
    pull_confirmed,
    raw_confirmed,
    staging_confirmed,
    provider_map_confirmed,
    public_merge_confirmed,
    downstream_confirmed,
    last_run_group,
    last_run_at,
    last_check_at,
    db_evidence_summary,
    next_action,
    audit_note,
    created_at,
    updated_at
)
VALUES (
    'api_american_football',
    'AFB',
    'players',
    'CONFIRMED',
    'PEOPLE V2.1 pipeline end-to-end confirmed',
    true,
    true,
    false,
    true,
    true,
    true,
    true,
    true,
    false,
    'AFB_PEOPLE_V2',
    now(),
    now(),
    'AFB players RAW->staging->public OK (86 mapped)',
    'Rozšířit scope na více týmů/sezon',
    'Vytvořeno po V2.1 pipeline',
    now(),
    now()
);