/*
===============================================================================
MATCHMATRIX STANDARDNÍ HLAVIČKA
===============================================================================

CO:
Vytváří databázové úložiště pro dlouhodobé stavové snapshoty dokumentační
vrstvy MatchMatrix a navazující pohledy pro OPS panel.

K ČEMU:
- ukládá výsledky nástroje
  25_1_A_10_BUILD_DOCUMENTATION_STATUS_SNAPSHOT_V1.py,
- uchovává historii health stavu dokumentačního systému,
- ukládá hlavní KPI dokumentace,
- chrání před duplicitním vložením stejného snapshotu,
- poskytuje pohled na poslední snapshot,
- poskytuje KPI pohled pro budoucí OPS panel,
- nezasahuje do dokumentů, verzí ani jejich historie stavů.

KDE:
db/25_DOCUMENTATION/25_1_A_12_CREATE_DOCUMENTATION_STATUS_STORAGE_V1.sql

JAK:
Spustit celý skript v DBeaveru nad databází matchmatrix.

NÁVAZNOST:
- A10 vytváří JSON stavový snapshot.
- A12 vytváří databázové úložiště.
- A13 načte JSON snapshot do databáze.
===============================================================================
*/

BEGIN;

CREATE SCHEMA IF NOT EXISTS documentation;
CREATE SCHEMA IF NOT EXISTS ops;


/*
-------------------------------------------------------------------------------
1. HLAVNÍ TABULKA STAVOVÝCH SNAPSHOTŮ
-------------------------------------------------------------------------------
*/

CREATE TABLE IF NOT EXISTS documentation.status_snapshots
(
    status_snapshot_pk bigint
        GENERATED BY DEFAULT AS IDENTITY,

    snapshot_at timestamptz NOT NULL,

    health text NOT NULL,
    final_status text NOT NULL,

    manifest_status text NOT NULL,
    verification_status text NOT NULL,
    sync_status text NOT NULL,
    control_cycle_status text NOT NULL,

    source_git_commit text,
    source_git_branch text,
    source_git_dirty boolean NOT NULL DEFAULT false,

    documents_count integer NOT NULL DEFAULT 0,
    current_versions_count integer NOT NULL DEFAULT 0,
    sections_count integer NOT NULL DEFAULT 0,
    relations_count integer NOT NULL DEFAULT 0,
    status_history_count integer NOT NULL DEFAULT 0,
    import_runs_count integer NOT NULL DEFAULT 0,

    checks_total integer NOT NULL DEFAULT 0,
    checks_passed integer NOT NULL DEFAULT 0,

    verification_warnings integer NOT NULL DEFAULT 0,
    verification_blockers integer NOT NULL DEFAULT 0,

    in_sync_count integer NOT NULL DEFAULT 0,
    sync_actions integer NOT NULL DEFAULT 0,
    sync_blockers integer NOT NULL DEFAULT 0,

    unregistered_sources integer NOT NULL DEFAULT 0,
    database_only_documents integer NOT NULL DEFAULT 0,

    manifest_candidates integer NOT NULL DEFAULT 0,
    manifest_ready integer NOT NULL DEFAULT 0,
    manifest_blockers integer NOT NULL DEFAULT 0,
    manifest_warnings integer NOT NULL DEFAULT 0,

    control_stages integer NOT NULL DEFAULT 0,
    control_stages_successful integer NOT NULL DEFAULT 0,

    blockers jsonb NOT NULL DEFAULT '[]'::jsonb,
    warnings jsonb NOT NULL DEFAULT '[]'::jsonb,

    source_reports jsonb NOT NULL DEFAULT '{}'::jsonb,
    source_payload jsonb NOT NULL DEFAULT '{}'::jsonb,

    source_file_path text,
    snapshot_hash_sha256 text NOT NULL,

    created_at timestamptz NOT NULL DEFAULT now(),
    created_by text NOT NULL DEFAULT current_user,

    CONSTRAINT status_snapshots_pkey
        PRIMARY KEY (status_snapshot_pk),

    CONSTRAINT uq_documentation_status_snapshots_hash
        UNIQUE (snapshot_hash_sha256),

    CONSTRAINT ck_documentation_status_snapshots_health
        CHECK (
            health = ANY (
                ARRAY[
                    'READY'::text,
                    'WARNING'::text,
                    'BLOCKED'::text
                ]
            )
        ),

    CONSTRAINT ck_documentation_status_snapshots_final_status
        CHECK (
            final_status = ANY (
                ARRAY[
                    'DOCUMENTATION_STATUS_READY'::text,
                    'DOCUMENTATION_STATUS_WARNING'::text,
                    'DOCUMENTATION_STATUS_BLOCKED'::text
                ]
            )
        ),

    CONSTRAINT ck_documentation_status_snapshots_git_commit
        CHECK (
            source_git_commit IS NULL
            OR source_git_commit ~ '^[0-9a-fA-F]{7,64}$'
        ),

    CONSTRAINT ck_documentation_status_snapshots_hash
        CHECK (
            snapshot_hash_sha256 ~ '^[0-9a-f]{64}$'
        ),

    CONSTRAINT ck_documentation_status_snapshots_status_values
        CHECK (
            length(btrim(manifest_status)) > 0
            AND length(btrim(verification_status)) > 0
            AND length(btrim(sync_status)) > 0
            AND length(btrim(control_cycle_status)) > 0
        ),

    CONSTRAINT ck_documentation_status_snapshots_counts_nonnegative
        CHECK (
            documents_count >= 0
            AND current_versions_count >= 0
            AND sections_count >= 0
            AND relations_count >= 0
            AND status_history_count >= 0
            AND import_runs_count >= 0
            AND checks_total >= 0
            AND checks_passed >= 0
            AND verification_warnings >= 0
            AND verification_blockers >= 0
            AND in_sync_count >= 0
            AND sync_actions >= 0
            AND sync_blockers >= 0
            AND unregistered_sources >= 0
            AND database_only_documents >= 0
            AND manifest_candidates >= 0
            AND manifest_ready >= 0
            AND manifest_blockers >= 0
            AND manifest_warnings >= 0
            AND control_stages >= 0
            AND control_stages_successful >= 0
        ),

    CONSTRAINT ck_documentation_status_snapshots_logical_counts
        CHECK (
            current_versions_count <= documents_count
            AND in_sync_count <= documents_count
            AND checks_passed <= checks_total
            AND manifest_ready <= manifest_candidates
            AND control_stages_successful <= control_stages
        ),

    CONSTRAINT ck_documentation_status_snapshots_json_types
        CHECK (
            jsonb_typeof(blockers) = 'array'
            AND jsonb_typeof(warnings) = 'array'
            AND jsonb_typeof(source_reports) = 'object'
            AND jsonb_typeof(source_payload) = 'object'
        )
);


/*
-------------------------------------------------------------------------------
2. KOMENTÁŘE
-------------------------------------------------------------------------------
*/

COMMENT ON TABLE documentation.status_snapshots IS
'Historické stavové snapshoty celé dokumentační vrstvy MatchMatrix. '
'Nejedná se o historii stavů jednotlivých dokumentů.';

COMMENT ON COLUMN documentation.status_snapshots.snapshot_at IS
'Čas vytvoření zdrojového status snapshotu nástrojem A10.';

COMMENT ON COLUMN documentation.status_snapshots.health IS
'Celkový health stav dokumentační vrstvy: READY, WARNING nebo BLOCKED.';

COMMENT ON COLUMN documentation.status_snapshots.final_status IS
'Finální technický stav zdrojového snapshotu.';

COMMENT ON COLUMN documentation.status_snapshots.snapshot_hash_sha256 IS
'SHA-256 celého zdrojového JSON souboru; slouží jako idempotentní identifikátor.';

COMMENT ON COLUMN documentation.status_snapshots.source_payload IS
'Úplný zdrojový JSON snapshot pro audit, dohledatelnost a budoucí rozšíření.';


/*
-------------------------------------------------------------------------------
3. INDEXY
-------------------------------------------------------------------------------
*/

CREATE INDEX IF NOT EXISTS
    idx_documentation_status_snapshots_time
ON documentation.status_snapshots
    (snapshot_at DESC, status_snapshot_pk DESC);


CREATE INDEX IF NOT EXISTS
    idx_documentation_status_snapshots_health
ON documentation.status_snapshots
    (health, snapshot_at DESC);


CREATE INDEX IF NOT EXISTS
    idx_documentation_status_snapshots_final_status
ON documentation.status_snapshots
    (final_status, snapshot_at DESC);


CREATE INDEX IF NOT EXISTS
    idx_documentation_status_snapshots_git_commit
ON documentation.status_snapshots
    (source_git_commit);


CREATE INDEX IF NOT EXISTS
    idx_documentation_status_snapshots_payload_gin
ON documentation.status_snapshots
USING gin
    (source_payload);


/*
-------------------------------------------------------------------------------
4. POSLEDNÍ STAVOVÝ SNAPSHOT
-------------------------------------------------------------------------------
*/

CREATE OR REPLACE VIEW documentation.v_latest_status_snapshot_v1 AS
SELECT
    s.status_snapshot_pk,
    s.snapshot_at,
    s.health,
    s.final_status,

    s.manifest_status,
    s.verification_status,
    s.sync_status,
    s.control_cycle_status,

    s.source_git_commit,
    s.source_git_branch,
    s.source_git_dirty,

    s.documents_count,
    s.current_versions_count,
    s.sections_count,
    s.relations_count,
    s.status_history_count,
    s.import_runs_count,

    s.checks_total,
    s.checks_passed,

    s.verification_warnings,
    s.verification_blockers,

    s.in_sync_count,
    s.sync_actions,
    s.sync_blockers,

    s.unregistered_sources,
    s.database_only_documents,

    s.manifest_candidates,
    s.manifest_ready,
    s.manifest_blockers,
    s.manifest_warnings,

    s.control_stages,
    s.control_stages_successful,

    jsonb_array_length(s.blockers) AS blockers_count,
    jsonb_array_length(s.warnings) AS warnings_count,

    s.source_file_path,
    s.snapshot_hash_sha256,
    s.created_at,
    s.created_by
FROM documentation.status_snapshots AS s
ORDER BY
    s.snapshot_at DESC,
    s.status_snapshot_pk DESC
LIMIT 1;


COMMENT ON VIEW documentation.v_latest_status_snapshot_v1 IS
'Poslední uložený stavový snapshot dokumentační vrstvy MatchMatrix.';


/*
-------------------------------------------------------------------------------
5. OPS KPI POHLED
-------------------------------------------------------------------------------
*/

CREATE OR REPLACE VIEW ops.v_documentation_status_kpi_v1 AS
SELECT
    s.snapshot_at,
    s.health AS documentation_health,
    s.final_status,

    s.documents_count,
    s.current_versions_count,
    s.sections_count,
    s.relations_count,

    s.checks_passed,
    s.checks_total,

    CASE
        WHEN s.checks_total = 0 THEN 0::numeric
        ELSE round(
            s.checks_passed::numeric
            * 100::numeric
            / s.checks_total::numeric,
            2
        )
    END AS checks_success_percent,

    s.in_sync_count,

    CASE
        WHEN s.documents_count = 0 THEN 0::numeric
        ELSE round(
            s.in_sync_count::numeric
            * 100::numeric
            / s.documents_count::numeric,
            2
        )
    END AS synchronization_percent,

    s.sync_actions,
    s.sync_blockers,
    s.verification_warnings,
    s.verification_blockers,

    s.unregistered_sources,
    s.database_only_documents,

    s.blockers_count,
    s.warnings_count,

    s.source_git_commit,
    s.source_git_branch,
    s.source_git_dirty,

    CASE
        WHEN s.health = 'READY'
         AND s.sync_blockers = 0
         AND s.verification_blockers = 0
        THEN 'GOOD'

        WHEN s.health = 'WARNING'
          OR s.sync_actions > 0
          OR s.verification_warnings > 0
        THEN 'WARNING'

        ELSE 'CRITICAL'
    END AS kpi_status
FROM documentation.v_latest_status_snapshot_v1 AS s;


COMMENT ON VIEW ops.v_documentation_status_kpi_v1 IS
'KPI posledního stavu dokumentační vrstvy pro MatchMatrix OPS panel.';

/*
-------------------------------------------------------------------------------
6. OPS HISTORICKÝ POHLED
-------------------------------------------------------------------------------
*/

CREATE OR REPLACE VIEW ops.v_documentation_status_history_v1 AS
SELECT
    s.status_snapshot_pk,
    s.snapshot_at,
    s.health,
    s.final_status,

    s.documents_count,
    s.current_versions_count,
    s.sections_count,
    s.relations_count,

    s.checks_total,
    s.checks_passed,

    CASE
        WHEN s.checks_total = 0 THEN 0::numeric
        ELSE round(
            s.checks_passed::numeric
            * 100::numeric
            / s.checks_total::numeric,
            2
        )
    END AS checks_success_percent,

    s.in_sync_count,
    s.sync_actions,
    s.sync_blockers,

    s.verification_warnings,
    s.verification_blockers,

    jsonb_array_length(s.blockers) AS blockers_count,
    jsonb_array_length(s.warnings) AS warnings_count,

    s.source_git_commit,
    s.source_git_dirty,
    s.created_at
FROM documentation.status_snapshots AS s;


COMMENT ON VIEW ops.v_documentation_status_history_v1 IS
'Historický vývoj health stavu a KPI dokumentační vrstvy MatchMatrix.';


COMMIT;


/*
===============================================================================
7. OVĚŘENÍ
===============================================================================
*/

SELECT
    table_schema,
    table_name
FROM information_schema.tables
WHERE table_schema = 'documentation'
  AND table_name = 'status_snapshots';


SELECT
    table_schema,
    table_name
FROM information_schema.views
WHERE (
        table_schema = 'documentation'
        AND table_name = 'v_latest_status_snapshot_v1'
      )
   OR (
        table_schema = 'ops'
        AND table_name IN (
            'v_documentation_status_kpi_v1',
            'v_documentation_status_history_v1'
        )
      )
ORDER BY
    table_schema,
    table_name;


SELECT
    COUNT(*) AS stored_snapshots
FROM documentation.status_snapshots;


SELECT
    'DOCUMENTATION_STATUS_STORAGE_READY' AS final_status;