/*
===============================================================================
MATCHMATRIX
SOUBOR: 25_1_A_1_CREATE_DOCUMENTATION_CORE_V1.sql
SEKCE: 25 – DOCUMENTATION MANAGEMENT SYSTEM
VERZE: V1
DATUM: 2026-06-30

CO:
Vytváří základní databázovou vrstvu Documentation Management System (DMS)
projektu MatchMatrix.

K ČEMU:
- evidence dokumentů podle neměnného Document ID,
- ukládání verzí a úplného Markdown obsahu,
- evidence zdrojového souboru a Git commitu,
- kontrola aktuální verze dokumentu,
- evidence kapitol a sekcí,
- evidence vazeb mezi dokumenty,
- historie změn stavů,
- audit importních běhů.

KDE:
C:\MatchMatrix-platform\db\25_DOCUMENTATION\
25_1_A_1_CREATE_DOCUMENTATION_CORE_V1.sql

JAK:
Spustit celý skript nad databází `matchmatrix` v DBeaveru.

BEZPEČNOST:
- skript nemaže žádná existující data,
- používá samostatné schéma `documentation`,
- objekty jsou vytvářeny pomocí IF NOT EXISTS,
- Markdown soubory v Git repozitáři zůstávají editovatelným zdrojem,
- databáze bude řídit identitu, verze, vazby, obsah a audit.

ARCHITEKTONICKÝ PRINCIP V1:
Git / Markdown = editovatelný zdroj
PostgreSQL     = řízený registr dokumentace a znalostí
===============================================================================
*/

BEGIN;

-- ============================================================================
-- 1. SCHÉMA
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS documentation;

COMMENT ON SCHEMA documentation IS
'Řízená databázová vrstva dokumentace a znalostí projektu MatchMatrix.';

-- ============================================================================
-- 2. IMPORTNÍ BĚHY
-- ============================================================================

CREATE TABLE IF NOT EXISTS documentation.import_runs (
    import_run_pk          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at             timestamptz NOT NULL DEFAULT now(),
    finished_at            timestamptz,
    import_status          text NOT NULL DEFAULT 'RUNNING',
    import_mode            text NOT NULL DEFAULT 'FULL_SCAN',
    source_root            text,
    git_repository         text,
    git_branch             text,
    git_commit             text,
    files_scanned          integer NOT NULL DEFAULT 0,
    files_imported         integer NOT NULL DEFAULT 0,
    files_updated          integer NOT NULL DEFAULT 0,
    files_skipped          integer NOT NULL DEFAULT 0,
    files_failed           integer NOT NULL DEFAULT 0,
    executed_by            text NOT NULL DEFAULT current_user,
    notes                  text,
    details                jsonb NOT NULL DEFAULT '{}'::jsonb,

    CONSTRAINT ck_documentation_import_runs_status
        CHECK (
            import_status IN (
                'RUNNING',
                'DONE',
                'DONE_WITH_WARNINGS',
                'FAILED',
                'CANCELLED'
            )
        ),

    CONSTRAINT ck_documentation_import_runs_mode
        CHECK (
            import_mode IN (
                'FULL_SCAN',
                'INCREMENTAL',
                'SINGLE_FILE',
                'MANUAL'
            )
        ),

    CONSTRAINT ck_documentation_import_runs_counts
        CHECK (
            files_scanned >= 0
            AND files_imported >= 0
            AND files_updated >= 0
            AND files_skipped >= 0
            AND files_failed >= 0
        ),

    CONSTRAINT ck_documentation_import_runs_details_object
        CHECK (jsonb_typeof(details) = 'object'),

    CONSTRAINT ck_documentation_import_runs_git_commit
        CHECK (
            git_commit IS NULL
            OR git_commit ~ '^[0-9a-fA-F]{7,64}$'
        )
);

COMMENT ON TABLE documentation.import_runs IS
'Auditní evidence každého importu dokumentace z Git repozitáře do databáze.';

COMMENT ON COLUMN documentation.import_runs.import_mode IS
'FULL_SCAN, INCREMENTAL, SINGLE_FILE nebo MANUAL.';

COMMENT ON COLUMN documentation.import_runs.details IS
'Rozšiřující strukturované údaje importu ve formátu JSON.';

-- ============================================================================
-- 3. HLAVNÍ REGISTR DOKUMENTŮ
-- ============================================================================

CREATE TABLE IF NOT EXISTS documentation.documents (
    document_pk            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id            text NOT NULL,
    document_type          text NOT NULL,
    title                  text NOT NULL,
    edition                text,
    language_code          text NOT NULL DEFAULT 'cs',
    current_version_label  text,
    current_status         text NOT NULL DEFAULT 'DRAFT',
    category               text,
    owner_name             text,
    technical_partner      text,
    canonical_filename     text,
    repo_relative_path     text,
    source_of_truth        text NOT NULL DEFAULT 'HYBRID',
    is_active              boolean NOT NULL DEFAULT true,
    metadata               jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at             timestamptz NOT NULL DEFAULT now(),
    updated_at             timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_documentation_documents_document_id
        UNIQUE (document_id),

    CONSTRAINT uq_documentation_documents_repo_path
        UNIQUE (repo_relative_path),

    CONSTRAINT ck_documentation_documents_id
        CHECK (
            document_id ~ '^MM-[A-Z]{2,10}-[0-9]{3,4}[A-Z]?$'
        ),

    CONSTRAINT ck_documentation_documents_type
        CHECK (
            document_type IN (
                'DOC',
                'STD',
                'REF',
                'BOOK',
                'MST',
                'GOV',
                'ARC',
                'DB',
                'PRV',
                'LAY',
                'OPS',
                'DEV',
                'HIS',
                'VIS',
                'TPL',
                'EXP',
                'DRF',
                'ARCV',
                'OTHER'
            )
        ),

    CONSTRAINT ck_documentation_documents_language
        CHECK (
            language_code ~ '^[a-z]{2}(-[A-Z]{2})?$'
        ),

    CONSTRAINT ck_documentation_documents_status
        CHECK (
            current_status IN (
                'DRAFT',
                'IN_PROGRESS',
                'REVIEW',
                'APPROVED',
                'ACTIVE',
                'DEPRECATED',
                'ARCHIVED',
                'CANCELLED'
            )
        ),

    CONSTRAINT ck_documentation_documents_source_of_truth
        CHECK (
            source_of_truth IN (
                'FILE',
                'DATABASE',
                'HYBRID'
            )
        ),

    CONSTRAINT ck_documentation_documents_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object')
);

COMMENT ON TABLE documentation.documents IS
'Centrální registr dokumentů MatchMatrix. Jeden řádek představuje jedno neměnné Document ID.';

COMMENT ON COLUMN documentation.documents.document_id IS
'Neměnný identifikátor dokumentu, například MM-DOC-300.';

COMMENT ON COLUMN documentation.documents.current_version_label IS
'Označení aktuální verze dokumentu, například 1.0 nebo 1.1.';

COMMENT ON COLUMN documentation.documents.current_status IS
'Aktuální stav dokumentu v jeho životním cyklu.';

COMMENT ON COLUMN documentation.documents.repo_relative_path IS
'Relativní cesta souboru vůči kořeni Git repozitáře.';

COMMENT ON COLUMN documentation.documents.source_of_truth IS
'FILE, DATABASE nebo HYBRID. V první etapě se používá HYBRID.';

-- ============================================================================
-- 4. VERZE DOKUMENTŮ
-- ============================================================================

CREATE TABLE IF NOT EXISTS documentation.document_versions (
    version_pk             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_pk            bigint NOT NULL,
    import_run_pk          bigint,
    version_label          text NOT NULL,
    version_status         text NOT NULL DEFAULT 'REVIEW',
    content_markdown       text NOT NULL,
    content_hash_sha256    text NOT NULL,
    source_filename        text NOT NULL,
    source_file_path       text NOT NULL,
    source_git_commit      text,
    source_modified_at     timestamptz,
    change_summary         text,
    is_current             boolean NOT NULL DEFAULT false,
    imported_at            timestamptz NOT NULL DEFAULT now(),
    imported_by            text NOT NULL DEFAULT current_user,
    metadata               jsonb NOT NULL DEFAULT '{}'::jsonb,

    CONSTRAINT fk_documentation_versions_document
        FOREIGN KEY (document_pk)
        REFERENCES documentation.documents (document_pk)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_documentation_versions_import_run
        FOREIGN KEY (import_run_pk)
        REFERENCES documentation.import_runs (import_run_pk)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT uq_documentation_versions_document_hash
        UNIQUE (document_pk, content_hash_sha256),

    CONSTRAINT ck_documentation_versions_status
        CHECK (
            version_status IN (
                'DRAFT',
                'IN_PROGRESS',
                'REVIEW',
                'APPROVED',
                'ACTIVE',
                'DEPRECATED',
                'ARCHIVED',
                'CANCELLED'
            )
        ),

    CONSTRAINT ck_documentation_versions_hash
        CHECK (
            content_hash_sha256 ~ '^[0-9a-f]{64}$'
        ),

    CONSTRAINT ck_documentation_versions_git_commit
        CHECK (
            source_git_commit IS NULL
            OR source_git_commit ~ '^[0-9a-fA-F]{7,64}$'
        ),

    CONSTRAINT ck_documentation_versions_content_not_empty
        CHECK (length(btrim(content_markdown)) > 0),

    CONSTRAINT ck_documentation_versions_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object')
);

COMMENT ON TABLE documentation.document_versions IS
'Úplná historie verzí a Markdown obsahu jednotlivých dokumentů.';

COMMENT ON COLUMN documentation.document_versions.content_hash_sha256 IS
'SHA-256 hash obsahu používaný pro detekci změn a duplicitních importů.';

COMMENT ON COLUMN documentation.document_versions.is_current IS
'Označuje aktuální platnou databázovou verzi daného dokumentu.';

CREATE UNIQUE INDEX IF NOT EXISTS
    uq_documentation_versions_one_current
ON documentation.document_versions (document_pk)
WHERE is_current = true;

CREATE INDEX IF NOT EXISTS
    idx_documentation_versions_document
ON documentation.document_versions (
    document_pk,
    imported_at DESC
);

CREATE INDEX IF NOT EXISTS
    idx_documentation_versions_import_run
ON documentation.document_versions (import_run_pk);

CREATE INDEX IF NOT EXISTS
    idx_documentation_versions_status
ON documentation.document_versions (
    version_status,
    is_current
);

CREATE INDEX IF NOT EXISTS
    idx_documentation_versions_hash
ON documentation.document_versions (content_hash_sha256);

-- ============================================================================
-- 5. KAPITOLY A SEKCE
-- ============================================================================

CREATE TABLE IF NOT EXISTS documentation.document_sections (
    section_pk             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_pk             bigint NOT NULL,
    parent_section_pk      bigint,
    section_key            text,
    section_order          integer NOT NULL,
    heading_level          smallint NOT NULL,
    title                  text NOT NULL,
    anchor_name            text,
    content_markdown       text,
    content_hash_sha256    text,
    metadata               jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at             timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_documentation_sections_version
        FOREIGN KEY (version_pk)
        REFERENCES documentation.document_versions (version_pk)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_documentation_sections_parent
        FOREIGN KEY (parent_section_pk)
        REFERENCES documentation.document_sections (section_pk)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT uq_documentation_sections_order
        UNIQUE (version_pk, section_order),

    CONSTRAINT ck_documentation_sections_order
        CHECK (section_order > 0),

    CONSTRAINT ck_documentation_sections_heading_level
        CHECK (heading_level BETWEEN 1 AND 6),

    CONSTRAINT ck_documentation_sections_hash
        CHECK (
            content_hash_sha256 IS NULL
            OR content_hash_sha256 ~ '^[0-9a-f]{64}$'
        ),

    CONSTRAINT ck_documentation_sections_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object')
);

COMMENT ON TABLE documentation.document_sections IS
'Strukturované kapitoly a podkapitoly konkrétní verze dokumentu.';

CREATE INDEX IF NOT EXISTS
    idx_documentation_sections_version
ON documentation.document_sections (
    version_pk,
    section_order
);

CREATE INDEX IF NOT EXISTS
    idx_documentation_sections_parent
ON documentation.document_sections (parent_section_pk);

CREATE INDEX IF NOT EXISTS
    idx_documentation_sections_key
ON documentation.document_sections (section_key);

-- ============================================================================
-- 6. VAZBY MEZI DOKUMENTY
-- ============================================================================

CREATE TABLE IF NOT EXISTS documentation.document_relations (
    relation_pk            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_document_pk     bigint NOT NULL,
    target_document_pk     bigint NOT NULL,
    relation_type          text NOT NULL,
    source_section_key     text,
    target_section_key     text,
    relation_note          text,
    is_active              boolean NOT NULL DEFAULT true,
    valid_from             timestamptz NOT NULL DEFAULT now(),
    valid_to               timestamptz,
    metadata               jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at             timestamptz NOT NULL DEFAULT now(),
    created_by             text NOT NULL DEFAULT current_user,

    CONSTRAINT fk_documentation_relations_source
        FOREIGN KEY (source_document_pk)
        REFERENCES documentation.documents (document_pk)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_documentation_relations_target
        FOREIGN KEY (target_document_pk)
        REFERENCES documentation.documents (document_pk)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT uq_documentation_relations_identity
        UNIQUE (
            source_document_pk,
            target_document_pk,
            relation_type,
            source_section_key,
            target_section_key
        ),

    CONSTRAINT ck_documentation_relations_not_self
        CHECK (
            source_document_pk <> target_document_pk
        ),

    CONSTRAINT ck_documentation_relations_type
        CHECK (
            relation_type IN (
                'REFERENCES',
                'RELATED_TO',
                'GOVERNED_BY',
                'IMPLEMENTS',
                'DESCRIBES',
                'DERIVED_FROM',
                'SUPERSEDES',
                'SUPERSEDED_BY',
                'NEXT_DOCUMENT',
                'PREVIOUS_DOCUMENT',
                'PARENT_OF',
                'CHILD_OF',
                'SOURCE_FOR'
            )
        ),

    CONSTRAINT ck_documentation_relations_validity
        CHECK (
            valid_to IS NULL
            OR valid_to >= valid_from
        ),

    CONSTRAINT ck_documentation_relations_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object')
);

COMMENT ON TABLE documentation.document_relations IS
'Řízené vazby mezi dokumenty, standardy, referencemi a souvisejícími oblastmi.';

CREATE INDEX IF NOT EXISTS
    idx_documentation_relations_source
ON documentation.document_relations (
    source_document_pk,
    relation_type,
    is_active
);

CREATE INDEX IF NOT EXISTS
    idx_documentation_relations_target
ON documentation.document_relations (
    target_document_pk,
    relation_type,
    is_active
);

-- ============================================================================
-- 7. HISTORIE STAVŮ DOKUMENTŮ
-- ============================================================================

CREATE TABLE IF NOT EXISTS documentation.document_status_history (
    status_history_pk      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_pk            bigint NOT NULL,
    version_pk             bigint,
    previous_status        text,
    new_status             text NOT NULL,
    change_reason          text,
    changed_at             timestamptz NOT NULL DEFAULT now(),
    changed_by             text NOT NULL DEFAULT current_user,
    metadata               jsonb NOT NULL DEFAULT '{}'::jsonb,

    CONSTRAINT fk_documentation_status_document
        FOREIGN KEY (document_pk)
        REFERENCES documentation.documents (document_pk)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_documentation_status_version
        FOREIGN KEY (version_pk)
        REFERENCES documentation.document_versions (version_pk)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT ck_documentation_status_previous
        CHECK (
            previous_status IS NULL
            OR previous_status IN (
                'DRAFT',
                'IN_PROGRESS',
                'REVIEW',
                'APPROVED',
                'ACTIVE',
                'DEPRECATED',
                'ARCHIVED',
                'CANCELLED'
            )
        ),

    CONSTRAINT ck_documentation_status_new
        CHECK (
            new_status IN (
                'DRAFT',
                'IN_PROGRESS',
                'REVIEW',
                'APPROVED',
                'ACTIVE',
                'DEPRECATED',
                'ARCHIVED',
                'CANCELLED'
            )
        ),

    CONSTRAINT ck_documentation_status_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object')
);

COMMENT ON TABLE documentation.document_status_history IS
'Auditní historie změn stavů dokumentů.';

CREATE INDEX IF NOT EXISTS
    idx_documentation_status_history_document
ON documentation.document_status_history (
    document_pk,
    changed_at DESC
);

-- ============================================================================
-- 8. FUNKCE PRO UPDATED_AT
-- ============================================================================

CREATE OR REPLACE FUNCTION documentation.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at := clock_timestamp();
    RETURN NEW;
END;
$function$;

COMMENT ON FUNCTION documentation.set_updated_at() IS
'Nastavuje updated_at při každé změně řádku dokumentu.';

DO $do$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'trg_documentation_documents_updated_at'
          AND tgrelid = 'documentation.documents'::regclass
    ) THEN
        CREATE TRIGGER trg_documentation_documents_updated_at
        BEFORE UPDATE
        ON documentation.documents
        FOR EACH ROW
        EXECUTE FUNCTION documentation.set_updated_at();
    END IF;
END;
$do$;

-- ============================================================================
-- 9. POHLED AKTUÁLNÍHO REGISTRU
-- ============================================================================

CREATE OR REPLACE VIEW documentation.v_document_registry_v1 AS
SELECT
    d.document_pk,
    d.document_id,
    d.document_type,
    d.title,
    d.edition,
    d.language_code,
    d.current_version_label,
    d.current_status,
    d.category,
    d.owner_name,
    d.canonical_filename,
    d.repo_relative_path,
    d.source_of_truth,
    d.is_active,
    v.version_pk AS current_version_pk,
    v.version_label AS stored_version_label,
    v.version_status AS stored_version_status,
    v.content_hash_sha256,
    v.source_filename,
    v.source_file_path,
    v.source_git_commit,
    v.source_modified_at,
    v.imported_at,
    d.created_at,
    d.updated_at
FROM documentation.documents d
LEFT JOIN documentation.document_versions v
  ON v.document_pk = d.document_pk
 AND v.is_current = true;

COMMENT ON VIEW documentation.v_document_registry_v1 IS
'Jednotný registr dokumentů včetně aktuální importované verze.';

-- ============================================================================
-- 10. POHLED KONTROLY INTEGRITY
-- ============================================================================

CREATE OR REPLACE VIEW documentation.v_document_integrity_v1 AS
WITH version_counts AS (
    SELECT
        document_pk,
        count(*) AS version_count,
        count(*) FILTER (WHERE is_current = true) AS current_version_count
    FROM documentation.document_versions
    GROUP BY document_pk
)
SELECT
    d.document_pk,
    d.document_id,
    d.title,
    d.current_status,
    d.current_version_label,
    d.repo_relative_path,
    d.is_active,
    coalesce(vc.version_count, 0) AS version_count,
    coalesce(vc.current_version_count, 0) AS current_version_count,
    CASE
        WHEN d.repo_relative_path IS NULL
            THEN 'MISSING_REPOSITORY_PATH'
        WHEN d.canonical_filename IS NULL
            THEN 'MISSING_CANONICAL_FILENAME'
        WHEN d.is_active
             AND coalesce(vc.version_count, 0) = 0
            THEN 'MISSING_VERSION'
        WHEN d.is_active
             AND coalesce(vc.current_version_count, 0) = 0
            THEN 'MISSING_CURRENT_VERSION'
        WHEN coalesce(vc.current_version_count, 0) > 1
            THEN 'MULTIPLE_CURRENT_VERSIONS'
        ELSE 'OK'
    END AS integrity_status
FROM documentation.documents d
LEFT JOIN version_counts vc
  ON vc.document_pk = d.document_pk;

COMMENT ON VIEW documentation.v_document_integrity_v1 IS
'Kontrolní pohled ověřující základní úplnost a konzistenci registru dokumentů.';

-- ============================================================================
-- 11. DALŠÍ INDEXY REGISTRU
-- ============================================================================

CREATE INDEX IF NOT EXISTS
    idx_documentation_documents_status
ON documentation.documents (
    current_status,
    is_active
);

CREATE INDEX IF NOT EXISTS
    idx_documentation_documents_type
ON documentation.documents (
    document_type,
    is_active
);

CREATE INDEX IF NOT EXISTS
    idx_documentation_documents_title
ON documentation.documents (title);

CREATE INDEX IF NOT EXISTS
    idx_documentation_documents_metadata_gin
ON documentation.documents
USING gin (metadata);

CREATE INDEX IF NOT EXISTS
    idx_documentation_versions_metadata_gin
ON documentation.document_versions
USING gin (metadata);

-- ============================================================================
-- 12. VERIFIKACE PŘED COMMIT
-- ============================================================================

DO $do$
DECLARE
    v_table_count integer;
    v_view_count  integer;
BEGIN
    SELECT count(*)
    INTO v_table_count
    FROM information_schema.tables
    WHERE table_schema = 'documentation'
      AND table_type = 'BASE TABLE';

    SELECT count(*)
    INTO v_view_count
    FROM information_schema.views
    WHERE table_schema = 'documentation';

    IF v_table_count < 6 THEN
        RAISE EXCEPTION
            'Documentation schema verification failed. Expected at least 6 tables, found %.',
            v_table_count;
    END IF;

    IF v_view_count < 2 THEN
        RAISE EXCEPTION
            'Documentation schema verification failed. Expected at least 2 views, found %.',
            v_view_count;
    END IF;
END;
$do$;

COMMIT;

-- ============================================================================
-- 13. VÝSTUP PO ÚSPĚŠNÉM VYTVOŘENÍ
-- ============================================================================

SELECT
    current_database() AS database_name,
    'documentation' AS schema_name,
    count(*) FILTER (
        WHERE object_type = 'TABLE'
    ) AS tables_created,
    count(*) FILTER (
        WHERE object_type = 'VIEW'
    ) AS views_created,
    'DOCUMENTATION_CORE_CREATED' AS final_status
FROM (
    SELECT
        table_name AS object_name,
        'TABLE'::text AS object_type
    FROM information_schema.tables
    WHERE table_schema = 'documentation'
      AND table_type = 'BASE TABLE'

    UNION ALL

    SELECT
        table_name AS object_name,
        'VIEW'::text AS object_type
    FROM information_schema.views
    WHERE table_schema = 'documentation'
) objects;

SELECT
    table_schema,
    table_name,
    table_type
FROM information_schema.tables
WHERE table_schema = 'documentation'
ORDER BY
    table_type,
    table_name;

SELECT
    document_id,
    title,
    integrity_status
FROM documentation.v_document_integrity_v1
ORDER BY document_id;