-- ============================================================================
-- MATCHMATRIX
-- DATA ACQUISITION SOURCE ROUTING V1
-- ============================================================================
--
-- CO:
--   Vytvoření řízené routingové tabulky pro Data Acquisition Blueprint.
--
-- K ČEMU:
--   Ukládá explicitní rozhodnutí:
--
--       SPORT
--       × LAYER
--       × ENTITY
--       × TIME_MODE
--       × SOURCE
--       × ROLE
--
--   Tabulka NEUKLÁDÁ výsledky auditů.
--   Auditní evidence zůstává v existujících auditních tabulkách a views.
--
-- KDE:
--   ops.data_acquisition_source_routing
--
-- JAK:
--   Každý řádek představuje jednu routingovou volbu zdroje.
--
--   SOURCE_ROLE:
--       PRIMARY
--       FALLBACK
--       MERGE
--       REFERENCE
--
--   SOURCE_ORIGIN:
--       PROVIDER_ENTITY_COVERAGE
--       GLOBAL_SOURCE_REGISTRY
--
--   DECISION_STATUS:
--       PROPOSED
--       APPROVED
--       REJECTED
--       RETIRED
--
-- DŮLEŽITÉ:
--   Pro jednu kombinaci SPORT × LAYER × ENTITY × TIME_MODE
--   může existovat pouze jeden aktivní APPROVED PRIMARY.
--
-- MODE:
--   APPLY
-- ============================================================================


BEGIN;


CREATE TABLE ops.data_acquisition_source_routing
(
    route_id bigint
        GENERATED BY DEFAULT AS IDENTITY,

    sport_code text
        NOT NULL,

    layer_type text
        NOT NULL,

    entity text
        NOT NULL,

    time_mode text
        NOT NULL,

    source_role text
        NOT NULL,

    source_name text
        NOT NULL,

    source_origin text
        NOT NULL,

    source_ref_id bigint
        NOT NULL,

    route_priority integer
        NOT NULL
        DEFAULT 100,

    decision_status text
        NOT NULL
        DEFAULT 'PROPOSED',

    decision_note text,

    approved_by text,

    approved_at timestamp with time zone,

    is_active boolean
        NOT NULL
        DEFAULT true,

    created_at timestamp with time zone
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at timestamp with time zone
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,


    CONSTRAINT pk_data_acquisition_source_routing
        PRIMARY KEY (route_id),


    CONSTRAINT ck_data_acq_source_routing_layer
        CHECK (
            layer_type IN (
                'CORE',
                'PEOPLE',
                'MATCH_DETAIL',
                'ODDS',
                'MEDIA_FAN'
            )
        ),


    CONSTRAINT ck_data_acq_source_routing_time_mode
        CHECK (
            time_mode IN (
                'HISTORY_FAN',
                'HISTORY_PREDICTION',
                'CURRENT',
                'FUTURE',
                'LIVE'
            )
        ),


    CONSTRAINT ck_data_acq_source_routing_source_role
        CHECK (
            source_role IN (
                'PRIMARY',
                'FALLBACK',
                'MERGE',
                'REFERENCE'
            )
        ),


    CONSTRAINT ck_data_acq_source_routing_source_origin
        CHECK (
            source_origin IN (
                'PROVIDER_ENTITY_COVERAGE',
                'GLOBAL_SOURCE_REGISTRY'
            )
        ),


    CONSTRAINT ck_data_acq_source_routing_decision_status
        CHECK (
            decision_status IN (
                'PROPOSED',
                'APPROVED',
                'REJECTED',
                'RETIRED'
            )
        ),


    CONSTRAINT ck_data_acq_source_routing_priority
        CHECK (
            route_priority >= 1
        ),


    CONSTRAINT ck_data_acq_source_routing_required_text
        CHECK (
               btrim(sport_code) <> ''
           AND btrim(layer_type) <> ''
           AND btrim(entity) <> ''
           AND btrim(source_role) <> ''
           AND btrim(source_name) <> ''
           AND btrim(source_origin) <> ''
        ),


    CONSTRAINT ck_data_acq_source_routing_approval
        CHECK (
            decision_status <> 'APPROVED'
            OR (
                   approved_at IS NOT NULL
               AND approved_by IS NOT NULL
               AND btrim(approved_by) <> ''
               AND decision_note IS NOT NULL
               AND btrim(decision_note) <> ''
            )
        )
);


-- ============================================================================
-- Jeden stejný aktivní zdroj nesmí být pro stejnou scope/roli vložen dvakrát.
-- ============================================================================

CREATE UNIQUE INDEX
    uq_data_acq_source_routing_active_source
ON ops.data_acquisition_source_routing
(
    sport_code,
    layer_type,
    entity,
    time_mode,
    source_role,
    source_origin,
    source_name
)
WHERE is_active = true;


-- ============================================================================
-- HARD GATE:
-- Pro SPORT × LAYER × ENTITY × TIME_MODE smí být pouze
-- jeden aktivní APPROVED PRIMARY.
--
-- Více PROPOSED kandidátů je dovoleno.
-- ============================================================================
CREATE UNIQUE INDEX
    uq_data_acq_source_routing_one_approved_primary
ON ops.data_acquisition_source_routing
(
    sport_code,
    layer_type,
    entity,
    time_mode
)
WHERE
        is_active = true
    AND source_role = 'PRIMARY'
    AND decision_status = 'APPROVED';


COMMENT ON TABLE ops.data_acquisition_source_routing IS
'Řízený source routing pro MatchMatrix Data Acquisition Blueprint. '
'Definuje zvolený PRIMARY/FALLBACK/MERGE/REFERENCE zdroj pro '
'SPORT × LAYER × ENTITY × TIME_MODE. Auditní výsledky se zde neukládají.';


COMMENT ON COLUMN ops.data_acquisition_source_routing.source_origin IS
'Objekt, ze kterého pochází identita zdroje. '
'PROVIDER_ENTITY_COVERAGE = API/provider routing; '
'GLOBAL_SOURCE_REGISTRY = externí/oficiální/referenční zdroj.';


COMMENT ON COLUMN ops.data_acquisition_source_routing.source_ref_id IS
'ID zdrojového řádku podle source_origin. '
'provider_entity_coverage.id nebo global_source_registry.source_id.';


COMMENT ON COLUMN ops.data_acquisition_source_routing.source_role IS
'Role zdroje: PRIMARY, FALLBACK, MERGE nebo REFERENCE.';


COMMENT ON COLUMN ops.data_acquisition_source_routing.decision_status IS
'Stav routingového rozhodnutí: PROPOSED, APPROVED, REJECTED nebo RETIRED.';


COMMENT ON COLUMN ops.data_acquisition_source_routing.route_priority IS
'Pořadí zdroje uvnitř dané scope/role. Nižší číslo = vyšší priorita.';


COMMIT;


-- ============================================================================
-- POSTCHECK
-- ============================================================================

SELECT
    'OBJECT' AS check_type,
    'ops.data_acquisition_source_routing' AS item,
    CASE
        WHEN to_regclass(
            'ops.data_acquisition_source_routing'
        ) IS NOT NULL
            THEN 'OK'
        ELSE 'MISSING'
    END AS result

UNION ALL

SELECT
    'COLUMNS',
    'column_count',
    COUNT(*)::text
FROM information_schema.columns
WHERE table_schema = 'ops'
  AND table_name = 'data_acquisition_source_routing'

UNION ALL

SELECT
    'ROWS',
    'current_rows',
    COUNT(*)::text
FROM ops.data_acquisition_source_routing

UNION ALL

SELECT
    'CONSTRAINT',
    conname,
    'OK'
FROM pg_constraint
WHERE conrelid =
      'ops.data_acquisition_source_routing'::regclass

UNION ALL

SELECT
    'INDEX',
    indexname,
    'OK'
FROM pg_indexes
WHERE schemaname = 'ops'
  AND tablename = 'data_acquisition_source_routing'

ORDER BY
    check_type,
    item;