/* =============================================================================
CO:
    G4D-3 / STEP 4C
    ROUTING COMPATIBILITY VALIDATE_ONLY

K ČEMU:
    Fyzicky ověří cílovou kompatibilitu:
      1. SOURCE_MASTER jako canonical identity target,
      2. source_id v existujícím routing masteru,
      3. FK source_id -> SOURCE_MASTER,
      4. FK sport_code -> public.sports(code),
      5. nullable legacy source fields,
      6. nové routing role,
      7. canonical unique index přes source_id,
      8. max. jeden aktivní PRIMARY,
      9. zachování approval ochrany.

KDE:
    PostgreSQL database matchmatrix / PC2

JAK:
    Celý skript spustit najednou v DBeaveru.

BEZPEČNOST:
    - NENÍ APPLY
    - změny vzniknou pouze uvnitř transakce
    - žádný existující routing row se nemění (routing má 0 řádků)
    - testovací data jsou syntetická a existují pouze uvnitř transakce
    - na konci POVINNĚ ROLLBACK

DŮLEŽITÉ:
    Tento krok ještě nevytváří:
      - SOURCE_ALIAS
      - SOURCE_SPORT
      - SOURCE_ENTITY_TIME_COVERAGE
      - SOURCE_AUDIT_EVIDENCE
      - RUNTIME_ADAPTER
      - SOURCE_ADAPTER_BINDING

    Neprovádí žádný skutečný routing approval.
============================================================================= */


BEGIN;


/* ============================================================================
0. SAFETY GUARDS
============================================================================ */

DO $$
DECLARE
    v_db text;
    v_rows bigint;
BEGIN
    SELECT current_database()
      INTO v_db;

    IF v_db <> 'matchmatrix' THEN
        RAISE EXCEPTION
            'BLOCKER: expected database matchmatrix, current database = %',
            v_db;
    END IF;


    SELECT COUNT(*)
      INTO v_rows
      FROM ops.data_acquisition_source_routing;

    IF v_rows <> 0 THEN
        RAISE EXCEPTION
            'BLOCKER: routing table must be empty for STEP 4C, rows = %',
            v_rows;
    END IF;


    IF to_regclass('ops.source_master') IS NOT NULL THEN
        RAISE EXCEPTION
            'BLOCKER: ops.source_master already exists before VALIDATE_ONLY';
    END IF;
END
$$;


/* ============================================================================
1. VALIDATE_ONLY SOURCE_MASTER PHYSICAL TARGET

   Toto je pouze rollback-safe fyzická implementace frozen logického kontraktu.

   source_type a lifecycle_status jsou TEXT bez domyšleného enum constraintu.
   Jejich povinnost vychází z Design Freeze, ale hodnotový slovník zde
   nevymýšlíme.
============================================================================ */

CREATE TABLE ops.source_master
(
    source_id         bigint GENERATED BY DEFAULT AS IDENTITY,
    source_code       text NOT NULL,
    canonical_name    text NOT NULL,
    source_type       text NOT NULL,
    lifecycle_status  text NOT NULL,

    canonical_domain  text NULL,
    owner_org         text NULL,
    notes             text NULL,

    created_at        timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_source_master
        PRIMARY KEY (source_id),

    CONSTRAINT uq_source_master_source_code
        UNIQUE (source_code),

    CONSTRAINT ck_source_master_required_text
        CHECK (
            btrim(source_code) <> ''
            AND btrim(canonical_name) <> ''
            AND btrim(source_type) <> ''
            AND btrim(lifecycle_status) <> ''
        )
);


/* ============================================================================
2. SYNTHETICKÁ VALIDATE_ONLY IDENTITA

   NEJDE o produkční seed.
   Je vložena pouze proto, abychom mohli fyzicky otestovat FK a canonical route.
   ROLLBACK ji odstraní.
============================================================================ */

INSERT INTO ops.source_master
(
    source_code,
    canonical_name,
    source_type,
    lifecycle_status,
    notes
)
VALUES
(
    '__g4d_validate_only__',
    'G4D VALIDATE ONLY SYNTHETIC SOURCE',
    'VALIDATE_ONLY_TEST',
    'VALIDATE_ONLY_TEST',
    'Synthetic row. Must never survive ROLLBACK.'
);


/* ============================================================================
3. ROUTING – PŘIDÁNÍ CANONICAL SOURCE_ID
============================================================================ */

ALTER TABLE ops.data_acquisition_source_routing
    ADD COLUMN source_id bigint;


/* Routing je 0 rows, takže cílový required kontrakt lze ověřit rovnou. */

ALTER TABLE ops.data_acquisition_source_routing
    ALTER COLUMN source_id SET NOT NULL;


/* ============================================================================
4. LEGACY SOURCE FIELDS – ZACHOVAT, ALE ZRUŠIT POVINNOST

   Nesmíme vytvářet fake source_name/source_origin/source_ref_id pouze proto,
   aby canonical route prošla starým schématem.
============================================================================ */

ALTER TABLE ops.data_acquisition_source_routing
    ALTER COLUMN source_name DROP NOT NULL;

ALTER TABLE ops.data_acquisition_source_routing
    ALTER COLUMN source_origin DROP NOT NULL;

ALTER TABLE ops.data_acquisition_source_routing
    ALTER COLUMN source_ref_id DROP NOT NULL;


/* ============================================================================
5. FOREIGN KEYS
============================================================================ */

ALTER TABLE ops.data_acquisition_source_routing
    ADD CONSTRAINT fk_data_acq_source_routing_source
    FOREIGN KEY (source_id)
    REFERENCES ops.source_master(source_id);


ALTER TABLE ops.data_acquisition_source_routing
    ADD CONSTRAINT fk_data_acq_source_routing_sport
    FOREIGN KEY (sport_code)
    REFERENCES public.sports(code);


/* ============================================================================
6. REQUIRED TEXT CHECK

   Starý check vyžaduje source_name/source_origin.
   Ten je v canonical modelu chybný.

   Povinný zůstává skutečný routing scope.
============================================================================ */

ALTER TABLE ops.data_acquisition_source_routing
    DROP CONSTRAINT ck_data_acq_source_routing_required_text;


ALTER TABLE ops.data_acquisition_source_routing
    ADD CONSTRAINT ck_data_acq_source_routing_required_text
    CHECK (
        btrim(sport_code) <> ''
        AND btrim(layer_type) <> ''
        AND btrim(entity) <> ''
        AND btrim(time_mode) <> ''
        AND btrim(source_role) <> ''
    );


/* ============================================================================
7. SOURCE_ORIGIN

   Sloupec zůstává pro legacy provenance.
   NULL je nyní povolen.
   Pokud ale hodnota existuje, musí stále odpovídat známému legacy původu.
============================================================================ */

ALTER TABLE ops.data_acquisition_source_routing
    DROP CONSTRAINT ck_data_acq_source_routing_source_origin;


ALTER TABLE ops.data_acquisition_source_routing
    ADD CONSTRAINT ck_data_acq_source_routing_source_origin
    CHECK (
        source_origin IS NULL
        OR source_origin = ANY (
            ARRAY[
                'PROVIDER_ENTITY_COVERAGE'::text,
                'GLOBAL_SOURCE_REGISTRY'::text
            ]
        )
    );


/* ============================================================================
8. ROUTING ROLES

   REFERENCE se automaticky nemapuje.
   Cílový kontrakt:
     PRIMARY
     FALLBACK
     MERGE
     VALIDATION
     NOT_USED
============================================================================ */

ALTER TABLE ops.data_acquisition_source_routing
    DROP CONSTRAINT ck_data_acq_source_routing_source_role;


ALTER TABLE ops.data_acquisition_source_routing
    ADD CONSTRAINT ck_data_acq_source_routing_source_role
    CHECK (
        source_role = ANY (
            ARRAY[
                'PRIMARY'::text,
                'FALLBACK'::text,
                'MERGE'::text,
                'VALIDATION'::text,
                'NOT_USED'::text
            ]
        )
    );


/* ============================================================================
9. ACTIVE SOURCE UNIQUENESS

   Legacy:
     ... source_role + source_origin + source_name

   Target:
     ... source_role + source_id
============================================================================ */

DROP INDEX ops.uq_data_acq_source_routing_active_source;


CREATE UNIQUE INDEX uq_data_acq_source_routing_active_source
ON ops.data_acquisition_source_routing
(
    sport_code,
    layer_type,
    entity,
    time_mode,
    source_role,
    source_id
)
WHERE is_active = true;


/* ============================================================================
10. MAX. JEDEN AKTIVNÍ PRIMARY

   Starý index:
     pouze APPROVED PRIMARY

   Frozen kontrakt:
     max. 1 ACTIVE PRIMARY na přesný scope.

   Proto decision_status již není součástí filtru.
============================================================================ */

DROP INDEX ops.uq_data_acq_source_routing_one_approved_primary;


CREATE UNIQUE INDEX uq_data_acq_source_routing_one_active_primary
ON ops.data_acquisition_source_routing
(
    sport_code,
    layer_type,
    entity,
    time_mode
)
WHERE
    is_active = true
    AND source_role = 'PRIMARY';


/* ============================================================================
11. APPROVAL PROTECTION

   NIC NEMĚNÍME.

   Existing constraint musí zůstat:
     APPROVED
       -> approved_at
       -> approved_by
       -> decision_note
============================================================================ */


/* ============================================================================
12. CANONICAL ROUTE INSERT TEST

   Testujeme přesně problém, který měl starý kontrakt:

   source_id je vyplněn,
   legacy source_name/source_origin/source_ref_id = NULL.

   Pokud tento INSERT projde, canonical route již nepotřebuje fake legacy data.

   VALIDATION je záměrně nová cílová role.

   Řádek bude hned smazán a nakonec stejně proběhne ROLLBACK.
============================================================================ */

INSERT INTO ops.data_acquisition_source_routing
(
    sport_code,
    layer_type,
    entity,
    time_mode,
    source_role,
    source_id,
    route_priority,
    decision_status,
    decision_note,
    approved_by,
    approved_at,
    is_active
)
SELECT
    'HB',
    'CORE',
    '__G4D_VALIDATE_ONLY__',
    'CURRENT',
    'VALIDATION',
    sm.source_id,
    100,
    'PROPOSED',
    NULL,
    NULL,
    NULL,
    true
FROM ops.source_master sm
WHERE sm.source_code = '__g4d_validate_only__';


/* ============================================================================
13. INSERT TEST – MUSÍ BÝT PRÁVĚ 1
============================================================================ */

DO $$
DECLARE
    v_count bigint;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM ops.data_acquisition_source_routing
     WHERE entity = '__G4D_VALIDATE_ONLY__';

    IF v_count <> 1 THEN
        RAISE EXCEPTION
            'BLOCKER: canonical route insert test expected 1 row, found %',
            v_count;
    END IF;
END
$$;


/* ============================================================================
14. TESTOVACÍ ROUTE ODSTRANIT

   Stále jsme uvnitř transakce.
============================================================================ */

DELETE FROM ops.data_acquisition_source_routing
WHERE entity = '__G4D_VALIDATE_ONLY__';


/* ============================================================================
15. VALIDATION REPORT
============================================================================ */

WITH checks AS (

    /* 01 */
    SELECT
        10 AS sort_order,
        'V01_ROUTING_ROWS_BASELINE'::text AS check_id,
        CASE
            WHEN COUNT(*) = 0 THEN 'PASS'
            ELSE 'BLOCKER'
        END AS status,
        'rows=' || COUNT(*)::text AS detail
    FROM ops.data_acquisition_source_routing


    UNION ALL


    /* 02 */
    SELECT
        20,
        'V02_SOURCE_ID_COLUMN',
        CASE
            WHEN EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_schema = 'ops'
                  AND table_name = 'data_acquisition_source_routing'
                  AND column_name = 'source_id'
                  AND data_type = 'bigint'
                  AND is_nullable = 'NO'
            )
            THEN 'PASS'
            ELSE 'BLOCKER'
        END,
        'source_id BIGINT NOT NULL'


    UNION ALL


    /* 03 */
    SELECT
        30,
        'V03_LEGACY_COLUMNS_NULLABLE',
        CASE
            WHEN (
                SELECT COUNT(*)
                FROM information_schema.columns
                WHERE table_schema = 'ops'
                  AND table_name = 'data_acquisition_source_routing'
                  AND column_name IN (
                      'source_name',
                      'source_origin',
                      'source_ref_id'
                  )
                  AND is_nullable = 'YES'
            ) = 3
            THEN 'PASS'
            ELSE 'BLOCKER'
        END,
        'source_name/source_origin/source_ref_id nullable'


    UNION ALL


    /* 04 */
    SELECT
        40,
        'V04_SOURCE_FK',
        CASE
            WHEN EXISTS (
                SELECT 1
                FROM pg_constraint c
                WHERE c.conrelid =
                    'ops.data_acquisition_source_routing'::regclass
                  AND c.conname =
                    'fk_data_acq_source_routing_source'
                  AND c.contype = 'f'
            )
            THEN 'PASS'
            ELSE 'BLOCKER'
        END,
        'source_id -> ops.source_master(source_id)'


    UNION ALL


    /* 05 */
    SELECT
        50,
        'V05_SPORT_FK',
        CASE
            WHEN EXISTS (
                SELECT 1
                FROM pg_constraint c
                WHERE c.conrelid =
                    'ops.data_acquisition_source_routing'::regclass
                  AND c.conname =
                    'fk_data_acq_source_routing_sport'
                  AND c.contype = 'f'
            )
            THEN 'PASS'
            ELSE 'BLOCKER'
        END,
        'sport_code -> public.sports(code)'


    UNION ALL


    /* 06 */
    SELECT
        60,
        'V06_ROUTING_ROLE_CONTRACT',
        CASE
            WHEN pg_get_constraintdef(c.oid, true)
                    LIKE '%VALIDATION%'
             AND pg_get_constraintdef(c.oid, true)
                    LIKE '%NOT_USED%'
             AND pg_get_constraintdef(c.oid, true)
                    NOT LIKE '%REFERENCE%'
            THEN 'PASS'
            ELSE 'BLOCKER'
        END,
        pg_get_constraintdef(c.oid, true)
    FROM pg_constraint c
    WHERE c.conrelid =
            'ops.data_acquisition_source_routing'::regclass
      AND c.conname =
            'ck_data_acq_source_routing_source_role'


    UNION ALL


    /* 07 */
    SELECT
        70,
        'V07_CANONICAL_ACTIVE_SOURCE_UNIQUE',
        CASE
            WHEN indexdef LIKE '%source_id%'
             AND indexdef NOT LIKE '%source_origin%'
             AND indexdef NOT LIKE '%source_name%'
            THEN 'PASS'
            ELSE 'BLOCKER'
        END,
        indexdef
    FROM pg_indexes
    WHERE schemaname = 'ops'
      AND tablename = 'data_acquisition_source_routing'
      AND indexname =
            'uq_data_acq_source_routing_active_source'


    UNION ALL


    /* 08 */
    SELECT
        80,
        'V08_ONE_ACTIVE_PRIMARY',
        CASE
            WHEN indexdef LIKE '%source_role = ''PRIMARY''%'
             AND indexdef NOT LIKE '%decision_status%'
            THEN 'PASS'
            ELSE 'BLOCKER'
        END,
        indexdef
    FROM pg_indexes
    WHERE schemaname = 'ops'
      AND tablename = 'data_acquisition_source_routing'
      AND indexname =
            'uq_data_acq_source_routing_one_active_primary'


    UNION ALL


    /* 09 */
    SELECT
        90,
        'V09_APPROVAL_PROTECTION_PRESERVED',
        CASE
            WHEN pg_get_constraintdef(c.oid, true)
                    LIKE '%approved_at IS NOT NULL%'
             AND pg_get_constraintdef(c.oid, true)
                    LIKE '%approved_by IS NOT NULL%'
             AND pg_get_constraintdef(c.oid, true)
                    LIKE '%decision_note IS NOT NULL%'
            THEN 'PASS'
            ELSE 'BLOCKER'
        END,
        pg_get_constraintdef(c.oid, true)
    FROM pg_constraint c
    WHERE c.conrelid =
            'ops.data_acquisition_source_routing'::regclass
      AND c.conname =
            'ck_data_acq_source_routing_approval'


    UNION ALL


    /* 10 */
    SELECT
        100,
        'V10_SOURCE_MASTER_PRESENT_IN_TRANSACTION',
        CASE
            WHEN to_regclass('ops.source_master') IS NOT NULL
            THEN 'PASS'
            ELSE 'BLOCKER'
        END,
        'VALIDATE_ONLY temporary physical target'


    UNION ALL


    /* 11 */
    SELECT
        110,
        'V11_SYNTHETIC_ROUTE_CLEANED',
        CASE
            WHEN COUNT(*) = 0 THEN 'PASS'
            ELSE 'BLOCKER'
        END,
        'synthetic_rows=' || COUNT(*)::text
    FROM ops.data_acquisition_source_routing
    WHERE entity = '__G4D_VALIDATE_ONLY__'


    UNION ALL


    /* 12 */
    SELECT
        120,
        'V12_NO_APPLY',
        'PASS',
        'transaction will end with ROLLBACK'
)

SELECT
    check_id,
    status,
    detail
FROM checks
ORDER BY sort_order;


/* ============================================================================
16. SUMMARY
============================================================================ */

SELECT
    'G4D-3_STEP_4C' AS step,
    'ROUTING_COMPATIBILITY_VALIDATE_ONLY' AS operation,
    COUNT(*) AS routing_rows_before_rollback,
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS_BASELINE_EMPTY'
        ELSE 'BLOCKER'
    END AS routing_status
FROM ops.data_acquisition_source_routing;


/* ============================================================================
17. POVINNÝ ROLLBACK
============================================================================ */

ROLLBACK;