/*
CO:
STEP 9V – EXACT COVERAGE CHILD REGISTRY APPLY

K ČEMU:
Trvale vytvořit detailní Source Coverage registr:

ops.source_entity_time_scope_coverage

a vložit pouze dva již doložené HB scope navázané na:
- coverage_id 1 = HISTORY_FAN
- coverage_id 2 = HISTORY_PREDICTION
- audit evidence ID 58

DŮLEŽITÉ:
Tento krok:
- NEMĚNÍ parent coverage na CONFIRMED,
- NEVYTVÁŘÍ routing,
- NEAKTIVUJE source-adapter binding,
- NEAKTIVUJE harvest,
- NEZAPISUJE fotbalové scope,
- NENÍ Harvest Completion Registry,
- NENÍ Refresh Policy.

KDE:
Databáze matchmatrix.

JAK:
Jeden atomický PostgreSQL DO blok.
*/

DO $$
DECLARE
    v_rows              integer;
    v_bad_parent        integer;
    v_bad_evidence      integer;
    v_bad_resolution    integer;
BEGIN

    /* =====================================================
       1. COLLISION GUARD
       ===================================================== */

    IF to_regclass(
        'ops.source_entity_time_scope_coverage'
    ) IS NOT NULL THEN
        RAISE EXCEPTION
            'STEP 9V BLOCKED: ops.source_entity_time_scope_coverage již existuje.';
    END IF;


    /* =====================================================
       2. PARENT COVERAGE GUARD
       ===================================================== */

    IF NOT EXISTS (
        SELECT 1
        FROM ops.source_entity_time_coverage
        WHERE coverage_id = 1
          AND source_id = 18
          AND sport_code = 'HB'
          AND layer_type = 'CORE'
          AND entity = 'fixtures'
          AND time_mode = 'HISTORY_FAN'
          AND coverage_status = 'RUNTIME_TESTED'
    ) THEN
        RAISE EXCEPTION
            'STEP 9V BLOCKED: coverage_id=1 není očekávaný HISTORY_FAN RUNTIME_TESTED scope.';
    END IF;


    IF NOT EXISTS (
        SELECT 1
        FROM ops.source_entity_time_coverage
        WHERE coverage_id = 2
          AND source_id = 18
          AND sport_code = 'HB'
          AND layer_type = 'CORE'
          AND entity = 'fixtures'
          AND time_mode = 'HISTORY_PREDICTION'
          AND coverage_status = 'RUNTIME_TESTED'
    ) THEN
        RAISE EXCEPTION
            'STEP 9V BLOCKED: coverage_id=2 není očekávaný HISTORY_PREDICTION RUNTIME_TESTED scope.';
    END IF;


    /* =====================================================
       3. EVIDENCE GUARD
       ===================================================== */

    IF NOT EXISTS (
        SELECT 1
        FROM ops.source_audit_evidence
        WHERE audit_evidence_id = 58
          AND source_id = 18
          AND audit_dimension = 'RUNTIME_COVERAGE_TEST'
          AND result_status = 'PASS'
    ) THEN
        RAISE EXCEPTION
            'STEP 9V BLOCKED: audit evidence ID=58 není očekávaný PASS runtime důkaz.';
    END IF;


    /* =====================================================
       4. CREATE PERSISTENT TABLE
       ===================================================== */

    CREATE TABLE ops.source_entity_time_scope_coverage
    (
        scope_coverage_id
            bigint
            GENERATED BY DEFAULT AS IDENTITY
            PRIMARY KEY,

        coverage_id
            bigint
            NOT NULL,

        scope_type
            text
            NOT NULL,

        scope_key
            text
            NOT NULL,

        canonical_league_id
            integer
            NULL,

        canonical_season_id
            bigint
            NULL,

        source_competition_key
            text
            NULL,

        source_season_key
            text
            NULL,

        season_resolution_status
            text
            NOT NULL
            DEFAULT 'NOT_APPLICABLE',

        scope_from
            date
            NULL,

        scope_to
            date
            NULL,

        scope_status
            text
            NOT NULL,

        audit_evidence_id
            bigint
            NOT NULL,

        tested_at
            timestamptz
            NULL,

        is_active
            boolean
            NOT NULL
            DEFAULT true,

        notes
            text
            NULL,

        created_at
            timestamptz
            NOT NULL
            DEFAULT now(),

        updated_at
            timestamptz
            NOT NULL
            DEFAULT now(),


        CONSTRAINT fk_setsc_coverage
            FOREIGN KEY (coverage_id)
            REFERENCES ops.source_entity_time_coverage
            (coverage_id),

        CONSTRAINT fk_setsc_league
            FOREIGN KEY (canonical_league_id)
            REFERENCES public.leagues
            (id),

        CONSTRAINT fk_setsc_season
            FOREIGN KEY (canonical_season_id)
            REFERENCES public.seasons
            (id),

        CONSTRAINT fk_setsc_evidence
            FOREIGN KEY (audit_evidence_id)
            REFERENCES ops.source_audit_evidence
            (audit_evidence_id),


        CONSTRAINT uq_setsc_parent_scope
            UNIQUE (
                coverage_id,
                scope_key
            ),


        CONSTRAINT ck_setsc_scope_type_nonempty
            CHECK (
                btrim(scope_type) <> ''
            ),

        CONSTRAINT ck_setsc_scope_key_nonempty
            CHECK (
                btrim(scope_key) <> ''
            ),

        CONSTRAINT ck_setsc_scope_status
            CHECK (
                scope_status IN (
                    'UNKNOWN',
                    'PLANNED',
                    'TECH_READY',
                    'RUNTIME_TESTED',
                    'CONFIRMED',
                    'BLOCKED'
                )
            ),

        CONSTRAINT ck_setsc_season_resolution_status
            CHECK (
                season_resolution_status IN (
                    'DIRECT',
                    'COMPACT_MAPPED',
                    'UNRESOLVED',
                    'AMBIGUOUS',
                    'EMPTY',
                    'NOT_APPLICABLE'
                )
            ),

        CONSTRAINT ck_setsc_date_range
            CHECK (
                scope_from IS NULL
                OR scope_to IS NULL
                OR scope_from <= scope_to
            ),

        CONSTRAINT ck_setsc_canonical_season_resolution
            CHECK (
                canonical_season_id IS NULL
                OR season_resolution_status IN (
                    'DIRECT',
                    'COMPACT_MAPPED'
                )
            ),

        CONSTRAINT ck_setsc_resolved_requires_season
            CHECK (
                season_resolution_status NOT IN (
                    'DIRECT',
                    'COMPACT_MAPPED'
                )
                OR canonical_season_id IS NOT NULL
            ),

        CONSTRAINT ck_setsc_competition_season
            CHECK (
                scope_type <> 'COMPETITION_SEASON'
                OR (
                    canonical_league_id IS NOT NULL
                    AND source_season_key IS NOT NULL
                    AND btrim(source_season_key) <> ''
                    AND season_resolution_status
                        <> 'NOT_APPLICABLE'
                )
            )
    );


    /* =====================================================
       5. INDEXY
       ===================================================== */

    CREATE INDEX ix_setsc_coverage
        ON ops.source_entity_time_scope_coverage
        (coverage_id);

    CREATE INDEX ix_setsc_league
        ON ops.source_entity_time_scope_coverage
        (canonical_league_id);

    CREATE INDEX ix_setsc_season
        ON ops.source_entity_time_scope_coverage
        (canonical_season_id);

    CREATE INDEX ix_setsc_evidence
        ON ops.source_entity_time_scope_coverage
        (audit_evidence_id);

    CREATE INDEX ix_setsc_season_resolution
        ON ops.source_entity_time_scope_coverage
        (season_resolution_status);


    /* =====================================================
       6. KOMENTÁŘE / SÉMANTIKA
       ===================================================== */

    COMMENT ON TABLE ops.source_entity_time_scope_coverage IS
        'Detailní evidence exact Source Coverage scope pod ops.source_entity_time_coverage. '
        'Nejde o routing, refresh policy ani harvest completion.';

    COMMENT ON COLUMN
        ops.source_entity_time_scope_coverage.coverage_id IS
        'Parent canonical source×sport×layer×entity×time_mode coverage.';

    COMMENT ON COLUMN
        ops.source_entity_time_scope_coverage.source_season_key IS
        'Původní season identita použitá zdrojem nebo doloženým datovým scope; nesmí být ztracena canonicalizací.';

    COMMENT ON COLUMN
        ops.source_entity_time_scope_coverage.canonical_season_id IS
        'Volitelná bezpečně vyřešená canonical season identity z public.seasons.';

    COMMENT ON COLUMN
        ops.source_entity_time_scope_coverage.season_resolution_status IS
        'Stav vazby source_season_key na canonical season. Nejde o coverage status.';

    COMMENT ON COLUMN
        ops.source_entity_time_scope_coverage.scope_status IS
        'Evidence status konkrétního exact coverage scope.';


    /* =====================================================
       7. HB HISTORY_FAN EXACT SCOPE
       ===================================================== */

    INSERT INTO ops.source_entity_time_scope_coverage
    (
        coverage_id,
        scope_type,
        scope_key,
        canonical_league_id,
        canonical_season_id,
        source_competition_key,
        source_season_key,
        season_resolution_status,
        scope_status,
        audit_evidence_id,
        tested_at,
        notes
    )
    VALUES
    (
        1,

        'COMPETITION_SEASON',

        'league:24881|source_competition:131|source_season:2024',

        24881,
        NULL,

        '131',
        '2024',

        'UNRESOLVED',

        'RUNTIME_TESTED',

        58,

        TIMESTAMPTZ '2026-09-29 09:57:36.098+02',

        'API-Sports HB runtime test. '
        'Provider league 131, source season 2024. '
        'API returned 132 records; corresponding DB scope contained '
        '132 FINISHED matches with scores. '
        'Canonical season is intentionally unresolved.'
    );


    /* =====================================================
       8. HB HISTORY_PREDICTION EXACT SCOPE
       ===================================================== */

    INSERT INTO ops.source_entity_time_scope_coverage
    (
        coverage_id,
        scope_type,
        scope_key,
        canonical_league_id,
        canonical_season_id,
        source_competition_key,
        source_season_key,
        season_resolution_status,
        scope_status,
        audit_evidence_id,
        tested_at,
        notes
    )
    VALUES
    (
        2,

        'COMPETITION_SEASON',

        'league:24881|source_competition:131|source_season:2024',

        24881,
        NULL,

        '131',
        '2024',

        'UNRESOLVED',

        'RUNTIME_TESTED',

        58,

        TIMESTAMPTZ '2026-09-29 09:57:36.098+02',

        'API-Sports HB historical fixtures runtime evidence '
        'for model-oriented use. '
        'Canonical season is intentionally unresolved.'
    );


    /* =====================================================
       9. PERSISTENCE VALIDATION
       ===================================================== */

    SELECT COUNT(*)
    INTO v_rows
    FROM ops.source_entity_time_scope_coverage;


    SELECT COUNT(*)
    INTO v_bad_parent
    FROM ops.source_entity_time_scope_coverage d
    LEFT JOIN ops.source_entity_time_coverage p
      ON p.coverage_id = d.coverage_id
    WHERE p.coverage_id IS NULL;


    SELECT COUNT(*)
    INTO v_bad_evidence
    FROM ops.source_entity_time_scope_coverage d
    LEFT JOIN ops.source_audit_evidence e
      ON e.audit_evidence_id = d.audit_evidence_id
    WHERE e.audit_evidence_id IS NULL;


    SELECT COUNT(*)
    INTO v_bad_resolution
    FROM ops.source_entity_time_scope_coverage
    WHERE
        (
            canonical_season_id IS NOT NULL
            AND season_resolution_status NOT IN (
                'DIRECT',
                'COMPACT_MAPPED'
            )
        )
        OR
        (
            canonical_season_id IS NULL
            AND season_resolution_status IN (
                'DIRECT',
                'COMPACT_MAPPED'
            )
        );


    IF v_rows <> 2
       OR v_bad_parent <> 0
       OR v_bad_evidence <> 0
       OR v_bad_resolution <> 0
    THEN
        RAISE EXCEPTION
            'STEP 9V VALIDATION FAIL: rows=%, bad_parent=%, bad_evidence=%, bad_resolution=%',
            v_rows,
            v_bad_parent,
            v_bad_evidence,
            v_bad_resolution;
    END IF;


    RAISE NOTICE
        'STEP_9V_TABLE=ops.source_entity_time_scope_coverage';

    RAISE NOTICE
        'STEP_9V_ROWS=%',
        v_rows;

    RAISE NOTICE
        'STEP_9V_SCOPE_IDS=1:HISTORY_FAN, 2:HISTORY_PREDICTION';

    RAISE NOTICE
        'STEP_9V_SEASON_RESOLUTION=UNRESOLVED_VALID';

    RAISE NOTICE
        'STEP_9V_VALIDATE bad_parent=%, bad_evidence=%, bad_resolution=%',
        v_bad_parent,
        v_bad_evidence,
        v_bad_resolution;

    RAISE NOTICE
        'STEP_9V_STATUS=APPLY_PASS';

END
$$;