/*
CO:
STEP 10N – HARVEST COMPLETION REGISTRY FINAL CONTRACT VALIDATE_ONLY

K ČEMU:
Ověřit finální fyzický kontrakt nového exact Harvest Completion Registry.

HLAVNÍ PRINCIP:

SOURCE COVERAGE
= co zdroj umí

HARVEST TARGET
= co chceme získat

HARVEST COMPLETION
= co jsme skutečně získali a ověřili

REFRESH POLICY
= samostatná odpovědnost


VALIDAČNÍ SCÉNÁŘE:

A)
API-Sports / HB / CORE / fixtures
league 34 / season 2024
HISTORY_FAN + HISTORY_PREDICTION
→ COMPLETE
→ RECONCILED
→ source 240 = final DB 240

B)
jeden skutečný enabled HB target bez historických dat
HISTORY_FAN + HISTORY_PREDICTION
→ NOT_STARTED
→ exact coverage link = NULL
→ audit evidence = NULL

REŽIM:
VALIDATE_ONLY.

Po dokončení tabulka nesmí v DB zůstat.
*/

DO $$
DECLARE
    v_missing_target_id        bigint;
    v_missing_league_id        integer;
    v_missing_provider_league  text;
    v_missing_season           text;

    v_rows                     integer;
    v_complete                 integer;
    v_not_started              integer;
    v_bad_complete             integer;
    v_bad_not_started          integer;
    v_bad_links                integer;
BEGIN

    /* =====================================================
       1. COLLISION GUARD
       ===================================================== */

    IF to_regclass(
        'ops.harvest_scope_completion'
    ) IS NOT NULL THEN

        RAISE EXCEPTION
            'STEP 10N BLOCKED: ops.harvest_scope_completion již existuje.';

    END IF;


    /* =====================================================
       2. REAL NOT-STARTED TARGET

       Vybereme skutečný enabled HB target,
       pro který dnes nemáme žádná api_handball historical data.

       Současně vyžadujeme, aby pro něj ještě neexistoval
       exact source coverage scope.
       ===================================================== */

    SELECT
        t.id,
        t.canonical_league_id::integer,
        t.provider_league_id::text,
        t.season::text

    INTO
        v_missing_target_id,
        v_missing_league_id,
        v_missing_provider_league,
        v_missing_season

    FROM ops.ingest_targets t

    WHERE t.provider = 'api_handball'
      AND t.sport_code = 'HB'
      AND t.season = '2024'
      AND t.enabled = true

      AND NOT EXISTS (
          SELECT 1
          FROM public.matches m
          JOIN public.match_provider_map mpm
            ON mpm.match_id = m.id
           AND mpm.provider = 'api_handball'
          WHERE m.league_id = t.canonical_league_id
            AND m.season::text = t.season::text
      )

      AND NOT EXISTS (
          SELECT 1
          FROM ops.source_entity_time_scope_coverage d
          WHERE d.canonical_league_id = t.canonical_league_id
            AND d.source_competition_key
                = t.provider_league_id::text
            AND d.source_season_key
                = t.season::text
      )

    ORDER BY
        t.tier,
        t.id

    LIMIT 1;


    IF v_missing_target_id IS NULL THEN
        RAISE EXCEPTION
            'STEP 10N BLOCKED: nebyl nalezen vhodný NOT_STARTED HB target.';
    END IF;


    /* =====================================================
       3. CREATE VALIDATION TABLE
       ===================================================== */

    EXECUTE $DDL$

        CREATE TABLE ops.harvest_scope_completion
        (
            completion_id
                bigint
                GENERATED BY DEFAULT AS IDENTITY
                PRIMARY KEY,


            /* ---------------------------------------------
               CANONICAL DATASET IDENTITY
               --------------------------------------------- */

            source_id
                bigint
                NOT NULL,

            sport_code
                text
                NOT NULL,

            layer_type
                text
                NOT NULL,

            entity
                text
                NOT NULL,

            time_mode
                text
                NOT NULL,


            /* ---------------------------------------------
               EXACT DATA SCOPE
               --------------------------------------------- */

            scope_type
                text
                NOT NULL,

            scope_key
                text
                NOT NULL,

            canonical_league_id
                integer
                NULL,

            canonical_season_id
                bigint
                NULL,

            source_competition_key
                text
                NULL,

            source_season_key
                text
                NULL,

            scope_from
                date
                NULL,

            scope_to
                date
                NULL,


            /* ---------------------------------------------
               OPTIONAL LINKS

               Completion musí přežít změnu nebo odstranění
               provozních / evidence objektů.
               --------------------------------------------- */

            ingest_target_id
                bigint
                NULL,

            scope_coverage_id
                bigint
                NULL,

            audit_evidence_id
                bigint
                NULL,

            harvest_run_monitor_id
                bigint
                NULL,


            /* ---------------------------------------------
               COMPLETION COUNTERS
               --------------------------------------------- */

            expected_count
                bigint
                NULL,

            source_observed_count
                bigint
                NULL,

            harvested_count
                bigint
                NULL,

            parsed_count
                bigint
                NULL,

            merged_count
                bigint
                NULL,

            rejected_count
                bigint
                NULL,


            /* ---------------------------------------------
               COMPLETION STATE
               --------------------------------------------- */

            completion_status
                text
                NOT NULL,

            verification_status
                text
                NOT NULL
                DEFAULT 'UNVERIFIED',

            completed_at
                timestamptz
                NULL,

            verified_at
                timestamptz
                NULL,

            last_checked_at
                timestamptz
                NULL,


            /* ---------------------------------------------
               METADATA
               --------------------------------------------- */

            notes
                text
                NULL,

            created_at
                timestamptz
                NOT NULL
                DEFAULT now(),

            updated_at
                timestamptz
                NOT NULL
                DEFAULT now(),


            /* =============================================
               FOREIGN KEYS
               ============================================= */

            CONSTRAINT fk_hsc_source
                FOREIGN KEY (source_id)
                REFERENCES ops.source_master
                    (source_id),

            CONSTRAINT fk_hsc_sport
                FOREIGN KEY (sport_code)
                REFERENCES public.sports
                    (code),

            CONSTRAINT fk_hsc_league
                FOREIGN KEY (canonical_league_id)
                REFERENCES public.leagues
                    (id),

            CONSTRAINT fk_hsc_season
                FOREIGN KEY (canonical_season_id)
                REFERENCES public.seasons
                    (id),

            /*
            Ingest target je provozní objekt.
            Jeho odstranění nesmí smazat completion history.
            */
            CONSTRAINT fk_hsc_ingest_target
                FOREIGN KEY (ingest_target_id)
                REFERENCES ops.ingest_targets
                    (id)
                ON DELETE SET NULL,

            /*
            Exact Source Coverage je samostatná evidence.
            Completion bez ní musí být validní.
            */
            CONSTRAINT fk_hsc_scope_coverage
                FOREIGN KEY (scope_coverage_id)
                REFERENCES ops.source_entity_time_scope_coverage
                    (scope_coverage_id)
                ON DELETE SET NULL,

            CONSTRAINT fk_hsc_audit_evidence
                FOREIGN KEY (audit_evidence_id)
                REFERENCES ops.source_audit_evidence
                    (audit_evidence_id)
                ON DELETE SET NULL,

            CONSTRAINT fk_hsc_run_monitor
                FOREIGN KEY (harvest_run_monitor_id)
                REFERENCES ops.harvest_run_monitor
                    (monitor_id)
                ON DELETE SET NULL,


            /* =============================================
               IDENTITY / UNIQUENESS
               ============================================= */

            CONSTRAINT uq_hsc_dataset_scope
                UNIQUE
                (
                    source_id,
                    sport_code,
                    layer_type,
                    entity,
                    time_mode,
                    scope_key
                ),


            /* =============================================
               REQUIRED TEXT
               ============================================= */

            CONSTRAINT ck_hsc_required_text
                CHECK (
                    btrim(sport_code) <> ''
                    AND btrim(layer_type) <> ''
                    AND btrim(entity) <> ''
                    AND btrim(scope_type) <> ''
                    AND btrim(scope_key) <> ''
                ),


            /* =============================================
               TIME MODE
               ============================================= */

            CONSTRAINT ck_hsc_time_mode
                CHECK (
                    time_mode IN (
                        'HISTORY_FAN',
                        'HISTORY_PREDICTION',
                        'CURRENT',
                        'FUTURE',
                        'LIVE'
                    )
                ),


            /* =============================================
               COMPLETION STATUS
               ============================================= */

            CONSTRAINT ck_hsc_completion_status
                CHECK (
                    completion_status IN (
                        'UNKNOWN',
                        'NOT_STARTED',
                        'IN_PROGRESS',
                        'PARTIAL',
                        'COMPLETE',
                        'COMPLETE_WITH_EXCEPTIONS',
                        'BLOCKED',
                        'FAILED'
                    )
                ),


            /* =============================================
               VERIFICATION STATUS
               ============================================= */

            CONSTRAINT ck_hsc_verification_status
                CHECK (
                    verification_status IN (
                        'UNVERIFIED',
                        'COUNT_MATCH',
                        'RECONCILED',
                        'MISMATCH',
                        'NOT_APPLICABLE'
                    )
                ),


            /* =============================================
               NONNEGATIVE COUNTERS
               ============================================= */

            CONSTRAINT ck_hsc_nonnegative_counts
                CHECK (
                    COALESCE(expected_count, 0) >= 0
                    AND COALESCE(source_observed_count, 0) >= 0
                    AND COALESCE(harvested_count, 0) >= 0
                    AND COALESCE(parsed_count, 0) >= 0
                    AND COALESCE(merged_count, 0) >= 0
                    AND COALESCE(rejected_count, 0) >= 0
                ),


            /* =============================================
               DATE RANGE
               ============================================= */

            CONSTRAINT ck_hsc_date_range
                CHECK (
                    scope_from IS NULL
                    OR scope_to IS NULL
                    OR scope_from <= scope_to
                ),


            /* =============================================
               COMPETITION SEASON SCOPE

               Canonical season není povinná.
               Raw/source season key se zachovává.
               ============================================= */

            CONSTRAINT ck_hsc_competition_season
                CHECK (
                    scope_type <> 'COMPETITION_SEASON'

                    OR
                    (
                        canonical_league_id IS NOT NULL

                        AND
                        (
                            canonical_season_id IS NOT NULL

                            OR
                            (
                                source_season_key IS NOT NULL
                                AND btrim(source_season_key) <> ''
                            )
                        )
                    )
                ),


            /* =============================================
               COMPLETE CONTRACT

               COMPLETE znamená:
               - známe očekávaný počet,
               - známe aktuálně pozorovaný počet na zdroji,
               - známe final merged/stored počet,
               - všechny tři se shodují,
               - existuje verification,
               - existuje completed_at.

               harvested_count a parsed_count mohou být NULL,
               protože dataset může být zpětně potvrzen
               source-vs-final-DB reconciliation testem.
               ============================================= */

            CONSTRAINT ck_hsc_complete_contract
                CHECK (
                    completion_status <> 'COMPLETE'

                    OR
                    (
                        expected_count IS NOT NULL
                        AND source_observed_count IS NOT NULL
                        AND merged_count IS NOT NULL

                        AND expected_count
                            = source_observed_count

                        AND source_observed_count
                            = merged_count

                        AND verification_status IN (
                            'COUNT_MATCH',
                            'RECONCILED'
                        )

                        AND completed_at IS NOT NULL
                    )
                ),


            /* =============================================
               NOT STARTED CONTRACT
               ============================================= */

            CONSTRAINT ck_hsc_not_started_contract
                CHECK (
                    completion_status <> 'NOT_STARTED'

                    OR
                    (
                        COALESCE(harvested_count, 0) = 0
                        AND COALESCE(parsed_count, 0) = 0
                        AND COALESCE(merged_count, 0) = 0
                        AND completed_at IS NULL
                    )
                )
        )

    $DDL$;


    /* =====================================================
       4. INDEXY
       ===================================================== */

    EXECUTE '
        CREATE INDEX ix_hsc_source_scope
        ON ops.harvest_scope_completion
        (
            source_id,
            sport_code,
            layer_type,
            entity,
            time_mode
        )
    ';

    EXECUTE '
        CREATE INDEX ix_hsc_ingest_target
        ON ops.harvest_scope_completion
        (ingest_target_id)
    ';

    EXECUTE '
        CREATE INDEX ix_hsc_scope_coverage
        ON ops.harvest_scope_completion
        (scope_coverage_id)
    ';

    EXECUTE '
        CREATE INDEX ix_hsc_completion_status
        ON ops.harvest_scope_completion
        (completion_status)
    ';

    EXECUTE '
        CREATE INDEX ix_hsc_league
        ON ops.harvest_scope_completion
        (canonical_league_id)
    ';


    /* =====================================================
       5. VALIDATION A:
          LEAGUE 34 – VERIFIED COMPLETE

          Vloží se 2 rows:
          HISTORY_FAN
          HISTORY_PREDICTION
       ===================================================== */

    INSERT INTO ops.harvest_scope_completion
    (
        source_id,
        sport_code,
        layer_type,
        entity,
        time_mode,

        scope_type,
        scope_key,

        canonical_league_id,
        canonical_season_id,

        source_competition_key,
        source_season_key,

        ingest_target_id,
        scope_coverage_id,
        audit_evidence_id,
        harvest_run_monitor_id,

        expected_count,
        source_observed_count,

        harvested_count,
        parsed_count,
        merged_count,
        rejected_count,

        completion_status,
        verification_status,

        completed_at,
        verified_at,
        last_checked_at,

        notes
    )

    SELECT
        18,
        'HB',
        'CORE',
        'fixtures',
        c.time_mode,

        'COMPETITION_SEASON',
        d.scope_key,

        d.canonical_league_id,
        d.canonical_season_id,

        d.source_competition_key,
        d.source_season_key,

        t.id,
        d.scope_coverage_id,
        59,
        NULL,

        (e.result_detail::jsonb
            ->> 'db_expected_matches')::bigint,

        (e.result_detail::jsonb
            ->> 'api_returned_matches')::bigint,

        NULL,
        NULL,

        (e.result_detail::jsonb
            ->> 'db_expected_matches')::bigint,

        NULL,

        'COMPLETE',
        'RECONCILED',

        e.evidence_date,
        e.evidence_date,
        e.evidence_date,

        'STEP 10N VALIDATE_ONLY. '
        'League 34 / season 2024. '
        'Completion proven by current API count versus final DB reconciliation; '
        'historical pipeline stage counters are intentionally unknown.'

    FROM ops.source_entity_time_scope_coverage d

    JOIN ops.source_entity_time_coverage c
      ON c.coverage_id = d.coverage_id

    JOIN ops.source_audit_evidence e
      ON e.audit_evidence_id = 59

    JOIN ops.ingest_targets t
      ON t.provider = 'api_handball'
     AND t.sport_code = 'HB'
     AND t.provider_league_id = '34'
     AND t.season = '2024'

    WHERE d.source_competition_key = '34'
      AND d.source_season_key = '2024'
      AND d.scope_status = 'CONFIRMED'

      AND c.source_id = 18
      AND c.sport_code = 'HB'
      AND c.layer_type = 'CORE'
      AND c.entity = 'fixtures'

      AND c.time_mode IN (
          'HISTORY_FAN',
          'HISTORY_PREDICTION'
      );


    /* =====================================================
       6. VALIDATION B:
          REAL TARGET WITHOUT HISTORY

          Vloží se 2 rows:
          HISTORY_FAN
          HISTORY_PREDICTION

          Exact Coverage link ani evidence zde nejsou povinné.
       ===================================================== */

    INSERT INTO ops.harvest_scope_completion
    (
        source_id,
        sport_code,
        layer_type,
        entity,
        time_mode,

        scope_type,
        scope_key,

        canonical_league_id,
        canonical_season_id,

        source_competition_key,
        source_season_key,

        ingest_target_id,
        scope_coverage_id,
        audit_evidence_id,
        harvest_run_monitor_id,

        expected_count,
        source_observed_count,

        harvested_count,
        parsed_count,
        merged_count,
        rejected_count,

        completion_status,
        verification_status,

        completed_at,
        verified_at,
        last_checked_at,

        notes
    )

    SELECT
        18,
        'HB',
        'CORE',
        'fixtures',
        tm.time_mode,

        'COMPETITION_SEASON',

        format(
            'league:%s|source_competition:%s|source_season:%s',
            v_missing_league_id,
            v_missing_provider_league,
            v_missing_season
        ),

        v_missing_league_id,
        NULL,

        v_missing_provider_league,
        v_missing_season,

        v_missing_target_id,
        NULL,
        NULL,
        NULL,

        NULL,
        NULL,

        0,
        0,
        0,
        0,

        'NOT_STARTED',
        'UNVERIFIED',

        NULL,
        NULL,
        NULL,

        'STEP 10N VALIDATE_ONLY. '
        'Real enabled HB target without stored api_handball history. '
        'No exact coverage or audit evidence required for NOT_STARTED completion state.'

    FROM (
        VALUES
            ('HISTORY_FAN'::text),
            ('HISTORY_PREDICTION'::text)
    ) AS tm(time_mode);


    /* =====================================================
       7. VALIDACE
       ===================================================== */

    SELECT COUNT(*)
    INTO v_rows
    FROM ops.harvest_scope_completion;


    SELECT COUNT(*)
    INTO v_complete
    FROM ops.harvest_scope_completion
    WHERE completion_status = 'COMPLETE'
      AND verification_status = 'RECONCILED';


    SELECT COUNT(*)
    INTO v_not_started
    FROM ops.harvest_scope_completion
    WHERE completion_status = 'NOT_STARTED'
      AND verification_status = 'UNVERIFIED';


    SELECT COUNT(*)
    INTO v_bad_complete
    FROM ops.harvest_scope_completion
    WHERE completion_status = 'COMPLETE'
      AND (
           expected_count IS NULL
        OR source_observed_count IS NULL
        OR merged_count IS NULL
        OR expected_count <> source_observed_count
        OR source_observed_count <> merged_count
        OR completed_at IS NULL
      );


    SELECT COUNT(*)
    INTO v_bad_not_started
    FROM ops.harvest_scope_completion
    WHERE completion_status = 'NOT_STARTED'
      AND (
           COALESCE(harvested_count, 0) <> 0
        OR COALESCE(parsed_count, 0) <> 0
        OR COALESCE(merged_count, 0) <> 0
        OR completed_at IS NOT NULL
      );


    SELECT COUNT(*)
    INTO v_bad_links
    FROM ops.harvest_scope_completion
    WHERE
        (
            completion_status = 'COMPLETE'
            AND (
                   scope_coverage_id IS NULL
                OR audit_evidence_id IS NULL
            )
        )

        OR
        (
            completion_status = 'NOT_STARTED'
            AND (
                   scope_coverage_id IS NOT NULL
                OR audit_evidence_id IS NOT NULL
            )
        );


    IF v_rows <> 4
       OR v_complete <> 2
       OR v_not_started <> 2
       OR v_bad_complete <> 0
       OR v_bad_not_started <> 0
       OR v_bad_links <> 0
    THEN

        RAISE EXCEPTION
            'STEP 10N VALIDATION FAIL: rows=%, complete=%, not_started=%, bad_complete=%, bad_not_started=%, bad_links=%',
            v_rows,
            v_complete,
            v_not_started,
            v_bad_complete,
            v_bad_not_started,
            v_bad_links;

    END IF;


    RAISE NOTICE
        'STEP_10N_ROWS=%',
        v_rows;

    RAISE NOTICE
        'STEP_10N_COMPLETE=%',
        v_complete;

    RAISE NOTICE
        'STEP_10N_NOT_STARTED=%',
        v_not_started;

    RAISE NOTICE
        'STEP_10N_COMPLETE_SCOPE=league_24942/source_league_34/season_2024';

    RAISE NOTICE
        'STEP_10N_NOT_STARTED_TARGET_ID=%',
        v_missing_target_id;

    RAISE NOTICE
        'STEP_10N_OPTIONAL_SCOPE_COVERAGE_LINK=PASS';

    RAISE NOTICE
        'STEP_10N_OPTIONAL_EVIDENCE_LINK=PASS';

    RAISE NOTICE
        'STEP_10N_INGEST_TARGET_DELETE_POLICY=SET_NULL';

    RAISE NOTICE
        'STEP_10N_VALIDATE bad_complete=%, bad_not_started=%, bad_links=%',
        v_bad_complete,
        v_bad_not_started,
        v_bad_links;


    /* =====================================================
       8. CLEANUP – VALIDATE ONLY
       ===================================================== */

    EXECUTE '
        DROP TABLE ops.harvest_scope_completion
    ';


    IF to_regclass(
        'ops.harvest_scope_completion'
    ) IS NOT NULL THEN

        RAISE EXCEPTION
            'STEP 10N CLEANUP FAIL: validační tabulka zůstala v DB.';

    END IF;


    RAISE NOTICE
        'STEP_10N_CLEANUP=OK';

    RAISE NOTICE
        'STEP_10N_STATUS=VALIDATE_ONLY_PASS';

END
$$;