/*
CO:
STEP 9U – EXACT COVERAGE CHILD REGISTRY FINAL CONTRACT VALIDATE_ONLY

K ČEMU:
Ověřit finální fyzický kontrakt detailního Source Coverage registru
po stress testu na házené i fotbale.

HLAVNÍ PRINCIPY:
- canonical season je volitelná,
- raw/source season key se vždy zachovává,
- season resolution má vlastní stav,
- season resolution není coverage status,
- registr není Routing,
- registr není Refresh Policy,
- registr není Harvest Completion.

REŽIM:
VALIDATE_ONLY.
Po dokončení objekt nesmí v DB zůstat.
*/

DO $$
DECLARE
    v_rows                  integer;
    v_bad_parent            integer;
    v_bad_evidence          integer;
    v_bad_resolution        integer;
BEGIN

    /* =====================================================
       1. COLLISION GUARD
       ===================================================== */

    IF to_regclass(
        'ops.source_entity_time_scope_coverage'
    ) IS NOT NULL THEN
        RAISE EXCEPTION
            'STEP 9U BLOCKED: cílová tabulka již existuje.';
    END IF;


    /* =====================================================
       2. CREATE VALIDATION TABLE
       ===================================================== */

    EXECUTE $DDL$

        CREATE TABLE ops.source_entity_time_scope_coverage
        (
            scope_coverage_id
                bigint
                GENERATED BY DEFAULT AS IDENTITY
                PRIMARY KEY,

            coverage_id
                bigint
                NOT NULL,

            scope_type
                text
                NOT NULL,

            scope_key
                text
                NOT NULL,

            canonical_league_id
                integer
                NULL,

            canonical_season_id
                bigint
                NULL,

            source_competition_key
                text
                NULL,

            source_season_key
                text
                NULL,

            season_resolution_status
                text
                NOT NULL
                DEFAULT 'NOT_APPLICABLE',

            scope_from
                date
                NULL,

            scope_to
                date
                NULL,

            scope_status
                text
                NOT NULL,

            audit_evidence_id
                bigint
                NOT NULL,

            tested_at
                timestamptz
                NULL,

            is_active
                boolean
                NOT NULL
                DEFAULT true,

            notes
                text
                NULL,

            created_at
                timestamptz
                NOT NULL
                DEFAULT now(),

            updated_at
                timestamptz
                NOT NULL
                DEFAULT now(),


            CONSTRAINT fk_setsc_coverage
                FOREIGN KEY (coverage_id)
                REFERENCES ops.source_entity_time_coverage
                (coverage_id),

            CONSTRAINT fk_setsc_league
                FOREIGN KEY (canonical_league_id)
                REFERENCES public.leagues
                (id),

            CONSTRAINT fk_setsc_season
                FOREIGN KEY (canonical_season_id)
                REFERENCES public.seasons
                (id),

            CONSTRAINT fk_setsc_evidence
                FOREIGN KEY (audit_evidence_id)
                REFERENCES ops.source_audit_evidence
                (audit_evidence_id),


            CONSTRAINT uq_setsc_parent_scope
                UNIQUE (
                    coverage_id,
                    scope_key
                ),


            CONSTRAINT ck_setsc_scope_type_nonempty
                CHECK (
                    btrim(scope_type) <> ''
                ),

            CONSTRAINT ck_setsc_scope_key_nonempty
                CHECK (
                    btrim(scope_key) <> ''
                ),

            CONSTRAINT ck_setsc_scope_status
                CHECK (
                    scope_status IN (
                        'UNKNOWN',
                        'PLANNED',
                        'TECH_READY',
                        'RUNTIME_TESTED',
                        'CONFIRMED',
                        'BLOCKED'
                    )
                ),

            CONSTRAINT ck_setsc_season_resolution_status
                CHECK (
                    season_resolution_status IN (
                        'DIRECT',
                        'COMPACT_MAPPED',
                        'UNRESOLVED',
                        'AMBIGUOUS',
                        'EMPTY',
                        'NOT_APPLICABLE'
                    )
                ),

            CONSTRAINT ck_setsc_date_range
                CHECK (
                    scope_from IS NULL
                    OR scope_to IS NULL
                    OR scope_from <= scope_to
                ),

            /*
            Pokud máme canonical season,
            resolution nesmí být UNRESOLVED / EMPTY.
            */
            CONSTRAINT ck_setsc_canonical_season_resolution
                CHECK (
                    canonical_season_id IS NULL
                    OR season_resolution_status IN (
                        'DIRECT',
                        'COMPACT_MAPPED'
                    )
                ),

            /*
            Pokud je resolution DIRECT nebo COMPACT_MAPPED,
            canonical season musí existovat.
            */
            CONSTRAINT ck_setsc_resolved_requires_season
                CHECK (
                    season_resolution_status NOT IN (
                        'DIRECT',
                        'COMPACT_MAPPED'
                    )
                    OR canonical_season_id IS NOT NULL
                ),

            /*
            COMPETITION_SEASON vyžaduje:
            - canonical league
            - source season key

            Canonical season může zůstat NULL.
            */
            CONSTRAINT ck_setsc_competition_season
                CHECK (
                    scope_type <> 'COMPETITION_SEASON'
                    OR (
                        canonical_league_id IS NOT NULL
                        AND source_season_key IS NOT NULL
                        AND btrim(source_season_key) <> ''
                        AND season_resolution_status
                            <> 'NOT_APPLICABLE'
                    )
                )
        )

    $DDL$;


    /* =====================================================
       3. INDEXY
       ===================================================== */

    EXECUTE '
        CREATE INDEX ix_setsc_coverage
        ON ops.source_entity_time_scope_coverage
        (coverage_id)
    ';

    EXECUTE '
        CREATE INDEX ix_setsc_league
        ON ops.source_entity_time_scope_coverage
        (canonical_league_id)
    ';

    EXECUTE '
        CREATE INDEX ix_setsc_season
        ON ops.source_entity_time_scope_coverage
        (canonical_season_id)
    ';

    EXECUTE '
        CREATE INDEX ix_setsc_evidence
        ON ops.source_entity_time_scope_coverage
        (audit_evidence_id)
    ';

    EXECUTE '
        CREATE INDEX ix_setsc_season_resolution
        ON ops.source_entity_time_scope_coverage
        (season_resolution_status)
    ';


    /* =====================================================
       4. HB HISTORY_FAN – UNRESOLVED SEASON
       ===================================================== */

    INSERT INTO ops.source_entity_time_scope_coverage
    (
        coverage_id,
        scope_type,
        scope_key,
        canonical_league_id,
        canonical_season_id,
        source_competition_key,
        source_season_key,
        season_resolution_status,
        scope_status,
        audit_evidence_id,
        tested_at,
        notes
    )
    VALUES
    (
        1,
        'COMPETITION_SEASON',

        'league:24881|source_competition:131|source_season:2024',

        24881,
        NULL,

        '131',
        '2024',

        'UNRESOLVED',

        'RUNTIME_TESTED',

        58,

        TIMESTAMPTZ '2026-09-29 09:57:36.098+02',

        'API-Sports HB runtime test. '
        '132 API results / 132 verified DB matches. '
        'Canonical season not yet available for HB.'
    );


    /* =====================================================
       5. HB HISTORY_PREDICTION – STEJNÝ EXACT SCOPE
       ===================================================== */

    INSERT INTO ops.source_entity_time_scope_coverage
    (
        coverage_id,
        scope_type,
        scope_key,
        canonical_league_id,
        canonical_season_id,
        source_competition_key,
        source_season_key,
        season_resolution_status,
        scope_status,
        audit_evidence_id,
        tested_at,
        notes
    )
    VALUES
    (
        2,
        'COMPETITION_SEASON',

        'league:24881|source_competition:131|source_season:2024',

        24881,
        NULL,

        '131',
        '2024',

        'UNRESOLVED',

        'RUNTIME_TESTED',

        58,

        TIMESTAMPTZ '2026-09-29 09:57:36.098+02',

        'API-Sports HB historical fixtures runtime evidence '
        'for model-oriented use. '
        'Canonical season unresolved.'
    );


    /* =====================================================
       6. VALIDACE
       ===================================================== */

    SELECT COUNT(*)
    INTO v_rows
    FROM ops.source_entity_time_scope_coverage;


    SELECT COUNT(*)
    INTO v_bad_parent
    FROM ops.source_entity_time_scope_coverage d
    LEFT JOIN ops.source_entity_time_coverage p
      ON p.coverage_id = d.coverage_id
    WHERE p.coverage_id IS NULL;


    SELECT COUNT(*)
    INTO v_bad_evidence
    FROM ops.source_entity_time_scope_coverage d
    LEFT JOIN ops.source_audit_evidence e
      ON e.audit_evidence_id = d.audit_evidence_id
    WHERE e.audit_evidence_id IS NULL;


    SELECT COUNT(*)
    INTO v_bad_resolution
    FROM ops.source_entity_time_scope_coverage
    WHERE
        (
            canonical_season_id IS NOT NULL
            AND season_resolution_status NOT IN (
                'DIRECT',
                'COMPACT_MAPPED'
            )
        )
        OR
        (
            canonical_season_id IS NULL
            AND season_resolution_status IN (
                'DIRECT',
                'COMPACT_MAPPED'
            )
        );


    IF v_rows <> 2
       OR v_bad_parent <> 0
       OR v_bad_evidence <> 0
       OR v_bad_resolution <> 0
    THEN
        RAISE EXCEPTION
            'STEP 9U VALIDATION FAIL: rows=%, bad_parent=%, bad_evidence=%, bad_resolution=%',
            v_rows,
            v_bad_parent,
            v_bad_evidence,
            v_bad_resolution;
    END IF;


    RAISE NOTICE
        'STEP_9U_ROWS=%',
        v_rows;

    RAISE NOTICE
        'STEP_9U_HB_SEASON_RESOLUTION=UNRESOLVED_VALID';

    RAISE NOTICE
        'STEP_9U_FOOTBALL_STRESS_TEST=DIRECT_AND_COMPACT_AND_UNRESOLVED_SUPPORTED';

    RAISE NOTICE
        'STEP_9U_VALIDATE bad_parent=%, bad_evidence=%, bad_resolution=%',
        v_bad_parent,
        v_bad_evidence,
        v_bad_resolution;


    /* =====================================================
       7. CLEANUP
       ===================================================== */

    EXECUTE '
        DROP TABLE ops.source_entity_time_scope_coverage
    ';


    IF to_regclass(
        'ops.source_entity_time_scope_coverage'
    ) IS NOT NULL THEN
        RAISE EXCEPTION
            'STEP 9U CLEANUP FAIL: validační tabulka zůstala v DB.';
    END IF;


    RAISE NOTICE
        'STEP_9U_CLEANUP=OK';

    RAISE NOTICE
        'STEP_9U_STATUS=VALIDATE_ONLY_PASS';

END
$$;