BEGIN;

CREATE TABLE ops.harvest_scope_refresh_policy (
    policy_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source_id bigint NOT NULL,
    sport_code text NOT NULL,
    layer_type text NOT NULL,
    entity text NOT NULL,
    time_mode text NOT NULL,
    scope_type text NOT NULL,
    scope_key text NOT NULL,

    canonical_league_id integer,
    canonical_season_id bigint,
    source_competition_key text,
    source_season_key text,
    scope_from date,
    scope_to date,
    ingest_target_id bigint,
    scope_coverage_id bigint,

    policy_status text NOT NULL DEFAULT 'DRAFT',
    refresh_mode text NOT NULL DEFAULT 'UNDECIDED',
    min_refresh_interval_seconds integer,
    policy_reason text,
    approved_by text,
    approved_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_hsrp_dataset_scope UNIQUE
        (source_id, sport_code, layer_type, entity, time_mode, scope_key),

    CONSTRAINT fk_hsrp_source FOREIGN KEY (source_id)
        REFERENCES ops.source_master(source_id),
    CONSTRAINT fk_hsrp_sport FOREIGN KEY (sport_code)
        REFERENCES sports(code),
    CONSTRAINT fk_hsrp_league FOREIGN KEY (canonical_league_id)
        REFERENCES leagues(id),
    CONSTRAINT fk_hsrp_season FOREIGN KEY (canonical_season_id)
        REFERENCES seasons(id),
    CONSTRAINT fk_hsrp_target FOREIGN KEY (ingest_target_id)
        REFERENCES ops.ingest_targets(id) ON DELETE SET NULL,
    CONSTRAINT fk_hsrp_scope_coverage FOREIGN KEY (scope_coverage_id)
        REFERENCES ops.source_entity_time_scope_coverage(scope_coverage_id)
        ON DELETE SET NULL,

    CONSTRAINT ck_hsrp_required_text CHECK (
        btrim(sport_code) <> ''
        AND btrim(layer_type) <> ''
        AND btrim(entity) <> ''
        AND btrim(scope_type) <> ''
        AND btrim(scope_key) <> ''
    ),
    CONSTRAINT ck_hsrp_time_mode CHECK (
        time_mode IN (
            'HISTORY_FAN', 'HISTORY_PREDICTION',
            'CURRENT', 'FUTURE', 'LIVE'
        )
    ),
    CONSTRAINT ck_hsrp_competition_season CHECK (
        scope_type <> 'COMPETITION_SEASON'
        OR (
            canonical_league_id IS NOT NULL
            AND (
                canonical_season_id IS NOT NULL
                OR nullif(btrim(source_season_key), '') IS NOT NULL
            )
        )
    ),
    CONSTRAINT ck_hsrp_date_range CHECK (
        scope_from IS NULL OR scope_to IS NULL OR scope_from <= scope_to
    ),
    CONSTRAINT ck_hsrp_policy_status CHECK (
        policy_status IN ('DRAFT', 'APPROVED', 'PAUSED', 'RETIRED')
    ),
    CONSTRAINT ck_hsrp_refresh_mode CHECK (
        refresh_mode IN ('UNDECIDED', 'STATIC_ONCE', 'PERIODIC', 'MANUAL')
    ),
    CONSTRAINT ck_hsrp_interval CHECK (
        (
            refresh_mode = 'PERIODIC'
            AND min_refresh_interval_seconds IS NOT NULL
            AND min_refresh_interval_seconds > 0
        )
        OR (
            refresh_mode <> 'PERIODIC'
            AND min_refresh_interval_seconds IS NULL
        )
    ),
    CONSTRAINT ck_hsrp_approval CHECK (
        policy_status <> 'APPROVED'
        OR (
            refresh_mode <> 'UNDECIDED'
            AND approved_at IS NOT NULL
            AND nullif(btrim(approved_by), '') IS NOT NULL
            AND nullif(btrim(policy_reason), '') IS NOT NULL
        )
    )
);

COMMIT;

SELECT to_regclass('ops.harvest_scope_refresh_policy') AS persisted_table;