/*
CO:
STEP 10P – HARVEST COMPLETION REGISTRY APPLY

K ČEMU:
Trvale vytvořit canonical Harvest Completion Registry:

ops.harvest_scope_completion

a inicializovat jej pro současný HB historical target universe:

211 enabled targetů
×
2 historical time modes
=
422 completion rows.

KLASIFIKACE:

COMPLETE
= exact Source Coverage CONFIRMED
+ PASS runtime evidence
+ API observed count = expected DB count
+ final DB scope je čistý a počet souhlasí

PARTIAL
= historická data v DB existují,
  ale completeness vůči provideru zatím nebyla potvrzena

NOT_STARTED
= enabled harvest target existuje,
  ale historical api_handball data v DB nejsou.

DŮLEŽITÉ:
Tento registr:
- NENÍ Source Coverage,
- NENÍ Routing,
- NENÍ Refresh Policy,
- NENÍ Planner,
- NENÍ Run Monitor.

Tento krok:
- NEAKTIVUJE binding,
- NEVYTVÁŘÍ routing,
- NESPOUŠTÍ harvest,
- NEMĚNÍ parent coverage.

KDE:
Databáze matchmatrix.

JAK:
Jeden atomický PostgreSQL DO blok.
*/

DO $$
DECLARE
    v_inserted              integer;

    v_complete_rows         integer;
    v_partial_rows          integer;
    v_not_started_rows      integer;

    v_complete_targets      integer;
    v_partial_targets       integer;
    v_not_started_targets   integer;

    v_bad_complete          integer;
    v_bad_not_started       integer;
    v_bad_total             integer;

    v_parent_confirmed      integer;
    v_active_bindings       integer;
    v_routes                integer;
BEGIN

    /* =====================================================
       1. COLLISION GUARD
       ===================================================== */

    IF to_regclass(
        'ops.harvest_scope_completion'
    ) IS NOT NULL THEN

        RAISE EXCEPTION
            'STEP 10P BLOCKED: ops.harvest_scope_completion již existuje.';

    END IF;


    /* =====================================================
       2. SOURCE / TARGET UNIVERSE GUARDS
       ===================================================== */

    IF NOT EXISTS (
        SELECT 1
        FROM ops.source_master
        WHERE source_id = 18
          AND source_code = 'api_sports'
          AND canonical_name = 'API-Sports'
    ) THEN

        RAISE EXCEPTION
            'STEP 10P BLOCKED: source_id=18 není očekávaná API-Sports identita.';

    END IF;


    IF (
        SELECT COUNT(*)
        FROM ops.ingest_targets
        WHERE provider = 'api_handball'
          AND sport_code = 'HB'
          AND season = '2024'
          AND enabled = true
    ) <> 211 THEN

        RAISE EXCEPTION
            'STEP 10P BLOCKED: enabled HB target universe není očekávaných 211 řádků.';

    END IF;


    /* =====================================================
       3. CREATE PERSISTENT REGISTRY
       ===================================================== */

    CREATE TABLE ops.harvest_scope_completion
    (
        completion_id
            bigint
            GENERATED BY DEFAULT AS IDENTITY
            PRIMARY KEY,


        /* -------------------------------------------------
           CANONICAL DATASET IDENTITY
           ------------------------------------------------- */

        source_id
            bigint
            NOT NULL,

        sport_code
            text
            NOT NULL,

        layer_type
            text
            NOT NULL,

        entity
            text
            NOT NULL,

        time_mode
            text
            NOT NULL,


        /* -------------------------------------------------
           EXACT DATA SCOPE
           ------------------------------------------------- */

        scope_type
            text
            NOT NULL,

        scope_key
            text
            NOT NULL,

        canonical_league_id
            integer
            NULL,

        canonical_season_id
            bigint
            NULL,

        source_competition_key
            text
            NULL,

        source_season_key
            text
            NULL,

        scope_from
            date
            NULL,

        scope_to
            date
            NULL,


        /* -------------------------------------------------
           OPTIONAL PROVENANCE LINKS
           ------------------------------------------------- */

        ingest_target_id
            bigint
            NULL,

        scope_coverage_id
            bigint
            NULL,

        audit_evidence_id
            bigint
            NULL,

        harvest_run_monitor_id
            bigint
            NULL,


        /* -------------------------------------------------
           COMPLETION COUNTERS
           ------------------------------------------------- */

        expected_count
            bigint
            NULL,

        source_observed_count
            bigint
            NULL,

        harvested_count
            bigint
            NULL,

        parsed_count
            bigint
            NULL,

        merged_count
            bigint
            NULL,

        rejected_count
            bigint
            NULL,


        /* -------------------------------------------------
           COMPLETION STATE
           ------------------------------------------------- */

        completion_status
            text
            NOT NULL,

        verification_status
            text
            NOT NULL
            DEFAULT 'UNVERIFIED',

        completed_at
            timestamptz
            NULL,

        verified_at
            timestamptz
            NULL,

        last_checked_at
            timestamptz
            NULL,


        /* -------------------------------------------------
           METADATA
           ------------------------------------------------- */

        notes
            text
            NULL,

        created_at
            timestamptz
            NOT NULL
            DEFAULT now(),

        updated_at
            timestamptz
            NOT NULL
            DEFAULT now(),


        /* =================================================
           FOREIGN KEYS
           ================================================= */

        CONSTRAINT fk_hsc_source
            FOREIGN KEY (source_id)
            REFERENCES ops.source_master
                (source_id),

        CONSTRAINT fk_hsc_sport
            FOREIGN KEY (sport_code)
            REFERENCES public.sports
                (code),

        CONSTRAINT fk_hsc_league
            FOREIGN KEY (canonical_league_id)
            REFERENCES public.leagues
                (id),

        CONSTRAINT fk_hsc_season
            FOREIGN KEY (canonical_season_id)
            REFERENCES public.seasons
                (id),

        CONSTRAINT fk_hsc_ingest_target
            FOREIGN KEY (ingest_target_id)
            REFERENCES ops.ingest_targets
                (id)
            ON DELETE SET NULL,

        CONSTRAINT fk_hsc_scope_coverage
            FOREIGN KEY (scope_coverage_id)
            REFERENCES ops.source_entity_time_scope_coverage
                (scope_coverage_id)
            ON DELETE SET NULL,

        CONSTRAINT fk_hsc_audit_evidence
            FOREIGN KEY (audit_evidence_id)
            REFERENCES ops.source_audit_evidence
                (audit_evidence_id)
            ON DELETE SET NULL,

        CONSTRAINT fk_hsc_run_monitor
            FOREIGN KEY (harvest_run_monitor_id)
            REFERENCES ops.harvest_run_monitor
                (monitor_id)
            ON DELETE SET NULL,


        /* =================================================
           DATASET IDENTITY
           ================================================= */

        CONSTRAINT uq_hsc_dataset_scope
            UNIQUE
            (
                source_id,
                sport_code,
                layer_type,
                entity,
                time_mode,
                scope_key
            ),


        /* =================================================
           REQUIRED TEXT
           ================================================= */

        CONSTRAINT ck_hsc_required_text
            CHECK (
                btrim(sport_code) <> ''
                AND btrim(layer_type) <> ''
                AND btrim(entity) <> ''
                AND btrim(scope_type) <> ''
                AND btrim(scope_key) <> ''
            ),


        /* =================================================
           TIME MODE
           ================================================= */

        CONSTRAINT ck_hsc_time_mode
            CHECK (
                time_mode IN (
                    'HISTORY_FAN',
                    'HISTORY_PREDICTION',
                    'CURRENT',
                    'FUTURE',
                    'LIVE'
                )
            ),


        /* =================================================
           COMPLETION STATUS
           ================================================= */

        CONSTRAINT ck_hsc_completion_status
            CHECK (
                completion_status IN (
                    'UNKNOWN',
                    'NOT_STARTED',
                    'IN_PROGRESS',
                    'PARTIAL',
                    'COMPLETE',
                    'COMPLETE_WITH_EXCEPTIONS',
                    'BLOCKED',
                    'FAILED'
                )
            ),


        /* =================================================
           VERIFICATION STATUS
           ================================================= */

        CONSTRAINT ck_hsc_verification_status
            CHECK (
                verification_status IN (
                    'UNVERIFIED',
                    'COUNT_MATCH',
                    'RECONCILED',
                    'MISMATCH',
                    'NOT_APPLICABLE'
                )
            ),


        /* =================================================
           NONNEGATIVE COUNTERS
           ================================================= */

        CONSTRAINT ck_hsc_nonnegative_counts
            CHECK (
                COALESCE(expected_count, 0) >= 0
                AND COALESCE(source_observed_count, 0) >= 0
                AND COALESCE(harvested_count, 0) >= 0
                AND COALESCE(parsed_count, 0) >= 0
                AND COALESCE(merged_count, 0) >= 0
                AND COALESCE(rejected_count, 0) >= 0
            ),


        /* =================================================
           DATE RANGE
           ================================================= */

        CONSTRAINT ck_hsc_date_range
            CHECK (
                scope_from IS NULL
                OR scope_to IS NULL
                OR scope_from <= scope_to
            ),


        /* =================================================
           COMPETITION SEASON CONTRACT
           ================================================= */

        CONSTRAINT ck_hsc_competition_season
            CHECK (
                scope_type <> 'COMPETITION_SEASON'

                OR
                (
                    canonical_league_id IS NOT NULL

                    AND
                    (
                        canonical_season_id IS NOT NULL

                        OR
                        (
                            source_season_key IS NOT NULL
                            AND btrim(source_season_key) <> ''
                        )
                    )
                )
            ),


        /* =================================================
           COMPLETE CONTRACT
           ================================================= */

        CONSTRAINT ck_hsc_complete_contract
            CHECK (
                completion_status <> 'COMPLETE'

                OR
                (
                    expected_count IS NOT NULL
                    AND source_observed_count IS NOT NULL
                    AND merged_count IS NOT NULL

                    AND expected_count
                        = source_observed_count

                    AND source_observed_count
                        = merged_count

                    AND verification_status IN (
                        'COUNT_MATCH',
                        'RECONCILED'
                    )

                    AND completed_at IS NOT NULL
                )
            ),


        /* =================================================
           NOT_STARTED CONTRACT
           ================================================= */

        CONSTRAINT ck_hsc_not_started_contract
            CHECK (
                completion_status <> 'NOT_STARTED'

                OR
                (
                    COALESCE(harvested_count, 0) = 0
                    AND COALESCE(parsed_count, 0) = 0
                    AND COALESCE(merged_count, 0) = 0
                    AND completed_at IS NULL
                )
            )
    );


    /* =====================================================
       4. INDEXY
       ===================================================== */

    CREATE INDEX ix_hsc_source_scope
        ON ops.harvest_scope_completion
        (
            source_id,
            sport_code,
            layer_type,
            entity,
            time_mode
        );

    CREATE INDEX ix_hsc_ingest_target
        ON ops.harvest_scope_completion
        (ingest_target_id);

    CREATE INDEX ix_hsc_scope_coverage
        ON ops.harvest_scope_completion
        (scope_coverage_id);

    CREATE INDEX ix_hsc_audit_evidence
        ON ops.harvest_scope_completion
        (audit_evidence_id);

    CREATE INDEX ix_hsc_completion_status
        ON ops.harvest_scope_completion
        (completion_status);

    CREATE INDEX ix_hsc_verification_status
        ON ops.harvest_scope_completion
        (verification_status);

    CREATE INDEX ix_hsc_league
        ON ops.harvest_scope_completion
        (canonical_league_id);


    /* =====================================================
       5. COMMENTS / SEMANTICS
       ===================================================== */

    COMMENT ON TABLE ops.harvest_scope_completion IS
        'Canonical exact dataset completion memory. '
        'Eviduje, zda konkrétní source/sport/layer/entity/time_mode/'
        'competition/season scope byl skutečně získán a ověřen. '
        'Není Source Coverage, Routing, Refresh Policy ani run telemetry.';


    COMMENT ON COLUMN
        ops.harvest_scope_completion.completion_status IS
        'Stav skutečného získání konkrétního dataset scope. '
        'PARTIAL znamená data existují, ale completeness zatím není prokázána.';


    COMMENT ON COLUMN
        ops.harvest_scope_completion.verification_status IS
        'Způsob ověření completeness. RECONCILED znamená provider/source count versus final DB reconciliation.';


    COMMENT ON COLUMN
        ops.harvest_scope_completion.scope_coverage_id IS
        'Volitelný odkaz na exact Source Coverage evidence. '
        'Harvest Completion může existovat i bez potvrzené Source Coverage.';


    COMMENT ON COLUMN
        ops.harvest_scope_completion.ingest_target_id IS
        'Volitelný odkaz na provozní harvest target. '
        'Při odstranění targetu completion history zůstává zachována.';


    /* =====================================================
       6. INITIAL POPULATION – 211 × 2
       ===================================================== */

    WITH time_modes AS
    (
        SELECT *
        FROM (
            VALUES
                ('HISTORY_FAN'::text),
                ('HISTORY_PREDICTION'::text)
        ) AS x(time_mode)
    ),

    targets AS
    (
        SELECT
            t.id AS ingest_target_id,
            t.canonical_league_id,
            t.provider_league_id::text
                AS provider_league_id,
            t.season::text
                AS source_season,
            t.tier

        FROM ops.ingest_targets t

        WHERE t.provider = 'api_handball'
          AND t.sport_code = 'HB'
          AND t.season = '2024'
          AND t.enabled = true
    ),

    history AS
    (
        SELECT
            m.league_id AS canonical_league_id,
            m.season::text AS source_season,

            COUNT(DISTINCT m.id) AS matches,

            COUNT(DISTINCT m.id) FILTER (
                WHERE m.status = 'FINISHED'
            ) AS finished,

            COUNT(DISTINCT m.id) FILTER (
                WHERE m.status = 'FINISHED'
                  AND m.home_score IS NOT NULL
                  AND m.away_score IS NOT NULL
            ) AS finished_with_score,

            COUNT(DISTINCT m.id) FILTER (
                WHERE m.status = 'SCHEDULED'
            ) AS scheduled,

            COUNT(DISTINCT m.id) FILTER (
                WHERE m.status = 'CANCELLED'
            ) AS cancelled

        FROM public.matches m

        JOIN public.match_provider_map mpm
          ON mpm.match_id = m.id
         AND mpm.provider = 'api_handball'

        WHERE m.kickoff < CURRENT_DATE

        GROUP BY
            m.league_id,
            m.season::text
    ),

    exact AS
    (
        SELECT
            d.scope_coverage_id,
            d.canonical_league_id,
            d.canonical_season_id,
            d.source_competition_key,
            d.source_season_key,
            d.scope_status,

            c.time_mode,

            d.audit_evidence_id,

            e.result_status AS evidence_result_status,
            e.evidence_date,
            e.result_detail::jsonb AS detail

        FROM ops.source_entity_time_scope_coverage d

        JOIN ops.source_entity_time_coverage c
          ON c.coverage_id = d.coverage_id

        LEFT JOIN ops.source_audit_evidence e
          ON e.audit_evidence_id =
             d.audit_evidence_id

        WHERE c.source_id = 18
          AND c.sport_code = 'HB'
          AND c.layer_type = 'CORE'
          AND c.entity = 'fixtures'

          AND c.time_mode IN (
              'HISTORY_FAN',
              'HISTORY_PREDICTION'
          )

          AND d.scope_status = 'CONFIRMED'
    ),

    universe AS
    (
        SELECT
            t.ingest_target_id,
            t.canonical_league_id,
            t.provider_league_id,
            t.source_season,

            tm.time_mode,

            h.matches,
            h.finished,
            h.finished_with_score,
            h.scheduled,
            h.cancelled,

            x.scope_coverage_id,
            x.canonical_season_id,
            x.audit_evidence_id,
            x.evidence_result_status,
            x.evidence_date,
            x.detail,

            CASE
                WHEN
                    x.scope_coverage_id IS NOT NULL

                    AND x.scope_status = 'CONFIRMED'

                    AND x.evidence_result_status = 'PASS'

                    AND COALESCE(
                        (x.detail ->>
                         'api_returned_matches')::bigint,
                        -1
                    ) > 0

                    AND
                    (x.detail ->>
                     'api_returned_matches')::bigint
                        =
                    (x.detail ->>
                     'db_expected_matches')::bigint

                    AND h.matches
                        =
                    (x.detail ->>
                     'db_expected_matches')::bigint

                    AND h.finished = h.matches

                    AND
                    h.finished_with_score = h.matches

                    AND h.scheduled = 0

                    AND h.cancelled = 0

                THEN true

                ELSE false
            END AS complete_ready

        FROM targets t

        CROSS JOIN time_modes tm

        LEFT JOIN history h
          ON h.canonical_league_id =
             t.canonical_league_id
         AND h.source_season =
             t.source_season

        LEFT JOIN exact x
          ON x.canonical_league_id =
             t.canonical_league_id

         AND x.source_competition_key =
             t.provider_league_id

         AND x.source_season_key =
             t.source_season

         AND x.time_mode =
             tm.time_mode
    ),

    classified AS
    (
        SELECT
            *,

            CASE
                WHEN complete_ready = true
                    THEN 'COMPLETE'

                WHEN matches IS NOT NULL
                    THEN 'PARTIAL'

                ELSE 'NOT_STARTED'
            END AS completion_status_calc

        FROM universe
    )

    INSERT INTO ops.harvest_scope_completion
    (
        source_id,
        sport_code,
        layer_type,
        entity,
        time_mode,

        scope_type,
        scope_key,

        canonical_league_id,
        canonical_season_id,

        source_competition_key,
        source_season_key,

        ingest_target_id,
        scope_coverage_id,
        audit_evidence_id,
        harvest_run_monitor_id,

        expected_count,
        source_observed_count,

        harvested_count,
        parsed_count,
        merged_count,
        rejected_count,

        completion_status,
        verification_status,

        completed_at,
        verified_at,
        last_checked_at,

        notes
    )

    SELECT
        18,
        'HB',
        'CORE',
        'fixtures',
        c.time_mode,

        'COMPETITION_SEASON',

        format(
            'league:%s|source_competition:%s|source_season:%s',
            c.canonical_league_id,
            c.provider_league_id,
            c.source_season
        ),

        c.canonical_league_id,
        c.canonical_season_id,

        c.provider_league_id,
        c.source_season,

        c.ingest_target_id,
        c.scope_coverage_id,
        c.audit_evidence_id,
        NULL,

        CASE
            WHEN c.complete_ready
            THEN
                (c.detail ->>
                 'db_expected_matches')::bigint
            ELSE NULL
        END,

        CASE
            WHEN c.complete_ready
            THEN
                (c.detail ->>
                 'api_returned_matches')::bigint
            ELSE NULL
        END,

        CASE
            WHEN c.completion_status_calc =
                 'NOT_STARTED'
            THEN 0
            ELSE NULL
        END,

        CASE
            WHEN c.completion_status_calc =
                 'NOT_STARTED'
            THEN 0
            ELSE NULL
        END,

        CASE
            WHEN c.matches IS NOT NULL
            THEN c.matches
            ELSE 0
        END,

        CASE
            WHEN c.completion_status_calc =
                 'NOT_STARTED'
            THEN 0
            ELSE NULL
        END,

        c.completion_status_calc,

        CASE
            WHEN c.complete_ready
            THEN 'RECONCILED'
            ELSE 'UNVERIFIED'
        END,

        CASE
            WHEN c.complete_ready
            THEN c.evidence_date
            ELSE NULL
        END,

        CASE
            WHEN c.complete_ready
            THEN c.evidence_date
            ELSE NULL
        END,

        CASE
            WHEN c.complete_ready
            THEN c.evidence_date
            ELSE NULL
        END,

        CASE
            WHEN c.complete_ready
            THEN
                'Initial STEP 10P population. '
                'Completeness proven by runtime provider '
                'reconciliation against final DB.'

            WHEN c.matches IS NOT NULL
            THEN
                'Initial STEP 10P population. '
                'Historical data exist in final DB, '
                'but provider completeness has not yet '
                'been runtime reconciled.'

            ELSE
                'Initial STEP 10P population. '
                'Enabled HB harvest target exists, '
                'but no historical api_handball data '
                'are currently stored.'
        END

    FROM classified c;


    GET DIAGNOSTICS v_inserted = ROW_COUNT;


    /* =====================================================
       7. ROW-LEVEL VALIDATION
       ===================================================== */

    SELECT COUNT(*)
    INTO v_complete_rows
    FROM ops.harvest_scope_completion
    WHERE completion_status = 'COMPLETE';


    SELECT COUNT(*)
    INTO v_partial_rows
    FROM ops.harvest_scope_completion
    WHERE completion_status = 'PARTIAL';


    SELECT COUNT(*)
    INTO v_not_started_rows
    FROM ops.harvest_scope_completion
    WHERE completion_status = 'NOT_STARTED';


    /* =====================================================
       8. TARGET-LEVEL VALIDATION
       ===================================================== */

    WITH target_status AS
    (
        SELECT
            ingest_target_id,

            CASE
                WHEN bool_and(
                    completion_status = 'COMPLETE'
                )
                    THEN 'COMPLETE'

                WHEN bool_and(
                    completion_status = 'NOT_STARTED'
                )
                    THEN 'NOT_STARTED'

                ELSE 'PARTIAL'
            END AS target_status

        FROM ops.harvest_scope_completion

        GROUP BY ingest_target_id
    )

    SELECT
        COUNT(*) FILTER (
            WHERE target_status = 'COMPLETE'
        ),

        COUNT(*) FILTER (
            WHERE target_status = 'PARTIAL'
        ),

        COUNT(*) FILTER (
            WHERE target_status = 'NOT_STARTED'
        )

    INTO
        v_complete_targets,
        v_partial_targets,
        v_not_started_targets

    FROM target_status;


    /* =====================================================
       9. SAFETY VALIDATION
       ===================================================== */

    SELECT COUNT(*)
    INTO v_bad_complete
    FROM ops.harvest_scope_completion

    WHERE completion_status = 'COMPLETE'

      AND (
           expected_count IS NULL

        OR source_observed_count IS NULL

        OR merged_count IS NULL

        OR expected_count
           <> source_observed_count

        OR source_observed_count
           <> merged_count

        OR scope_coverage_id IS NULL

        OR audit_evidence_id IS NULL

        OR verification_status
           <> 'RECONCILED'

        OR completed_at IS NULL
      );


    SELECT COUNT(*)
    INTO v_bad_not_started
    FROM ops.harvest_scope_completion

    WHERE completion_status = 'NOT_STARTED'

      AND (
           COALESCE(harvested_count, 0) <> 0
        OR COALESCE(parsed_count, 0) <> 0
        OR COALESCE(merged_count, 0) <> 0
        OR completed_at IS NOT NULL
      );


    SELECT COUNT(*)
    INTO v_bad_total
    FROM ops.harvest_scope_completion

    WHERE completion_status NOT IN (
        'COMPLETE',
        'PARTIAL',
        'NOT_STARTED'
    );


    /* =====================================================
       10. GOVERNANCE GUARDS
       ===================================================== */

    SELECT COUNT(*)
    INTO v_parent_confirmed
    FROM ops.source_entity_time_coverage
    WHERE source_id = 18
      AND sport_code = 'HB'
      AND layer_type = 'CORE'
      AND entity = 'fixtures'
      AND coverage_status = 'CONFIRMED';


    SELECT COUNT(*)
    INTO v_active_bindings
    FROM ops.source_adapter_binding
    WHERE source_id = 18
      AND is_active = true;


    SELECT COUNT(*)
    INTO v_routes
    FROM ops.data_acquisition_source_routing
    WHERE source_id = 18;


    /* =====================================================
       11. FINAL ASSERTIONS
       ===================================================== */

    IF v_inserted <> 422

       OR v_complete_rows <> 12

       OR v_partial_rows <> 248

       OR v_not_started_rows <> 162

       OR v_complete_targets <> 6

       OR v_partial_targets <> 124

       OR v_not_started_targets <> 81

       OR v_bad_complete <> 0

       OR v_bad_not_started <> 0

       OR v_bad_total <> 0

       OR v_parent_confirmed <> 0

       OR v_active_bindings <> 0

       OR v_routes <> 0

    THEN

        RAISE EXCEPTION
            'STEP 10P VALIDATION FAIL: inserted=%, complete_rows=%, partial_rows=%, not_started_rows=%, complete_targets=%, partial_targets=%, not_started_targets=%, bad_complete=%, bad_not_started=%, bad_total=%, parent_confirmed=%, active_bindings=%, routes=%',
            v_inserted,
            v_complete_rows,
            v_partial_rows,
            v_not_started_rows,
            v_complete_targets,
            v_partial_targets,
            v_not_started_targets,
            v_bad_complete,
            v_bad_not_started,
            v_bad_total,
            v_parent_confirmed,
            v_active_bindings,
            v_routes;

    END IF;


    /* =====================================================
       12. RESULT
       ===================================================== */

    RAISE NOTICE
        'STEP_10P_TABLE=ops.harvest_scope_completion';

    RAISE NOTICE
        'STEP_10P_INSERTED=%',
        v_inserted;

    RAISE NOTICE
        'STEP_10P_COMPLETE_ROWS=%',
        v_complete_rows;

    RAISE NOTICE
        'STEP_10P_PARTIAL_ROWS=%',
        v_partial_rows;

    RAISE NOTICE
        'STEP_10P_NOT_STARTED_ROWS=%',
        v_not_started_rows;

    RAISE NOTICE
        'STEP_10P_COMPLETE_TARGETS=%',
        v_complete_targets;

    RAISE NOTICE
        'STEP_10P_PARTIAL_TARGETS=%',
        v_partial_targets;

    RAISE NOTICE
        'STEP_10P_NOT_STARTED_TARGETS=%',
        v_not_started_targets;

    RAISE NOTICE
        'STEP_10P_PARENT_CONFIRMED=%',
        v_parent_confirmed;

    RAISE NOTICE
        'STEP_10P_ACTIVE_BINDINGS=%',
        v_active_bindings;

    RAISE NOTICE
        'STEP_10P_ROUTES=%',
        v_routes;

    RAISE NOTICE
        'STEP_10P_STATUS=APPLY_PASS';

END
$$;