/*
CO:
STEP 9R – EXACT COVERAGE CHILD REGISTRY VALIDATE_ONLY

K ČEMU:
Ověřit fyzický kontrakt detailního Source Coverage registru.

ARCHITEKTONICKÝ PRINCIP:

PARENT:
source_id
× sport
× layer
× entity
× time_mode

CHILD:
přesný doložený scope
× canonical competition
× optional canonical season
× source competition key
× source season key
× evidence

DŮLEŽITÉ:
- canonical_season_id smí být NULL,
- source_season_key zachovává skutečný provider/source údaj,
- nejde o Harvest Completion Registry,
- nejde o Refresh Policy,
- nejde o Routing.

REŽIM:
VALIDATE_ONLY.
Po dokončení tabulka nesmí v DB zůstat.
*/

DO $$
DECLARE
    v_rows              integer;
    v_bad_parent        integer;
    v_bad_evidence      integer;
    v_bad_season        integer;
BEGIN

    /* =====================================================
       1. COLLISION GUARD
       ===================================================== */

    IF to_regclass(
        'ops.source_entity_time_scope_coverage'
    ) IS NOT NULL THEN

        RAISE EXCEPTION
            'STEP 9R BLOCKED: ops.source_entity_time_scope_coverage již existuje.';
    END IF;


    /* =====================================================
       2. CREATE VALIDATION TABLE
       ===================================================== */

    EXECUTE $DDL$

        CREATE TABLE ops.source_entity_time_scope_coverage
        (
            scope_coverage_id
                bigint
                GENERATED BY DEFAULT AS IDENTITY
                PRIMARY KEY,

            coverage_id
                bigint
                NOT NULL,

            scope_type
                text
                NOT NULL,

            scope_key
                text
                NOT NULL,

            canonical_league_id
                integer
                NULL,

            canonical_season_id
                bigint
                NULL,

            source_competition_key
                text
                NULL,

            source_season_key
                text
                NULL,

            scope_from
                date
                NULL,

            scope_to
                date
                NULL,

            scope_status
                text
                NOT NULL,

            audit_evidence_id
                bigint
                NOT NULL,

            tested_at
                timestamptz
                NULL,

            is_active
                boolean
                NOT NULL
                DEFAULT true,

            notes
                text
                NULL,

            created_at
                timestamptz
                NOT NULL
                DEFAULT now(),

            updated_at
                timestamptz
                NOT NULL
                DEFAULT now(),


            CONSTRAINT fk_setsc_coverage
                FOREIGN KEY (coverage_id)
                REFERENCES ops.source_entity_time_coverage
                    (coverage_id),

            CONSTRAINT fk_setsc_league
                FOREIGN KEY (canonical_league_id)
                REFERENCES public.leagues
                    (id),

            CONSTRAINT fk_setsc_season
                FOREIGN KEY (canonical_season_id)
                REFERENCES public.seasons
                    (id),

            CONSTRAINT fk_setsc_evidence
                FOREIGN KEY (audit_evidence_id)
                REFERENCES ops.source_audit_evidence
                    (audit_evidence_id),


            CONSTRAINT uq_setsc_parent_scope
                UNIQUE
                (
                    coverage_id,
                    scope_key
                ),


            CONSTRAINT ck_setsc_scope_type_nonempty
                CHECK (
                    btrim(scope_type) <> ''
                ),

            CONSTRAINT ck_setsc_scope_key_nonempty
                CHECK (
                    btrim(scope_key) <> ''
                ),

            CONSTRAINT ck_setsc_status
                CHECK (
                    scope_status IN (
                        'UNKNOWN',
                        'PLANNED',
                        'TECH_READY',
                        'RUNTIME_TESTED',
                        'CONFIRMED',
                        'BLOCKED'
                    )
                ),

            CONSTRAINT ck_setsc_date_range
                CHECK (
                    scope_from IS NULL
                    OR scope_to IS NULL
                    OR scope_from <= scope_to
                ),

            /*
            Pro COMPETITION_SEASON musí existovat:
            - canonical liga
            - source season key

            Canonical season_id zatím povinný NENÍ.
            */
            CONSTRAINT ck_setsc_competition_season
                CHECK (
                    scope_type <> 'COMPETITION_SEASON'
                    OR (
                        canonical_league_id IS NOT NULL
                        AND source_season_key IS NOT NULL
                        AND btrim(source_season_key) <> ''
                    )
                )
        )

    $DDL$;


    /* =====================================================
       3. INDEXY
       ===================================================== */

    EXECUTE '
        CREATE INDEX ix_setsc_coverage
        ON ops.source_entity_time_scope_coverage
        (coverage_id)
    ';

    EXECUTE '
        CREATE INDEX ix_setsc_league
        ON ops.source_entity_time_scope_coverage
        (canonical_league_id)
    ';

    EXECUTE '
        CREATE INDEX ix_setsc_season
        ON ops.source_entity_time_scope_coverage
        (canonical_season_id)
    ';

    EXECUTE '
        CREATE INDEX ix_setsc_evidence
        ON ops.source_entity_time_scope_coverage
        (audit_evidence_id)
    ';


    /* =====================================================
       4. VALIDATION INSERT – HISTORY_FAN
       ===================================================== */

    INSERT INTO ops.source_entity_time_scope_coverage
    (
        coverage_id,
        scope_type,
        scope_key,
        canonical_league_id,
        canonical_season_id,
        source_competition_key,
        source_season_key,
        scope_status,
        audit_evidence_id,
        tested_at,
        notes
    )
    VALUES
    (
        1,

        'COMPETITION_SEASON',

        'league:24881|source_competition:131|season:2024',

        24881,

        NULL,

        '131',

        '2024',

        'RUNTIME_TESTED',

        58,

        TIMESTAMPTZ '2026-09-29 09:57:36.098+02',

        'STEP 9G runtime evidence. '
        'API-Sports HB league 131 season 2024; '
        '132 API results and 132 verified DB matches. '
        'Canonical season_id intentionally unresolved.'
    );


    /* =====================================================
       5. VALIDATION INSERT – HISTORY_PREDICTION
       ===================================================== */

    INSERT INTO ops.source_entity_time_scope_coverage
    (
        coverage_id,
        scope_type,
        scope_key,
        canonical_league_id,
        canonical_season_id,
        source_competition_key,
        source_season_key,
        scope_status,
        audit_evidence_id,
        tested_at,
        notes
    )
    VALUES
    (
        2,

        'COMPETITION_SEASON',

        'league:24881|source_competition:131|season:2024',

        24881,

        NULL,

        '131',

        '2024',

        'RUNTIME_TESTED',

        58,

        TIMESTAMPTZ '2026-09-29 09:57:36.098+02',

        'STEP 9G runtime evidence. '
        'Historical fixtures scope validated for model-oriented use. '
        'Canonical season_id intentionally unresolved.'
    );


    /* =====================================================
       6. VALIDACE
       ===================================================== */

    SELECT COUNT(*)
    INTO v_rows
    FROM ops.source_entity_time_scope_coverage;


    SELECT COUNT(*)
    INTO v_bad_parent
    FROM ops.source_entity_time_scope_coverage d
    LEFT JOIN ops.source_entity_time_coverage p
      ON p.coverage_id = d.coverage_id
    WHERE p.coverage_id IS NULL;


    SELECT COUNT(*)
    INTO v_bad_evidence
    FROM ops.source_entity_time_scope_coverage d
    LEFT JOIN ops.source_audit_evidence e
      ON e.audit_evidence_id = d.audit_evidence_id
    WHERE e.audit_evidence_id IS NULL;


    SELECT COUNT(*)
    INTO v_bad_season
    FROM ops.source_entity_time_scope_coverage
    WHERE scope_type = 'COMPETITION_SEASON'
      AND (
           canonical_league_id IS NULL
           OR source_season_key IS NULL
           OR btrim(source_season_key) = ''
      );


    IF v_rows <> 2
       OR v_bad_parent <> 0
       OR v_bad_evidence <> 0
       OR v_bad_season <> 0
    THEN

        RAISE EXCEPTION
            'STEP 9R VALIDATION FAIL: rows=%, bad_parent=%, bad_evidence=%, bad_season=%',
            v_rows,
            v_bad_parent,
            v_bad_evidence,
            v_bad_season;

    END IF;


    RAISE NOTICE
        'STEP_9R_ROWS=%',
        v_rows;

    RAISE NOTICE
        'STEP_9R_SCOPE=HB/CORE/fixtures/league_24881/source_league_131/season_2024';

    RAISE NOTICE
        'STEP_9R_CANONICAL_SEASON=NULL_ALLOWED_AND_VALID';

    RAISE NOTICE
        'STEP_9R_VALIDATE bad_parent=%, bad_evidence=%, bad_season=%',
        v_bad_parent,
        v_bad_evidence,
        v_bad_season;


    /* =====================================================
       7. CLEANUP – VALIDATE ONLY
       ===================================================== */

    EXECUTE '
        DROP TABLE ops.source_entity_time_scope_coverage
    ';


    IF to_regclass(
        'ops.source_entity_time_scope_coverage'
    ) IS NOT NULL THEN

        RAISE EXCEPTION
            'STEP 9R CLEANUP FAIL: validation table zůstala v DB.';

    END IF;


    RAISE NOTICE
        'STEP_9R_CLEANUP=OK';

    RAISE NOTICE
        'STEP_9R_STATUS=VALIDATE_ONLY_PASS';

END
$$;