-- 99_playground / ODDS RUNTIME AUDIT SEED
-- Účel: doplnit chybějící odds řádky do ops.runtime_entity_audit.
-- Neprovádí žádné stahování. Pouze auditní příprava pro placený API-Sport plán.

INSERT INTO ops.runtime_entity_audit (
    provider,
    sport_code,
    entity,
    current_state,
    state_reason,
    panel_runner_exists,
    planner_target_exists,
    batch_target_exists,
    pull_confirmed,
    raw_confirmed,
    staging_confirmed,
    provider_map_confirmed,
    public_merge_confirmed,
    downstream_confirmed,
    last_run_group,
    last_check_at,
    db_evidence_summary,
    next_action,
    audit_note,
    created_at,
    updated_at
)
VALUES
    ('api_football', 'FB', 'odds', 'PLANNED',
     'Odds vrstva je plánovaná pro paid/API-Sport režim. Před harvestem je nutný smoke test endpointu a napojení na public.matches.',
     true, true, true,
     false, false, false, false, false, false,
     'FB_ODDS_CORE',
     now(),
     'No confirmed runtime odds row yet in runtime_entity_audit.',
     'Po aktivaci PRO/paid plánu ověřit odds endpoint smoke testem pro vybrané FB matches.',
     'Seeded as planned odds audit row. No data pull executed.',
     now(), now()),

    ('api_hockey', 'HK', 'odds', 'PLANNED',
     'Odds vrstva je plánovaná pro paid/API-Sport režim. Před harvestem je nutný smoke test endpointu a napojení na public.matches.',
     true, true, true,
     false, false, false, false, false, false,
     'HK_ODDS_CORE',
     now(),
     'No confirmed runtime odds row yet in runtime_entity_audit.',
     'Po aktivaci PRO/paid plánu ověřit odds endpoint smoke testem pro HK.',
     'Seeded as planned odds audit row. No data pull executed.',
     now(), now()),

    ('api_sport', 'BK', 'odds', 'PLANNED',
     'Odds vrstva je plánovaná pro paid/API-Sport režim. Před harvestem je nutný smoke test endpointu a napojení na public.matches.',
     true, true, true,
     false, false, false, false, false, false,
     'BK_ODDS_CORE',
     now(),
     'No confirmed runtime odds row yet in runtime_entity_audit.',
     'Po aktivaci PRO/paid plánu ověřit odds endpoint smoke testem pro BK.',
     'Seeded as planned odds audit row. No data pull executed.',
     now(), now()),

    ('api_handball', 'HB', 'odds', 'PLANNED',
     'Odds vrstva je plánovaná pro paid/API-Sport režim. Před harvestem je nutný smoke test endpointu a napojení na public.matches.',
     true, true, true,
     false, false, false, false, false, false,
     'HB_ODDS_CORE',
     now(),
     'No confirmed runtime odds row yet in runtime_entity_audit.',
     'Po aktivaci PRO/paid plánu ověřit odds endpoint smoke testem pro HB.',
     'Seeded as planned odds audit row. No data pull executed.',
     now(), now()),

    ('api_baseball', 'BSB', 'odds', 'PLANNED',
     'Odds vrstva je plánovaná pro paid/API-Sport režim. Před harvestem je nutný smoke test endpointu a napojení na public.matches.',
     true, true, true,
     false, false, false, false, false, false,
     'BSB_ODDS_CORE',
     now(),
     'No confirmed runtime odds row yet in runtime_entity_audit.',
     'Po aktivaci PRO/paid plánu ověřit odds endpoint smoke testem pro BSB.',
     'Seeded as planned odds audit row. No data pull executed.',
     now(), now()),

    ('api_rugby', 'RGB', 'odds', 'PLANNED',
     'Odds vrstva je plánovaná pro paid/API-Sport režim. Před harvestem je nutný smoke test endpointu a napojení na public.matches.',
     true, true, true,
     false, false, false, false, false, false,
     'RGB_ODDS_CORE',
     now(),
     'No confirmed runtime odds row yet in runtime_entity_audit.',
     'Po aktivaci PRO/paid plánu ověřit odds endpoint smoke testem pro RGB.',
     'Seeded as planned odds audit row. No data pull executed.',
     now(), now()),

    ('api_cricket', 'CK', 'odds', 'PLANNED',
     'Odds vrstva je plánovaná pro paid/API-Sport režim. Před harvestem je nutný smoke test endpointu a napojení na public.matches.',
     true, true, true,
     false, false, false, false, false, false,
     'CK_ODDS_CORE',
     now(),
     'No confirmed runtime odds row yet in runtime_entity_audit.',
     'Po aktivaci PRO/paid plánu ověřit odds endpoint smoke testem pro CK.',
     'Seeded as planned odds audit row. No data pull executed.',
     now(), now()),

    ('api_american_football', 'AFB', 'odds', 'PLANNED',
     'Odds vrstva je plánovaná pro paid/API-Sport režim. Před harvestem je nutný smoke test endpointu a napojení na public.matches.',
     true, true, true,
     false, false, false, false, false, false,
     'AFB_ODDS_CORE',
     now(),
     'No confirmed runtime odds row yet in runtime_entity_audit.',
     'Po aktivaci PRO/paid plánu ověřit odds endpoint smoke testem pro AFB.',
     'Seeded as planned odds audit row. No data pull executed.',
     now(), now())
ON CONFLICT DO NOTHING;