-- ============================================================
-- 886_seed_provider_people_audit_v1.sql
-- MatchMatrix - Provider People Audit Matrix
--
-- Kam uložit:
-- C:\MatchMatrix-platform\db\audit\886_seed_provider_people_audit_v1.sql
--
-- Spustit v DBeaveru.
--
-- Účel:
-- - připraví řízení hráčů/trenérů pro další sporty
-- - nic nespouští
-- - jen říká, kde je people layer READY / PLANNED / WAIT_PROVIDER / BLOCKED
-- ============================================================

BEGIN;

INSERT INTO ops.provider_people_audit
(
    provider,
    sport_code,
    entity,
    provider_role,
    source_category,
    endpoint_name,
    endpoint_exists,
    endpoint_tested,
    endpoint_returns_data,
    usable_for_league,
    usable_for_team,
    usable_for_season,
    technical_status,
    data_quality_status,
    final_verdict,
    requires_pro,
    alternative_provider_needed,
    evidence_note,
    next_step,
    priority_rank,
    created_at,
    updated_at
)
VALUES
-- ============================================================
-- FOOTBALL / FB
-- ============================================================
(
    'api_football',
    'FB',
    'players',
    'primary',
    'provider_api',
    '/players',
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    'READY',
    'FREE_LIMITED',
    'RUNNABLE',
    FALSE,
    FALSE,
    'FB players pipeline confirmed. Free plan limited to first pages; PRO unlocks scale.',
    'Napojit automatické seedování dalších league/season jobů do ops.ingest_planner.',
    10,
    NOW(),
    NOW()
),
(
    'api_football',
    'FB',
    'player_season_stats',
    'primary',
    'provider_api',
    '/players statistics[]',
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    'READY',
    'FREE_LIMITED',
    'RUNNABLE',
    FALSE,
    FALSE,
    'Parser confirmed into staging.stg_provider_player_season_stats.',
    'Doplnit pravidelný parse/merge po každém players fetch běhu.',
    20,
    NOW(),
    NOW()
),
(
    'api_football',
    'FB',
    'coaches',
    'primary',
    'provider_api',
    '/coachs',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    TRUE,
    FALSE,
    'PLANNED',
    'UNKNOWN',
    'WAIT_TEST',
    FALSE,
    FALSE,
    'FB coaches jsou zatím plánovaní, ne potvrzení ostrým během.',
    'Ověřit endpoint reálným během a doplnit parser/merge.',
    60,
    NOW(),
    NOW()
),

-- ============================================================
-- HOCKEY / HK
-- ============================================================
(
    'api_hockey',
    'HK',
    'players',
    'primary',
    'provider_api',
    '/players',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    'BLOCKED',
    'UNKNOWN',
    'WAIT_PROVIDER',
    FALSE,
    TRUE,
    'HK players jsou podle auditu problematické / blocked.',
    'Najít vhodný provider pro hockey players.',
    100,
    NOW(),
    NOW()
),
(
    'api_hockey',
    'HK',
    'coaches',
    'primary',
    'provider_api',
    '/coachs',
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    TRUE,
    FALSE,
    'PLANNED',
    'UNKNOWN',
    'WAIT_TEST',
    FALSE,
    FALSE,
    'HK coaches jsou kandidát pro další people rozšíření.',
    'Otestovat endpoint, připravit pull/parser/merge.',
    80,
    NOW(),
    NOW()
),

-- ============================================================
-- BASKETBALL / BK
-- ============================================================
(
    'api_sport',
    'BK',
    'players',
    'primary',
    'provider_api',
    '/players',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    'PLANNED',
    'UNKNOWN',
    'WAIT_PROVIDER',
    FALSE,
    TRUE,
    'BK core skeleton je potvrzený, players vrstva zatím bez runtime workeru.',
    'Prověřit dostupnost players endpointu a rozhodnout primary provider.',
    120,
    NOW(),
    NOW()
),
(
    'api_sport',
    'BK',
    'coaches',
    'primary',
    'provider_api',
    '/coaches',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    'PLANNED',
    'UNKNOWN',
    'WAIT_PROVIDER',
    FALSE,
    TRUE,
    'BK coaches zatím bez runtime workeru.',
    'Prověřit provider dostupnost.',
    130,
    NOW(),
    NOW()
),

-- ============================================================
-- VOLLEYBALL / VB
-- ============================================================
(
    'api_volleyball',
    'VB',
    'players',
    'primary',
    'provider_api',
    '/players',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    'PLANNED',
    'UNKNOWN',
    'WAIT_PROVIDER',
    FALSE,
    TRUE,
    'VB core pipeline potvrzená, players zatím placeholder.',
    'Najít/ověřit provider endpoint pro players.',
    140,
    NOW(),
    NOW()
),
(
    'api_volleyball',
    'VB',
    'coaches',
    'primary',
    'provider_api',
    '/coachs',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    'PLANNED',
    'UNKNOWN',
    'WAIT_PROVIDER',
    FALSE,
    TRUE,
    'VB coaches zatím placeholder.',
    'Najít/ověřit provider endpoint pro coaches.',
    150,
    NOW(),
    NOW()
),

-- ============================================================
-- HANDBALL / HB
-- ============================================================
(
    'api_handball',
    'HB',
    'players',
    'primary',
    'provider_api',
    '/players',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    'PLANNED',
    'UNKNOWN',
    'WAIT_PROVIDER',
    FALSE,
    TRUE,
    'HB core pipeline potvrzená, players zatím placeholder.',
    'Najít/ověřit provider endpoint pro HB players.',
    160,
    NOW(),
    NOW()
),
(
    'api_handball',
    'HB',
    'coaches',
    'primary',
    'provider_api',
    '/coachs',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    'PLANNED',
    'UNKNOWN',
    'WAIT_PROVIDER',
    FALSE,
    TRUE,
    'HB coaches zatím placeholder.',
    'Najít/ověřit provider endpoint pro HB coaches.',
    170,
    NOW(),
    NOW()
),

-- ============================================================
-- BASEBALL / BSB
-- ============================================================
(
    'api_baseball',
    'BSB',
    'players',
    'primary',
    'provider_api',
    '/players',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    'PLANNED',
    'UNKNOWN',
    'WAIT_PROVIDER',
    FALSE,
    TRUE,
    'BSB core pipeline potvrzená, players zatím placeholder.',
    'Najít/ověřit provider endpoint pro baseball players.',
    180,
    NOW(),
    NOW()
),
(
    'api_baseball',
    'BSB',
    'coaches',
    'primary',
    'provider_api',
    '/coachs',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    'PLANNED',
    'UNKNOWN',
    'WAIT_PROVIDER',
    FALSE,
    TRUE,
    'BSB coaches zatím placeholder.',
    'Najít/ověřit provider endpoint pro baseball coaches.',
    190,
    NOW(),
    NOW()
),

-- ============================================================
-- RUGBY / RGB
-- ============================================================
(
    'api_rugby',
    'RGB',
    'players',
    'primary',
    'provider_api',
    '/players',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    'PLANNED',
    'UNKNOWN',
    'WAIT_PROVIDER',
    FALSE,
    TRUE,
    'RGB core pipeline potvrzená, players zatím placeholder.',
    'Najít/ověřit provider endpoint pro rugby players.',
    200,
    NOW(),
    NOW()
),
(
    'api_rugby',
    'RGB',
    'coaches',
    'primary',
    'provider_api',
    '/coachs',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    'PLANNED',
    'UNKNOWN',
    'WAIT_PROVIDER',
    FALSE,
    TRUE,
    'RGB coaches zatím placeholder.',
    'Najít/ověřit provider endpoint pro rugby coaches.',
    210,
    NOW(),
    NOW()
),

-- ============================================================
-- CRICKET / CK
-- ============================================================
(
    'api_cricket',
    'CK',
    'players',
    'primary',
    'provider_api',
    '/players',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    'PLANNED',
    'UNKNOWN',
    'WAIT_PROVIDER',
    FALSE,
    TRUE,
    'CK core pipeline potvrzená, players zatím placeholder.',
    'Najít/ověřit provider endpoint pro cricket players.',
    220,
    NOW(),
    NOW()
),
(
    'api_cricket',
    'CK',
    'coaches',
    'primary',
    'provider_api',
    '/coachs',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    'PLANNED',
    'UNKNOWN',
    'WAIT_PROVIDER',
    FALSE,
    TRUE,
    'CK coaches zatím placeholder.',
    'Najít/ověřit provider endpoint pro cricket coaches.',
    230,
    NOW(),
    NOW()
),

-- ============================================================
-- AMERICAN FOOTBALL / AFB
-- ============================================================
(
    'api_american_football',
    'AFB',
    'players',
    'primary',
    'provider_api',
    '/players',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    'PLANNED',
    'UNKNOWN',
    'WAIT_PROVIDER',
    FALSE,
    TRUE,
    'AFB core pipeline potvrzená, players zatím placeholder.',
    'Najít/ověřit provider endpoint pro American Football players.',
    240,
    NOW(),
    NOW()
),
(
    'api_american_football',
    'AFB',
    'coaches',
    'primary',
    'provider_api',
    '/coachs',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    'PLANNED',
    'UNKNOWN',
    'WAIT_PROVIDER',
    FALSE,
    TRUE,
    'AFB coaches zatím placeholder.',
    'Najít/ověřit provider endpoint pro American Football coaches.',
    250,
    NOW(),
    NOW()
),

-- ============================================================
-- FUTURE / PLACEHOLDERS
-- ============================================================
(
    'api_tennis',
    'TN',
    'players',
    'candidate',
    'provider_api',
    '/players',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    'PLANNED',
    'UNKNOWN',
    'WAIT_PROVIDER',
    TRUE,
    TRUE,
    'TN players budou řešeni až po ověření vhodného tenisového provideru.',
    'Ověřit RapidAPI tennis player endpoint a schéma.',
    300,
    NOW(),
    NOW()
),
(
    'api_mma',
    'MMA',
    'players',
    'candidate',
    'provider_api',
    '/fighters',
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    'PLANNED',
    'UNKNOWN',
    'WAIT_PROVIDER',
    TRUE,
    TRUE,
    'MMA fighters placeholder.',
    'Ověřit provider pro fighters.',
    310,
    NOW(),
    NOW()
)

ON CONFLICT (provider, sport_code, entity)
DO UPDATE SET
    provider_role = EXCLUDED.provider_role,
    source_category = EXCLUDED.source_category,
    endpoint_name = EXCLUDED.endpoint_name,
    endpoint_exists = EXCLUDED.endpoint_exists,
    endpoint_tested = EXCLUDED.endpoint_tested,
    endpoint_returns_data = EXCLUDED.endpoint_returns_data,
    usable_for_league = EXCLUDED.usable_for_league,
    usable_for_team = EXCLUDED.usable_for_team,
    usable_for_season = EXCLUDED.usable_for_season,
    technical_status = EXCLUDED.technical_status,
    data_quality_status = EXCLUDED.data_quality_status,
    final_verdict = EXCLUDED.final_verdict,
    requires_pro = EXCLUDED.requires_pro,
    alternative_provider_needed = EXCLUDED.alternative_provider_needed,
    evidence_note = EXCLUDED.evidence_note,
    next_step = EXCLUDED.next_step,
    priority_rank = EXCLUDED.priority_rank,
    updated_at = NOW();

COMMIT;

SELECT
    provider,
    sport_code,
    entity,
    provider_role,
    endpoint_exists,
    endpoint_tested,
    endpoint_returns_data,
    technical_status,
    final_verdict,
    requires_pro,
    alternative_provider_needed,
    priority_rank,
    next_step
FROM ops.provider_people_audit
ORDER BY priority_rank, sport_code, provider, entity;