/*
===============================================================================
MATCHMATRIX – MATCH PROVIDER IDENTITY
APPLY – TARGET TABLE DESIGN V1
===============================================================================

CO:
- Trvale vytvoří public.match_provider_map.
- Vytvoří ochranná omezení, indexy, komentáře a auditní trigger.

K ČEMU:
- Jeden kanonický zápas v public.matches může mít více externích identit.
- Zachování provenience při budoucím slučování providerových duplicit.
- Příprava belgické migrace Jupiler Pro League.

DŮLEŽITÉ:
- Skript nevkládá žádná data.
- Skript nemění public.matches.
- Skript nemění downstream vazby.
- Skript nemaže ani neslučuje zápasy.

REŽIM:
- APPLY
- TRANSACTIONAL DDL
===============================================================================
*/

BEGIN;

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '120s';
SET LOCAL client_min_messages = 'notice';

-------------------------------------------------------------------------------
-- 1. IDENTIFIKACE PROSTŘEDÍ
-------------------------------------------------------------------------------

SELECT
    current_database() AS database_name,
    current_user AS database_user,
    current_setting('transaction_isolation') AS transaction_isolation,
    current_setting('transaction_read_only') AS transaction_read_only,
    clock_timestamp() AS apply_started_at;

-------------------------------------------------------------------------------
-- 2. POVINNÉ PŘEDBĚŽNÉ KONTROLY
-------------------------------------------------------------------------------

DO $precheck$
DECLARE
    v_match_id_type text;
BEGIN
    IF to_regclass('public.matches') IS NULL THEN
        RAISE EXCEPTION
            'APPLY_FAILED: Tabulka public.matches neexistuje.';
    END IF;

    IF to_regclass('public.match_provider_map') IS NOT NULL THEN
        RAISE EXCEPTION
            'APPLY_FAILED: Tabulka public.match_provider_map již existuje.';
    END IF;

    IF to_regprocedure(
        'public.fn_match_provider_map_touch()'
    ) IS NOT NULL THEN
        RAISE EXCEPTION
            'APPLY_FAILED: Funkce public.fn_match_provider_map_touch již existuje.';
    END IF;

    SELECT format_type(a.atttypid, a.atttypmod)
    INTO v_match_id_type
    FROM pg_attribute a
    WHERE a.attrelid = 'public.matches'::regclass
      AND a.attname = 'id'
      AND a.attnum > 0
      AND NOT a.attisdropped;

    IF v_match_id_type IS NULL THEN
        RAISE EXCEPTION
            'APPLY_FAILED: Sloupec public.matches.id nebyl nalezen.';
    END IF;

    IF v_match_id_type <> 'integer' THEN
        RAISE EXCEPTION
            'APPLY_FAILED: Očekáván typ integer, nalezen typ %.',
            v_match_id_type;
    END IF;

    RAISE NOTICE
        'OK: public.matches.id používá potvrzený datový typ integer.';
END
$precheck$;

-------------------------------------------------------------------------------
-- 3. CÍLOVÁ TABULKA
-------------------------------------------------------------------------------

CREATE TABLE public.match_provider_map
(
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    match_id integer NOT NULL,

    provider text NOT NULL,
    provider_match_id text NOT NULL,

    identity_origin text NOT NULL DEFAULT 'PROVIDER',
    external_id_kind text NOT NULL DEFAULT 'NATIVE',

    mapping_status text NOT NULL DEFAULT 'ACTIVE',
    is_primary boolean NOT NULL DEFAULT false,

    confidence_score numeric(5,2) NOT NULL DEFAULT 100.00,

    source_record_hash text,

    first_seen_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    last_seen_at timestamptz NOT NULL DEFAULT clock_timestamp(),

    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,

    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),

    created_by text NOT NULL DEFAULT current_user,
    updated_by text NOT NULL DEFAULT current_user,

    CONSTRAINT pk_match_provider_map
        PRIMARY KEY (id),

    CONSTRAINT fk_match_provider_map_match
        FOREIGN KEY (match_id)
        REFERENCES public.matches(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT ck_mpm_provider_not_blank
        CHECK (length(btrim(provider)) > 0),

    CONSTRAINT ck_mpm_provider_match_id_not_blank
        CHECK (length(btrim(provider_match_id)) > 0),

    CONSTRAINT ck_mpm_identity_origin
        CHECK (
            identity_origin IN (
                'PROVIDER',
                'SOURCE',
                'ADAPTER',
                'INTERNAL'
            )
        ),

    CONSTRAINT ck_mpm_external_id_kind
        CHECK (
            external_id_kind IN (
                'NATIVE',
                'DERIVED',
                'HASH'
            )
        ),

    CONSTRAINT ck_mpm_mapping_status
        CHECK (
            mapping_status IN (
                'ACTIVE',
                'REVIEW',
                'HOLD',
                'SUPERSEDED',
                'REJECTED'
            )
        ),

    CONSTRAINT ck_mpm_primary_must_be_active
        CHECK (
            is_primary = false
            OR mapping_status = 'ACTIVE'
        ),

    CONSTRAINT ck_mpm_confidence_score
        CHECK (
            confidence_score >= 0.00
            AND confidence_score <= 100.00
        ),

    CONSTRAINT ck_mpm_seen_time_order
        CHECK (
            first_seen_at <= last_seen_at
        ),

    CONSTRAINT ck_mpm_source_record_hash
        CHECK (
            source_record_hash IS NULL
            OR source_record_hash ~ '^[0-9A-Fa-f]{64}$'
        ),

    CONSTRAINT ck_mpm_metadata_object
        CHECK (
            jsonb_typeof(metadata) = 'object'
        )
);

-------------------------------------------------------------------------------
-- 4. UNIKÁTNÍ PRAVIDLA A INDEXY
-------------------------------------------------------------------------------

CREATE UNIQUE INDEX uq_mpm_provider_identity
    ON public.match_provider_map (
        provider,
        provider_match_id
    );

CREATE UNIQUE INDEX uq_mpm_one_active_primary
    ON public.match_provider_map (match_id)
    WHERE is_primary = true
      AND mapping_status = 'ACTIVE';

CREATE UNIQUE INDEX uq_mpm_provider_source_hash
    ON public.match_provider_map (
        provider,
        source_record_hash
    )
    WHERE source_record_hash IS NOT NULL;

CREATE INDEX ix_mpm_match_id
    ON public.match_provider_map (match_id);

CREATE INDEX ix_mpm_mapping_status
    ON public.match_provider_map (
        mapping_status,
        provider
    );

-------------------------------------------------------------------------------
-- 5. AUDITNÍ FUNKCE
-------------------------------------------------------------------------------

CREATE FUNCTION public.fn_match_provider_map_touch()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at := clock_timestamp();
    NEW.updated_by := current_user;

    IF NEW.last_seen_at < OLD.last_seen_at THEN
        RAISE EXCEPTION
            'last_seen_at nesmí být starší než předchozí hodnota.';
    END IF;

    RETURN NEW;
END
$function$;

CREATE TRIGGER trg_match_provider_map_touch
BEFORE UPDATE
ON public.match_provider_map
FOR EACH ROW
EXECUTE FUNCTION public.fn_match_provider_map_touch();

-------------------------------------------------------------------------------
-- 6. DATABÁZOVÉ KOMENTÁŘE
-------------------------------------------------------------------------------

COMMENT ON TABLE public.match_provider_map IS
'Mapování více externích providerových nebo zdrojových identit na jeden kanonický zápas v public.matches.';

COMMENT ON COLUMN public.match_provider_map.id IS
'Interní identifikátor mapovacího záznamu.';

COMMENT ON COLUMN public.match_provider_map.match_id IS
'Kanonický identifikátor zápasu z public.matches.';

COMMENT ON COLUMN public.match_provider_map.provider IS
'Kanonický technický kód poskytovatele, zdroje nebo adaptéru. Providerový cizí klíč zatím není zaveden.';

COMMENT ON COLUMN public.match_provider_map.provider_match_id IS
'Externí identifikátor zápasu v rámci daného poskytovatele nebo zdroje.';

COMMENT ON COLUMN public.match_provider_map.identity_origin IS
'Význam původu identity: PROVIDER, SOURCE, ADAPTER nebo INTERNAL.';

COMMENT ON COLUMN public.match_provider_map.external_id_kind IS
'Způsob vzniku externího identifikátoru: NATIVE, DERIVED nebo HASH.';

COMMENT ON COLUMN public.match_provider_map.mapping_status IS
'Stav mapování: ACTIVE, REVIEW, HOLD, SUPERSEDED nebo REJECTED.';

COMMENT ON COLUMN public.match_provider_map.is_primary IS
'Označuje preferovanou aktivní externí identitu kanonického zápasu.';

COMMENT ON COLUMN public.match_provider_map.confidence_score IS
'Důvěryhodnost mapování v rozsahu 0 až 100.';

COMMENT ON COLUMN public.match_provider_map.source_record_hash IS
'Volitelný SHA-256 otisk původního zdrojového řádku nebo záznamu.';

COMMENT ON COLUMN public.match_provider_map.first_seen_at IS
'Čas prvního potvrzeného výskytu externí identity.';

COMMENT ON COLUMN public.match_provider_map.last_seen_at IS
'Čas posledního potvrzeného výskytu externí identity.';

COMMENT ON COLUMN public.match_provider_map.metadata IS
'Doplňující strukturovaná provenance a auditní metadata ve formátu JSON objektu.';

COMMENT ON COLUMN public.match_provider_map.created_at IS
'Čas vytvoření mapovacího záznamu.';

COMMENT ON COLUMN public.match_provider_map.updated_at IS
'Čas poslední změny mapovacího záznamu.';

COMMENT ON COLUMN public.match_provider_map.created_by IS
'Databázový uživatel, který mapovací záznam vytvořil.';

COMMENT ON COLUMN public.match_provider_map.updated_by IS
'Databázový uživatel, který mapovací záznam naposledy změnil.';

-------------------------------------------------------------------------------
-- 7. KONTROLA OBJEKTŮ PŘED COMMIT
-------------------------------------------------------------------------------

DO $verify$
DECLARE
    v_column_count integer;
    v_constraint_count integer;
    v_index_count integer;
    v_trigger_count integer;
    v_row_count bigint;
BEGIN
    IF to_regclass('public.match_provider_map') IS NULL THEN
        RAISE EXCEPTION
            'APPLY_FAILED: Tabulka nebyla vytvořena.';
    END IF;

    IF to_regprocedure(
        'public.fn_match_provider_map_touch()'
    ) IS NULL THEN
        RAISE EXCEPTION
            'APPLY_FAILED: Auditní funkce nebyla vytvořena.';
    END IF;

    SELECT COUNT(*)
    INTO v_column_count
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'match_provider_map';

    SELECT COUNT(*)
    INTO v_constraint_count
    FROM pg_constraint
    WHERE conrelid = 'public.match_provider_map'::regclass;

    SELECT COUNT(*)
    INTO v_index_count
    FROM pg_indexes
    WHERE schemaname = 'public'
      AND tablename = 'match_provider_map';

    SELECT COUNT(*)
    INTO v_trigger_count
    FROM pg_trigger
    WHERE tgrelid = 'public.match_provider_map'::regclass
      AND NOT tgisinternal;

    SELECT COUNT(*)
    INTO v_row_count
    FROM public.match_provider_map;

    IF v_column_count <> 17 THEN
        RAISE EXCEPTION
            'APPLY_FAILED: Očekáváno 17 sloupců, nalezeno %.',
            v_column_count;
    END IF;

    IF v_constraint_count <> 12 THEN
        RAISE EXCEPTION
            'APPLY_FAILED: Očekáváno 12 constraints, nalezeno %.',
            v_constraint_count;
    END IF;

    IF v_index_count <> 6 THEN
        RAISE EXCEPTION
            'APPLY_FAILED: Očekáváno 6 indexů, nalezeno %.',
            v_index_count;
    END IF;

    IF v_trigger_count <> 1 THEN
        RAISE EXCEPTION
            'APPLY_FAILED: Očekáván 1 trigger, nalezeno %.',
            v_trigger_count;
    END IF;

    IF v_row_count <> 0 THEN
        RAISE EXCEPTION
            'APPLY_FAILED: Nová tabulka není prázdná. Počet řádků: %.',
            v_row_count;
    END IF;

    RAISE NOTICE
        'OK: Tabulka vytvořena – sloupce %, constraints %, indexy %, triggery %, řádky %.',
        v_column_count,
        v_constraint_count,
        v_index_count,
        v_trigger_count,
        v_row_count;
END
$verify$;

-------------------------------------------------------------------------------
-- 8. TRVALÉ ULOŽENÍ
-------------------------------------------------------------------------------

COMMIT;

-------------------------------------------------------------------------------
-- 9. KONEČNÝ POST-COMMIT AUDIT
-------------------------------------------------------------------------------

SELECT
    CASE
        WHEN to_regclass('public.match_provider_map') IS NOT NULL
         AND to_regprocedure(
                'public.fn_match_provider_map_touch()'
             ) IS NOT NULL
        THEN 'APPLY_OK – MATCH_PROVIDER_MAP VYTVOŘENA'
        ELSE 'APPLY_FAILED – CÍLOVÉ OBJEKTY NEBYLY NALEZENY'
    END AS final_status;

SELECT
    COUNT(*) AS current_row_count
FROM public.match_provider_map;

SELECT
    c.ordinal_position,
    c.column_name,
    c.data_type,
    c.is_nullable,
    c.column_default
FROM information_schema.columns c
WHERE c.table_schema = 'public'
  AND c.table_name = 'match_provider_map'
ORDER BY c.ordinal_position;

SELECT
    indexname,
    indexdef
FROM pg_indexes
WHERE schemaname = 'public'
  AND tablename = 'match_provider_map'
ORDER BY indexname;