/*
===============================================================================
MATCHMATRIX – MATCH PROVIDER IDENTITY
VALIDATE ONLY – TARGET TABLE DESIGN V1
===============================================================================

CO:
- Návrh a transakční ověření public.match_provider_map.

K ČEMU:
- Jeden kanonický zápas v public.matches může mít více externích identit.
- Zachování provenience při budoucím slučování providerových duplicit.
- Příprava belgické migrace Jupiler Pro League.

BEZPEČNOST:
- Skript vytváří objekty pouze uvnitř explicitní transakce.
- Poslední příkaz transakce je ROLLBACK.
- Po úspěšném dokončení nezůstane v databázi žádná změna.

REŽIM:
- VALIDATE ONLY
- NO PERSISTENT DATABASE CHANGE
===============================================================================
*/

BEGIN;

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '120s';
SET LOCAL client_min_messages = 'notice';

-------------------------------------------------------------------------------
-- 1. IDENTIFIKACE PROSTŘEDÍ
-------------------------------------------------------------------------------

SELECT
    current_database() AS database_name,
    current_user AS database_user,
    current_setting('transaction_isolation') AS transaction_isolation,
    current_setting('transaction_read_only') AS transaction_read_only,
    clock_timestamp() AS validation_started_at;

-------------------------------------------------------------------------------
-- 2. POVINNÉ VSTUPNÍ KONTROLY
-------------------------------------------------------------------------------

DO $validation$
DECLARE
    v_match_id_type text;
BEGIN
    IF to_regclass('public.matches') IS NULL THEN
        RAISE EXCEPTION
            'VALIDATION_FAILED: Tabulka public.matches neexistuje.';
    END IF;

    IF to_regclass('public.match_provider_map') IS NOT NULL THEN
        RAISE EXCEPTION
            'VALIDATION_FAILED: Tabulka public.match_provider_map již existuje.';
    END IF;

    IF to_regprocedure(
        'public.fn_match_provider_map_touch()'
    ) IS NOT NULL THEN
        RAISE EXCEPTION
            'VALIDATION_FAILED: Funkce public.fn_match_provider_map_touch již existuje.';
    END IF;

    SELECT format_type(a.atttypid, a.atttypmod)
    INTO v_match_id_type
    FROM pg_attribute a
    WHERE a.attrelid = 'public.matches'::regclass
      AND a.attname = 'id'
      AND a.attnum > 0
      AND NOT a.attisdropped;

    IF v_match_id_type IS NULL THEN
        RAISE EXCEPTION
            'VALIDATION_FAILED: Sloupec public.matches.id nebyl nalezen.';
    END IF;

    RAISE NOTICE
        'OK: public.matches.id používá datový typ %.',
        v_match_id_type;
END
$validation$;

-------------------------------------------------------------------------------
-- 3. VYTVOŘENÍ CÍLOVÉ TABULKY PODLE SKUTEČNÉHO TYPU matches.id
-------------------------------------------------------------------------------

DO $create_table$
DECLARE
    v_match_id_type text;
BEGIN
    SELECT format_type(a.atttypid, a.atttypmod)
    INTO v_match_id_type
    FROM pg_attribute a
    WHERE a.attrelid = 'public.matches'::regclass
      AND a.attname = 'id'
      AND a.attnum > 0
      AND NOT a.attisdropped;

    EXECUTE format(
        $ddl$
        CREATE TABLE public.match_provider_map
        (
            id bigint GENERATED BY DEFAULT AS IDENTITY,

            match_id %s NOT NULL,

            provider text NOT NULL,
            provider_match_id text NOT NULL,

            identity_origin text NOT NULL DEFAULT 'PROVIDER',
            external_id_kind text NOT NULL DEFAULT 'NATIVE',

            mapping_status text NOT NULL DEFAULT 'ACTIVE',
            is_primary boolean NOT NULL DEFAULT false,

            confidence_score numeric(5,2) NOT NULL DEFAULT 100.00,

            source_record_hash text,

            first_seen_at timestamptz NOT NULL DEFAULT clock_timestamp(),
            last_seen_at timestamptz NOT NULL DEFAULT clock_timestamp(),

            metadata jsonb NOT NULL DEFAULT '{}'::jsonb,

            created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
            updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),

            created_by text NOT NULL DEFAULT current_user,
            updated_by text NOT NULL DEFAULT current_user,

            CONSTRAINT pk_match_provider_map
                PRIMARY KEY (id),

            CONSTRAINT fk_match_provider_map_match
                FOREIGN KEY (match_id)
                REFERENCES public.matches(id)
                ON UPDATE CASCADE
                ON DELETE RESTRICT,

            CONSTRAINT ck_mpm_provider_not_blank
                CHECK (length(btrim(provider)) > 0),

            CONSTRAINT ck_mpm_provider_match_id_not_blank
                CHECK (length(btrim(provider_match_id)) > 0),

            CONSTRAINT ck_mpm_identity_origin
                CHECK (
                    identity_origin IN (
                        'PROVIDER',
                        'SOURCE',
                        'ADAPTER',
                        'INTERNAL'
                    )
                ),

            CONSTRAINT ck_mpm_external_id_kind
                CHECK (
                    external_id_kind IN (
                        'NATIVE',
                        'DERIVED',
                        'HASH'
                    )
                ),

            CONSTRAINT ck_mpm_mapping_status
                CHECK (
                    mapping_status IN (
                        'ACTIVE',
                        'REVIEW',
                        'HOLD',
                        'SUPERSEDED',
                        'REJECTED'
                    )
                ),

            CONSTRAINT ck_mpm_primary_must_be_active
                CHECK (
                    is_primary = false
                    OR mapping_status = 'ACTIVE'
                ),

            CONSTRAINT ck_mpm_confidence_score
                CHECK (
                    confidence_score >= 0.00
                    AND confidence_score <= 100.00
                ),

            CONSTRAINT ck_mpm_seen_time_order
                CHECK (
                    first_seen_at <= last_seen_at
                ),

            CONSTRAINT ck_mpm_source_record_hash
                CHECK (
                    source_record_hash IS NULL
                    OR source_record_hash ~ '^[0-9A-Fa-f]{64}$'
                ),

            CONSTRAINT ck_mpm_metadata_object
                CHECK (
                    jsonb_typeof(metadata) = 'object'
                )
        )
        $ddl$,
        v_match_id_type
    );
END
$create_table$;

-------------------------------------------------------------------------------
-- 4. UNIKÁTNÍ PRAVIDLA A VYHLEDÁVACÍ INDEXY
-------------------------------------------------------------------------------

-- Jedna externí identita nesmí ukazovat na více kanonických zápasů.
CREATE UNIQUE INDEX uq_mpm_provider_identity
    ON public.match_provider_map (
        provider,
        provider_match_id
    );

-- Jeden kanonický zápas může mít nejvýše jednu aktivní primární identitu.
CREATE UNIQUE INDEX uq_mpm_one_active_primary
    ON public.match_provider_map (match_id)
    WHERE is_primary = true
      AND mapping_status = 'ACTIVE';

-- Jeden zdrojový řádek nesmí být přiřazen vícekrát.
CREATE UNIQUE INDEX uq_mpm_provider_source_hash
    ON public.match_provider_map (
        provider,
        source_record_hash
    )
    WHERE source_record_hash IS NOT NULL;

-- Rychlé načtení všech identit kanonického zápasu.
CREATE INDEX ix_mpm_match_id
    ON public.match_provider_map (match_id);

-- Kontrola položek čekajících na review nebo hold.
CREATE INDEX ix_mpm_mapping_status
    ON public.match_provider_map (
        mapping_status,
        provider
    );

-------------------------------------------------------------------------------
-- 5. AUTOMATICKÁ AKTUALIZACE AUDITNÍCH ÚDAJŮ
-------------------------------------------------------------------------------

CREATE FUNCTION public.fn_match_provider_map_touch()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at := clock_timestamp();
    NEW.updated_by := current_user;

    IF NEW.last_seen_at < OLD.last_seen_at THEN
        RAISE EXCEPTION
            'last_seen_at nesmí být starší než předchozí hodnota.';
    END IF;

    RETURN NEW;
END
$function$;

CREATE TRIGGER trg_match_provider_map_touch
BEFORE UPDATE
ON public.match_provider_map
FOR EACH ROW
EXECUTE FUNCTION public.fn_match_provider_map_touch();

-------------------------------------------------------------------------------
-- 6. DATABÁZOVÉ KOMENTÁŘE
-------------------------------------------------------------------------------

COMMENT ON TABLE public.match_provider_map IS
'Mapování více externích providerových nebo zdrojových identit na jeden kanonický zápas v public.matches.';

COMMENT ON COLUMN public.match_provider_map.match_id IS
'Kanonický identifikátor zápasu z public.matches.';

COMMENT ON COLUMN public.match_provider_map.provider IS
'Kanonický technický kód poskytovatele, zdroje nebo adaptéru. FK nebude přidán před sjednocením providerových kódů.';

COMMENT ON COLUMN public.match_provider_map.provider_match_id IS
'Externí identifikátor zápasu v rámci daného poskytovatele nebo zdroje.';

COMMENT ON COLUMN public.match_provider_map.identity_origin IS
'Význam původu identity: PROVIDER, SOURCE, ADAPTER nebo INTERNAL.';

COMMENT ON COLUMN public.match_provider_map.external_id_kind IS
'Způsob vzniku externího ID: NATIVE, DERIVED nebo HASH.';

COMMENT ON COLUMN public.match_provider_map.mapping_status IS
'Stav mapování: ACTIVE, REVIEW, HOLD, SUPERSEDED nebo REJECTED.';

COMMENT ON COLUMN public.match_provider_map.is_primary IS
'Označuje preferovanou aktivní externí identitu kanonického zápasu.';

COMMENT ON COLUMN public.match_provider_map.confidence_score IS
'Důvěryhodnost mapování v rozsahu 0 až 100.';

COMMENT ON COLUMN public.match_provider_map.source_record_hash IS
'Volitelný SHA-256 otisk původního zdrojového řádku nebo záznamu.';

COMMENT ON COLUMN public.match_provider_map.metadata IS
'Doplňující strukturovaná provenance a auditní metadata ve formátu JSON objektu.';

-------------------------------------------------------------------------------
-- 7. FUNKČNÍ TESTY
-------------------------------------------------------------------------------

DO $tests$
DECLARE
    v_match_1 public.matches.id%TYPE;
    v_match_2 public.matches.id%TYPE;

    v_updated_before timestamptz;
    v_updated_after timestamptz;
BEGIN
    SELECT id
    INTO v_match_1
    FROM public.matches
    ORDER BY id
    LIMIT 1;

    SELECT id
    INTO v_match_2
    FROM public.matches
    WHERE id <> v_match_1
    ORDER BY id
    LIMIT 1;

    IF v_match_1 IS NULL OR v_match_2 IS NULL THEN
        RAISE EXCEPTION
            'VALIDATION_FAILED: Pro test jsou potřeba alespoň dva zápasy v public.matches.';
    END IF;

    ---------------------------------------------------------------------------
    -- Test A: jeden zápas může mít více různých identit
    ---------------------------------------------------------------------------

    INSERT INTO public.match_provider_map
    (
        match_id,
        provider,
        provider_match_id,
        identity_origin,
        external_id_kind,
        mapping_status,
        is_primary,
        confidence_score,
        metadata
    )
    VALUES
    (
        v_match_1,
        '__mm_validate_api_football__',
        '__fixture_1001__',
        'PROVIDER',
        'NATIVE',
        'ACTIVE',
        true,
        100.00,
        '{"validation_test":"primary_identity"}'::jsonb
    );

    INSERT INTO public.match_provider_map
    (
        match_id,
        provider,
        provider_match_id,
        identity_origin,
        external_id_kind,
        mapping_status,
        is_primary,
        confidence_score,
        metadata
    )
    VALUES
    (
        v_match_1,
        '__mm_validate_football_data_uk__',
        '__derived_match_2001__',
        'SOURCE',
        'DERIVED',
        'ACTIVE',
        false,
        98.50,
        '{"validation_test":"secondary_identity"}'::jsonb
    );

    RAISE NOTICE
        'OK TEST A: Jeden kanonický zápas má dvě externí identity.';

    ---------------------------------------------------------------------------
    -- Test B: stejná providerová identita nesmí patřit jinému zápasu
    ---------------------------------------------------------------------------

    BEGIN
        INSERT INTO public.match_provider_map
        (
            match_id,
            provider,
            provider_match_id,
            identity_origin,
            external_id_kind,
            mapping_status
        )
        VALUES
        (
            v_match_2,
            '__mm_validate_api_football__',
            '__fixture_1001__',
            'PROVIDER',
            'NATIVE',
            'ACTIVE'
        );

        RAISE EXCEPTION
            'VALIDATION_FAILED TEST B: Duplicitní providerová identita byla povolena.';
    EXCEPTION
        WHEN unique_violation THEN
            RAISE NOTICE
                'OK TEST B: Duplicitní providerová identita byla správně zablokována.';
    END;

    ---------------------------------------------------------------------------
    -- Test C: jeden zápas nesmí mít dvě aktivní primární identity
    ---------------------------------------------------------------------------

    BEGIN
        INSERT INTO public.match_provider_map
        (
            match_id,
            provider,
            provider_match_id,
            identity_origin,
            external_id_kind,
            mapping_status,
            is_primary
        )
        VALUES
        (
            v_match_1,
            '__mm_validate_second_primary__',
            '__fixture_3001__',
            'PROVIDER',
            'NATIVE',
            'ACTIVE',
            true
        );

        RAISE EXCEPTION
            'VALIDATION_FAILED TEST C: Druhá primární identita byla povolena.';
    EXCEPTION
        WHEN unique_violation THEN
            RAISE NOTICE
                'OK TEST C: Druhá aktivní primární identita byla správně zablokována.';
    END;

    ---------------------------------------------------------------------------
    -- Test D: auditní trigger musí změnit updated_at
    ---------------------------------------------------------------------------

    SELECT updated_at
    INTO v_updated_before
    FROM public.match_provider_map
    WHERE provider = '__mm_validate_api_football__'
      AND provider_match_id = '__fixture_1001__';

    PERFORM pg_sleep(0.02);

    UPDATE public.match_provider_map
    SET metadata =
        metadata ||
        '{"validation_update":"trigger_test"}'::jsonb
    WHERE provider = '__mm_validate_api_football__'
      AND provider_match_id = '__fixture_1001__';

    SELECT updated_at
    INTO v_updated_after
    FROM public.match_provider_map
    WHERE provider = '__mm_validate_api_football__'
      AND provider_match_id = '__fixture_1001__';

    IF v_updated_after <= v_updated_before THEN
        RAISE EXCEPTION
            'VALIDATION_FAILED TEST D: updated_at nebyl triggerem aktualizován.';
    END IF;

    RAISE NOTICE
        'OK TEST D: Auditní trigger správně aktualizoval updated_at a updated_by.';
END
$tests$;

-------------------------------------------------------------------------------
-- 8. VÝSTUP – NAVRŽENÉ SLOUPCE
-------------------------------------------------------------------------------

SELECT
    c.ordinal_position,
    c.column_name,
    c.data_type,
    c.udt_name,
    c.is_nullable,
    c.column_default
FROM information_schema.columns c
WHERE c.table_schema = 'public'
  AND c.table_name = 'match_provider_map'
ORDER BY c.ordinal_position;

-------------------------------------------------------------------------------
-- 9. VÝSTUP – CONSTRAINTS
-------------------------------------------------------------------------------

SELECT
    con.conname AS constraint_name,
    CASE con.contype
        WHEN 'p' THEN 'PRIMARY KEY'
        WHEN 'f' THEN 'FOREIGN KEY'
        WHEN 'u' THEN 'UNIQUE'
        WHEN 'c' THEN 'CHECK'
        ELSE con.contype::text
    END AS constraint_type,
    pg_get_constraintdef(con.oid, true) AS definition
FROM pg_constraint con
WHERE con.conrelid = 'public.match_provider_map'::regclass
ORDER BY
    constraint_type,
    constraint_name;

-------------------------------------------------------------------------------
-- 10. VÝSTUP – INDEXY
-------------------------------------------------------------------------------

SELECT
    indexname,
    indexdef
FROM pg_indexes
WHERE schemaname = 'public'
  AND tablename = 'match_provider_map'
ORDER BY indexname;

-------------------------------------------------------------------------------
-- 11. VÝSTUP – TESTOVACÍ DATA
-------------------------------------------------------------------------------

SELECT
    id,
    match_id,
    provider,
    provider_match_id,
    identity_origin,
    external_id_kind,
    mapping_status,
    is_primary,
    confidence_score,
    metadata,
    created_at,
    updated_at,
    created_by,
    updated_by
FROM public.match_provider_map
ORDER BY id;

-------------------------------------------------------------------------------
-- 12. SOUHRNNÁ VALIDACE
-------------------------------------------------------------------------------

SELECT
    'TABLE_CREATED_IN_TRANSACTION' AS check_name,
    CASE
        WHEN to_regclass('public.match_provider_map') IS NOT NULL
            THEN 'OK'
        ELSE 'FAILED'
    END AS result

UNION ALL

SELECT
    'VALIDATION_ROWS',
    CASE
        WHEN COUNT(*) = 2 THEN 'OK'
        ELSE 'FAILED: ' || COUNT(*)::text
    END
FROM public.match_provider_map

UNION ALL

SELECT
    'MULTIPLE_IDENTITIES_ONE_MATCH',
    CASE
        WHEN COUNT(*) = 2 THEN 'OK'
        ELSE 'FAILED: ' || COUNT(*)::text
    END
FROM public.match_provider_map
WHERE match_id = (
    SELECT match_id
    FROM public.match_provider_map
    ORDER BY id
    LIMIT 1
)

UNION ALL

SELECT
    'ACTIVE_PRIMARY_IDENTITIES',
    CASE
        WHEN COUNT(*) = 1 THEN 'OK'
        ELSE 'FAILED: ' || COUNT(*)::text
    END
FROM public.match_provider_map
WHERE is_primary = true
  AND mapping_status = 'ACTIVE';

-------------------------------------------------------------------------------
-- 13. POVINNÝ ROLLBACK
-------------------------------------------------------------------------------

ROLLBACK;

-------------------------------------------------------------------------------
-- 14. KONEČNÁ KONTROLA, ŽE NIC NEZŮSTALO V DATABÁZI
-------------------------------------------------------------------------------

SELECT
    CASE
        WHEN to_regclass('public.match_provider_map') IS NULL
         AND to_regprocedure(
                'public.fn_match_provider_map_touch()'
             ) IS NULL
        THEN 'VALIDATE_ONLY_OK – ROLLBACK DOKONČEN – DATABÁZE BEZE ZMĚNY'
        ELSE 'VALIDATION_FAILED – NĚKTERÝ TESTOVACÍ OBJEKT ZŮSTAL'
    END AS final_status;