INSERT INTO ops.runtime_entity_audit (
    provider,
    sport_code,
    entity,
    current_state,
    state_reason,
    panel_runner_exists,
    planner_target_exists,
    batch_target_exists,
    pull_confirmed,
    raw_confirmed,
    staging_confirmed,
    provider_map_confirmed,
    public_merge_confirmed,
    downstream_confirmed,
    last_run_group,
    last_check_at,
    last_log_summary,
    db_evidence_summary,
    next_action,
    audit_note,
    created_at,
    updated_at
)
VALUES (
    'api_baseball',
    'BSB',
    'players',
    'BLOCKED',
    'Provider endpoint returned 200 OK but empty response for tested league and team scope.',
    true,
    true,
    false,
    true,
    true,
    false,
    false,
    false,
    false,
    'BSB_PEOPLE',
    NOW(),
    'BSB players runtime test: /players?league=10&season=2024 empty; /players?team=10&season=2024 empty.',
    'stg_api_payloads raw_payload_id=741 and 742 created; staging.players_import inserted=0.',
    'Keep BSB core ready. Revisit BSB players with another provider, paid plan, or different endpoint/scope.',
    'People layer test completed. Runtime works, provider data unavailable for tested scope.',
    NOW(),
    NOW()
)
ON CONFLICT (provider, sport_code, entity)
DO UPDATE SET
    current_state = EXCLUDED.current_state,
    state_reason = EXCLUDED.state_reason,
    panel_runner_exists = EXCLUDED.panel_runner_exists,
    planner_target_exists = EXCLUDED.planner_target_exists,
    batch_target_exists = EXCLUDED.batch_target_exists,
    pull_confirmed = EXCLUDED.pull_confirmed,
    raw_confirmed = EXCLUDED.raw_confirmed,
    staging_confirmed = EXCLUDED.staging_confirmed,
    provider_map_confirmed = EXCLUDED.provider_map_confirmed,
    public_merge_confirmed = EXCLUDED.public_merge_confirmed,
    downstream_confirmed = EXCLUDED.downstream_confirmed,
    last_run_group = EXCLUDED.last_run_group,
    last_check_at = EXCLUDED.last_check_at,
    last_log_summary = EXCLUDED.last_log_summary,
    db_evidence_summary = EXCLUDED.db_evidence_summary,
    next_action = EXCLUDED.next_action,
    audit_note = EXCLUDED.audit_note,
    updated_at = NOW();