-- 740_insert_runtime_entity_audit_ck_core_stage_confirmed.sql

INSERT INTO ops.runtime_entity_audit (
    provider,
    sport_code,
    entity,
    current_state,
    state_reason,
    panel_runner_exists,
    planner_target_exists,
    batch_target_exists,
    pull_confirmed,
    raw_confirmed,
    staging_confirmed,
    provider_map_confirmed,
    public_merge_confirmed,
    downstream_confirmed,
    last_run_group,
    last_run_at,
    last_check_at,
    last_log_summary,
    db_evidence_summary,
    next_action,
    audit_note,
    created_at,
    updated_at
)
VALUES
(
    'api_cricket',
    'CK',
    'fixtures',
    'PARTIAL',
    'CK fixtures raw + staging potvrzeny v novem modelu',
    false,
    false,
    false,
    true,
    true,
    true,
    false,
    false,
    false,
    'CK_CORE',
    now(),
    now(),
    'CK fixtures raw+staging confirmed | stg_api_payloads parsed fixtures=2 | stg_provider_fixtures=44',
    'api_cricket CK fixtures staging potvrzen: 44 rows',
    'Navrhnout a otestovat CK public merge pro fixtures',
    'CK jede pres stg_api_payloads + stg_provider_fixtures',
    now(),
    now()
),
(
    'api_cricket',
    'CK',
    'leagues',
    'PARTIAL',
    'CK leagues raw + staging potvrzeny v novem modelu',
    false,
    false,
    false,
    true,
    true,
    true,
    false,
    false,
    false,
    'CK_CORE',
    now(),
    now(),
    'CK leagues raw+staging confirmed | stg_api_payloads parsed leagues=1 | stg_provider_leagues=32',
    'api_cricket CK leagues staging potvrzen: 32 rows',
    'Navrhnout a otestovat CK public merge pro leagues',
    'CK jede pres stg_api_payloads + stg_provider_leagues',
    now(),
    now()
),
(
    'api_cricket',
    'CK',
    'teams',
    'PARTIAL',
    'CK teams raw + staging potvrzeny v novem modelu',
    false,
    false,
    false,
    true,
    true,
    true,
    false,
    false,
    false,
    'CK_CORE',
    now(),
    now(),
    'CK teams raw+staging confirmed | stg_api_payloads parsed teams=1 | stg_provider_teams=37',
    'api_cricket CK teams staging potvrzen: 37 rows',
    'Navrhnout a otestovat CK public merge pro teams',
    'CK jede pres stg_api_payloads + stg_provider_teams',
    now(),
    now()
);